;***	VLPT.INC
;
;
;	MVDM Virtual Printer Exported Definitions
; ***************************************************************************
;									    *
;			 IBM/Microsoft Confidential			    *
;									    *
;		   Copyright (c) IBM Corporation  1987, 1990		    *
;		   Copyright (c) Microsoft Corp.  1987, 1990		    *
;			     All Rights Reserved			    *
;									    *
; ***************************************************************************
;
;	For include file hierarchy, see MVDM.INC
;
;
;	MODIFICATION HISTORY
;
;



;***	VLPT constants
;


;***	VLPT data types
;


;***	VLPT function prototypes
;

VDHENTRY VDHPrintClose		<HVDM>
