
//  Module Header
//
//  Module Name: WPBUS
//
//  OS/2 Presentation Manager Workplace class definitions
//
//  Copyright (c) International Business Machines Corporation 1991, 1992
//

#ifndef wpbus_idl
#define wpbus_idl

#include "wpdevice.idl"

interface M_WPDevBus;

interface WPDevBus : WPDevice
{

#ifdef __SOMIDL__
  implementation {

    releaseorder: ;

    externalstem = wpbus;
    functionprefix = bus_;
    local;
//    externalprefix = bus_;
    majorversion = 1;
    minorversion = 2;
    filestem = wpbus;
    metaclass = M_WPDevBus;
    callstyle = oidl;
    dllname = "pnp.dll";

    passthru C_h =  ""
"";

/* Private instance data area */

     /* Overridden instance methods area */
  };
#endif /* __SOMIDL__ */
};

interface M_WPDevBus : M_WPDevice
{
  /* New class methods section */

  implementation {

    releaseorder: ;

    externalstem = wpbus;
    functionprefix = busM_;
    local;
//    externalprefix = busM_;
    majorversion = 1;
    minorversion = 2;
    filestem = wpbus;
    callstyle = oidl;
    dllname = "pnp.dll";


    /* Overridden class methods section */
    wpclsInitData:       override;
    wpclsQueryIconData:  override;                                             //bjf152374
    wpclsQueryTitle:     override;
    wpclsUnInitData:     override;
  };

};
#endif  /* wpbus_idl */
