
/*
 * This file was generated by the SOM Compiler.
 * FileName: G:\cwpsh\rel\os2c\include\base\os2\wpfolder.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.14
 *     SOM Emitter emith: 2.43
 */

/*
 *   Module Header
 * 
 *   Module Name: WPOBJECT
 * 
 *   OS/2 Presentation Manager Workplace class definitions
 * 
 *   Copyright (c) International Business Machines Corporation 1991, 1992
 * 
 */


#ifndef SOM_WPFolder_h
#define SOM_WPFolder_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef WPFolder
#define WPFolder SOMObject
#endif
#include <wpfsys.h>

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef WPImageFile
    #define WPImageFile SOMObject
#endif /* WPImageFile */
#ifndef M_WPFileSystem
    #define M_WPFileSystem SOMObject
#endif /* M_WPFileSystem */
#ifndef M_WPFolder
    #define M_WPFolder SOMObject
#endif /* M_WPFolder */

/*
 * End of bindings for IDL types.
 */

/*
 * Passthru lines: File: "C.h", "after"
 */

      /* Folder flags */

      #define FOI_POPULATEDWITHALL      0x0001
      #define FOI_POPULATEDWITHFOLDERS  0x0002
      #define FOI_WORKAREA              0x0004
      #define FOI_CHANGEFONT            0x0008
      #define FOI_WAMINIMIZED           0x0020
      #define FOI_WASTARTONRESTORE      0x0040
      #define FOI_NOREFRESHVIEWS        0x0080
      #define FOI_ASYNCREFRESHONOPEN    0x0100
      #define FOI_TREEPOPULATED         0x0200
      #define FOI_POPULATEINPROGRESS    0x0400
      #define FOI_REFRESHINPROGRESS     0x0800
      #define FOI_FIRSTPOPULATE         0x1000
      #define FOI_WAMCRINPROGRESS       0x2000
      #define FOI_CNRBKGNDOLDFORMAT     0x4000
      #define FOI_CHANGEICONBGNDCOLOR   0x8000
      #define FOI_CHANGEICONTEXTCOLOR   0x00010000
      #define FOI_DELETEINPROGRESS      0x00020000
      #define FOI_CHANGESHADOWTEXTCOLOR 0x00040000

      /* Open views for the wpOpen() method */

      #define OPEN_TREE          101
      #define OPEN_DETAILS       102

      /* State constants for OpenDoc attributes */

      #define MENUBAR_ON         1
      #define MENUBAR_OFF        0
      #define MENUBAR_DEFAULT    2

      #define TITLEBARICONS_ON   1
      #define TITLEBARICONS_OFF  0
      #define TITLEBARICONS_DEFAULT 2

      /* Folder save-restore keys */

      #define IDKEY_FDRCONTENTATTR     2900
      #define IDKEY_FDRTREEATTR        2901
      #define IDKEY_FDRCVLFONT         2902
      #define IDKEY_FDRCVNFONT         2903
      #define IDKEY_FDRCVIFONT         2904
      #define IDKEY_FDRTVLFONT         2905
      #define IDKEY_FDRTVNFONT         2906
      #define IDKEY_FDRDETAILSATTR     2907
      #define IDKEY_FDRDVFONT          2908
      #define IDKEY_FDRDETAILSCLASS    2909
      #define IDKEY_FDRICONPOS         2910
      #define IDKEY_FDRINVISCOLUMNS    2914
      #define IDKEY_FDRINCCLASS        2920
      #define IDKEY_FDRINCNAME         2921
      #define IDKEY_FDRFSYSSEARCHINFO  2922
      #define IDKEY_FILTERCONTENT      2923
      #define IDKEY_CNRBACKGROUND      2924
      #define IDKEY_FDRINCCRITERIA     2925
      #define IDKEY_FDRICONVIEWPOS     2926
      #define IDKEY_FDRSORTCLASS       2927
      #define IDKEY_FDRSORTATTRIBS     2928
      #define IDKEY_FDRSORTINFO        2929
      #define IDKEY_FDRSNEAKYCOUNT     2930
      #define IDKEY_FDRLONGARRAY       2931
      #define IDKEY_FDRSTRARRAY        2932
      #define IDKEY_FDRCNRBACKGROUND   2933
      #define IDKEY_FDRBKGNDIMAGEFILE  2934
      #define IDKEY_FDRBACKGROUND      2935
      #define IDKEY_FDRSELFCLOSE       2936

      #define IDKEY_FDRODMENUBARON     2937
      #define IDKEY_FDRGRIDINFO        2938
      #define IDKEY_FDRTREEVIEWCONTENTS 2939

      /* Constant for wpSetIconTextBackgroundColor */

      #define USE_GLOBAL_COLOR         0x40000000

      /* Constants for wpSetIconTextVisibility and wpQueryIconTextVisibility */

      #define ICON_TEXT_VISIBLE        0x00000001
      #define USE_GLOBAL_VISIBILITY    0x40000000

      /* Constants for wpSet/QueryBackground and wpSet/QueryLockupBackground */

      #define BACKGROUND_NORMAL_IMAGE 0
      #define BACKGROUND_TILED_IMAGE  1
      #define BACKGROUND_SCALED_IMAGE 2
      #define BACKGROUND_COLOR_ONLY   0
      #define BACKGROUND_IMAGE        1

      /* Miscellaneous */

      #define PPFONTSTRSIZE 20

      #define ICONPOSSIZE(pI) ( sizeof(ICONPOS) + strlen(pI->szIdentity) )
      #define PARTIAL_FILLFOLDER_SEM_TIMEOUT 5

      #define GETATTR(View) (View == OPEN_CONTENTS ? _ContentAttr : \
                             (View == OPEN_TREE ? _TreeAttr : _DetailsAttr))
      #define FOLDER_DEFATTRS (CV_ICON | CA_OWNERPAINTBACKGROUND     | \
                               CA_MIXEDTARGETEMPH | CA_OWNERDRAW)
      #define FOLDER_DEFTREEATTRS (CV_ICON | CA_OWNERPAINTBACKGROUND | \
                                   CV_TREE | CA_TREELINE | CA_OWNERDRAW)
      #define FOLDER_DEFDETAILS (CV_DETAIL | CA_OWNERPAINTBACKGROUND | \
                       CV_MINI | CA_DETAILSVIEWTITLES | CA_MIXEDTARGETEMPH)
      #define FOLDER_DEFSORT NULL

      /* wpSearchFolder structures */
       typedef struct _SEARCH_INFO {
          M_WPObject *ClassToBeFound;
          BOOL   fSkipExtendedSearchCriteria;
          PVOID  pvoidExtendedCriteria;
       } SEARCH_INFO;
       typedef SEARCH_INFO *PSEARCH_INFO;



#define WPFolder_MajorVersion 1
#define WPFolder_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define WPFolderNewClass wpfdrc
#pragma linkage(wpfdrc, system)
#define WPFolderClassData wpfdrd
#define WPFolderCClassData wpfdrx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include <wpfolder.h>
/*--------------Migration------------*/
#define WPFolder_classObj WPFolderClassData.classObject
#define _WPFolder WPFolder_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK WPFolderNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(WPFolderNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct WPFolderClassDataStructure {
	SOMClass *classObject;
	somMToken wpSetFldrFlags;
	somMToken wpQueryFldrFlags;
	somMToken wpSetFldrFont;
	somMToken wpQueryFldrFont;
	somMToken wpSetNextIconPos;
	somMToken wpQueryNextIconPos;
	somMToken wpPopulate;
	somMToken wpAddToContent;
	somMToken wpQueryContent;
	somMToken wpAddFolderView1Page;
	somMToken wpAddFolderView2Page;
	somMToken wpAddFolderView3Page;
	somMToken wpAddFolderIncludePage;
	somMToken wpAddFolderSortPage;
	somMToken wpAddFolderBackgroundPage;
	somMToken wpInitIconPosData;
	somMToken wpFreeIconPosData;
	somMToken wpQueryIconPosition;
	somMToken wpStoreIconPosData;
	somMToken wpDeleteFromContent;
	somMToken wpSetFldrAttr;
	somMToken wpQueryFldrAttr;
	somMToken wpSetFldrSort;
	somMToken wpQueryFldrSort;
	somMToken wpRestoreFldrRunObjs;
	somMToken wpStoreFldrRunObjs;
	somMToken withdrawn30;
	somMToken withdrawn31;
	somMToken wpDeleteContents;
	somMToken wpQueryOpenFolders;
	somMToken wpFolderPrivate1;
	somMToken wpSearchFolder;
	somMToken wpSetFldrDetailsClass;
	somMToken wpQueryFldrDetailsClass;
	somMToken wpRefresh;
	somMToken wpSetDetailsColumnVisibility;
	somMToken wpIsDetailsColumnVisible;
	somMToken wpFolderPrivate2;
	somMToken wpFolderPrivate3;
	somMToken wpFolderPrivate4;
	somMToken wpFolderPrivate5;
	somMToken wpSetFldrSortClass;
	somMToken wpQueryFldrSortClass;
	somMToken wpSetSortAttribAvailable;
	somMToken wpIsSortAttribAvailable;
	somMToken wpFolderPrivate6;
	somMToken wpContainsFolders;
	somMToken wpFolderPrivate7;
	somMToken wpQueryIconViewPos;
	somMToken wpQueryDefaultView;
	somMToken wpAddFirstChild;
	somMToken wpFolderPrivate8;
	somMToken wpHideFldrRunObjs;
	somMToken wpFolderPrivate9;
	somMToken wpFolderPrivate10;
	somMToken wpFolderPrivate11;
	somMToken wpFolderPrivate12;
	somMToken wpFolderPrivate13;
	somMToken wpFolderPrivate14;
	somMToken wpFolderPrivate15;
	somMToken wpFolderPrivate16;
	somMToken wpFolderPrivate17;
	somMToken wpFolderPrivate18;
	somMToken wpFolderPrivate19;
	somMToken wpFolderPrivate20;
	somMToken wpFolderPrivate21;
	somMToken wpFolderPrivate22;
	somMToken wpFolderPrivate23;
	somMToken wpModifyFldrFlags;
	somMToken wpFolderPrivate24;
	somMToken wpFolderPrivate25;
	somMToken wpFolderPrivate26;
	somMToken wpFolderPrivate27;
	somMToken wpFolderPrivate28;
	somMToken wpQueryIconTextBackgroundColor;
	somMToken wpSetIconTextBackgroundColor;
	somMToken wpFolderPrivate29;
	somMToken wpFolderPrivate30;
	somMToken wpFolderPrivate31;
	somMToken wpQueryIconTextColor;
	somMToken wpSetIconTextColor;
	somMToken wpQueryIconTextVisibility;
	somMToken wpSetIconTextVisibility;
	somMToken wpAddFolderSelfClosePage;
	somMToken wpFolderPrivate32;
	somMToken wpFolderPrivate33;
	somMToken wpFolderPrivate34;
	somMToken wpFolderPrivate35;
	somMToken wpFolderPrivate36;
	somMToken wpFolderPrivate37;
	somMToken wpFolderPrivate38;
	somMToken wpFolderPrivate39;
	somMToken wpFolderPrivate40;
	somMToken wpFolderPrivate41;
	somMToken wpFolderPrivate42;
	somMToken wpAddFolderMenu2Page;
	somMToken wpSetMenuBarVisibility;
	somMToken wpQueryMenuBarVisibility;
	somMToken wpFolderPrivate43;
	somMToken wpFolderPrivate44;
	somMToken wpFolderPrivate45;
	somMToken wpFlushNotifications;
	somMToken wpSetShadowTextColor;
	somMToken wpQueryShadowTextColor;
	somMToken wpSetFldrBackground;
	somMToken wpQueryFldrBackground;
	somMToken wpSetFldrGrid;
	somMToken wpQueryFldrGrid;
} SOMDLINK WPFolderClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct WPFolderCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK WPFolderCClassData;

/*
 * New and Renew macros for WPFolder
 */
#define WPFolderNew() \
   ( _WPFolder ? \
	_somNew(_WPFolder) \
	: ( WPFolderNewClass(\
		WPFolder_MajorVersion, \
		WPFolder_MinorVersion),\
	   _somNew(_WPFolder)))
#define WPFolderRenew(buf) \
   ( _WPFolder ? \
	_somRenew(_WPFolder, buf) \
	: ( WPFolderNewClass(\
		WPFolder_MajorVersion, \
		WPFolder_MinorVersion),\
	   _somRenew(_WPFolder, buf)))

/*
 * Override method: wpInitData
 */
#define WPFolder_wpInitData(somSelf) \
	WPObject_wpInitData(somSelf)

/*
 * Override method: wpUnInitData
 */
#define WPFolder_wpUnInitData(somSelf) \
	WPObject_wpUnInitData(somSelf)

/*
 * Override method: wpFree
 */
#define WPFolder_wpFree(somSelf) \
	WPObject_wpFree(somSelf)

/*
 * Override method: wpDelete
 */
#define WPFolder_wpDelete(somSelf,fConfirmations) \
	WPObject_wpDelete(somSelf,fConfirmations)

/*
 * Override method: wpConfirmDelete
 */
#define WPFolder_wpConfirmDelete(somSelf,fConfirmations) \
	WPObject_wpConfirmDelete(somSelf,fConfirmations)

/*
 * Override method: wpSaveState
 */
#define WPFolder_wpSaveState(somSelf) \
	WPObject_wpSaveState(somSelf)

/*
 * Override method: wpRestoreState
 */
#define WPFolder_wpRestoreState(somSelf,ulReserved) \
	WPObject_wpRestoreState(somSelf,ulReserved)

/*
 * Override method: wpMenuItemSelected
 */
#define WPFolder_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)

/*
 * Override method: wpAddSettingsPages
 */
#define WPFolder_wpAddSettingsPages(somSelf,hwndNotebook) \
	WPObject_wpAddSettingsPages(somSelf,hwndNotebook)

/*
 * Override method: wpOpen
 */
#define WPFolder_wpOpen(somSelf,hwndCnr,ulView,param) \
	WPObject_wpOpen(somSelf,hwndCnr,ulView,param)

/*
 * Override method: wpSetup
 */
#define WPFolder_wpSetup(somSelf,pszSetupString) \
	WPObject_wpSetup(somSelf,pszSetupString)

/*
 * Override method: wpMoveObject
 */
#define WPFolder_wpMoveObject(somSelf,Folder) \
	WPObject_wpMoveObject(somSelf,Folder)

/*
 * Override method: wpDrop
 */
#define WPFolder_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem) \
	WPObject_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem)

/*
 * Override method: wpDragOver
 */
#define WPFolder_wpDragOver(somSelf,hwndCnr,pdrgInfo) \
	WPObject_wpDragOver(somSelf,hwndCnr,pdrgInfo)

/*
 * Override method: wpMenuItemHelpSelected
 */
#define WPFolder_wpMenuItemHelpSelected(somSelf,MenuId) \
	WPObject_wpMenuItemHelpSelected(somSelf,MenuId)

/*
 * Override method: wpAddFile3Page
 */
#define WPFolder_wpAddFile3Page(somSelf,hwndNotebook) \
	WPFileSystem_wpAddFile3Page(somSelf,hwndNotebook)

/*
 * Override method: wpAddFile2Page
 */
#define WPFolder_wpAddFile2Page(somSelf,hwndNotebook) \
	WPFileSystem_wpAddFile2Page(somSelf,hwndNotebook)

/*
 * Override method: wpFormatDragItem
 */
#define WPFolder_wpFormatDragItem(somSelf,pdrgItem) \
	WPObject_wpFormatDragItem(somSelf,pdrgItem)

/*
 * Override method: wpRender
 */
#define WPFolder_wpRender(somSelf,pdxfer) \
	WPObject_wpRender(somSelf,pdxfer)

/*
 * Override method: wpRefresh
 */
#define WPFolder_wpRefresh(somSelf,ulView,pReserved) \
	WPFileSystem_wpRefresh(somSelf,ulView,pReserved)

/*
 * Override method: wpQueryDefaultView
 */
#define WPFolder_wpQueryDefaultView(somSelf) \
	WPObject_wpQueryDefaultView(somSelf)

/*
 * Override method: wpRenderComplete
 */
#define WPFolder_wpRenderComplete(somSelf,pdxfer,ulResult) \
	WPObject_wpRenderComplete(somSelf,pdxfer,ulResult)

/*
 * Override method: wpAddFileMenuPage
 */
#define WPFolder_wpAddFileMenuPage(somSelf,hwndNotebook) \
	WPFileSystem_wpAddFileMenuPage(somSelf,hwndNotebook)

/*
 * Override method: wpQueryDefaultHelp
 */
#define WPFolder_wpQueryDefaultHelp(somSelf,pHelpPanelId,HelpLibrary) \
	WPObject_wpQueryDefaultHelp(somSelf,pHelpPanelId,HelpLibrary)

/*
 * Override method: wpObjectReady
 */
#define WPFolder_wpObjectReady(somSelf,ulCode,refObject) \
	WPObject_wpObjectReady(somSelf,ulCode,refObject)

/*
 * Override method: wpAddObjectWindowPage
 */
#define WPFolder_wpAddObjectWindowPage(somSelf,hwndNotebook) \
	WPObject_wpAddObjectWindowPage(somSelf,hwndNotebook)

/*
 * Override method: wpModifyMenu
 */
#define WPFolder_wpModifyMenu(somSelf,hwndMenu,hwndCnr,iPosition,ulMenuType,ulView,ulReserved) \
	WPObject_wpModifyMenu(somSelf,hwndMenu,hwndCnr,iPosition,ulMenuType,ulView,ulReserved)

/*
 * Override method: wpFilterMenu
 */
#define WPFolder_wpFilterMenu(somSelf,pFlags,hwndCnr,fMultiSelect,ulMenuType,ulView,ulReserved) \
	WPObject_wpFilterMenu(somSelf,pFlags,hwndCnr,fMultiSelect,ulMenuType,ulView,ulReserved)

/*
 * Override method: wpDisplayMenu
 */
#define WPFolder_wpDisplayMenu(somSelf,hwndOwner,hwndClient,ptlPopupPt,ulMenuType,ulReserved) \
	WPObject_wpDisplayMenu(somSelf,hwndOwner,hwndClient,ptlPopupPt,ulMenuType,ulReserved)

/*
 * Override method: somDefaultInit
 */
#define WPFolder_somDefaultInit(somSelf,ctrl) \
	SOMObject_somDefaultInit(somSelf,ctrl)

/*
 * Override method: somDestruct
 */
#define WPFolder_somDestruct(somSelf,doFree,ctrl) \
	SOMObject_somDestruct(somSelf,doFree,ctrl)

/*
 * Override method: wpSetIconData
 */
#define WPFolder_wpSetIconData(somSelf,pIconInfo) \
	WPObject_wpSetIconData(somSelf,pIconInfo)

/*
 * New Method: wpSetFldrFlags
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpSetFldrFlags(WPFolder *somSelf, 
		ULONG ulFlags);
#pragma linkage(somTP_WPFolder_wpSetFldrFlags, system)
typedef somTP_WPFolder_wpSetFldrFlags *somTD_WPFolder_wpSetFldrFlags;
#define somMD_WPFolder_wpSetFldrFlags "::WPFolder::wpSetFldrFlags"
#define WPFolder_wpSetFldrFlags(somSelf,ulFlags) \
    (SOM_Resolve(somSelf, WPFolder, wpSetFldrFlags) \
	(somSelf,ulFlags))
#ifndef SOMGD_wpSetFldrFlags
    #if (defined(_wpSetFldrFlags) || defined(__wpSetFldrFlags))
        #undef _wpSetFldrFlags
        #undef __wpSetFldrFlags
        #define SOMGD_wpSetFldrFlags 1
    #else
        #define _wpSetFldrFlags WPFolder_wpSetFldrFlags
    #endif /* _wpSetFldrFlags */
#endif /* SOMGD_wpSetFldrFlags */

/*
 * New Method: wpQueryFldrFlags
 */
typedef ULONG   SOMLINK somTP_WPFolder_wpQueryFldrFlags(WPFolder *somSelf);
#pragma linkage(somTP_WPFolder_wpQueryFldrFlags, system)
typedef somTP_WPFolder_wpQueryFldrFlags *somTD_WPFolder_wpQueryFldrFlags;
#define somMD_WPFolder_wpQueryFldrFlags "::WPFolder::wpQueryFldrFlags"
#define WPFolder_wpQueryFldrFlags(somSelf) \
    (SOM_Resolve(somSelf, WPFolder, wpQueryFldrFlags) \
	(somSelf))
#ifndef SOMGD_wpQueryFldrFlags
    #if (defined(_wpQueryFldrFlags) || defined(__wpQueryFldrFlags))
        #undef _wpQueryFldrFlags
        #undef __wpQueryFldrFlags
        #define SOMGD_wpQueryFldrFlags 1
    #else
        #define _wpQueryFldrFlags WPFolder_wpQueryFldrFlags
    #endif /* _wpQueryFldrFlags */
#endif /* SOMGD_wpQueryFldrFlags */

/*
 * New Method: wpSetFldrFont
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpSetFldrFont(WPFolder *somSelf, 
		PSZ pszFont, 
		ULONG ulView);
#pragma linkage(somTP_WPFolder_wpSetFldrFont, system)
typedef somTP_WPFolder_wpSetFldrFont *somTD_WPFolder_wpSetFldrFont;
#define somMD_WPFolder_wpSetFldrFont "::WPFolder::wpSetFldrFont"
#define WPFolder_wpSetFldrFont(somSelf,pszFont,ulView) \
    (SOM_Resolve(somSelf, WPFolder, wpSetFldrFont) \
	(somSelf,pszFont,ulView))
#ifndef SOMGD_wpSetFldrFont
    #if (defined(_wpSetFldrFont) || defined(__wpSetFldrFont))
        #undef _wpSetFldrFont
        #undef __wpSetFldrFont
        #define SOMGD_wpSetFldrFont 1
    #else
        #define _wpSetFldrFont WPFolder_wpSetFldrFont
    #endif /* _wpSetFldrFont */
#endif /* SOMGD_wpSetFldrFont */

/*
 * New Method: wpQueryFldrFont
 */
typedef PSZ   SOMLINK somTP_WPFolder_wpQueryFldrFont(WPFolder *somSelf, 
		ULONG ulView);
#pragma linkage(somTP_WPFolder_wpQueryFldrFont, system)
typedef somTP_WPFolder_wpQueryFldrFont *somTD_WPFolder_wpQueryFldrFont;
#define somMD_WPFolder_wpQueryFldrFont "::WPFolder::wpQueryFldrFont"
#define WPFolder_wpQueryFldrFont(somSelf,ulView) \
    (SOM_Resolve(somSelf, WPFolder, wpQueryFldrFont) \
	(somSelf,ulView))
#ifndef SOMGD_wpQueryFldrFont
    #if (defined(_wpQueryFldrFont) || defined(__wpQueryFldrFont))
        #undef _wpQueryFldrFont
        #undef __wpQueryFldrFont
        #define SOMGD_wpQueryFldrFont 1
    #else
        #define _wpQueryFldrFont WPFolder_wpQueryFldrFont
    #endif /* _wpQueryFldrFont */
#endif /* SOMGD_wpQueryFldrFont */

/*
 * New Method: wpSetFldrAttr
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpSetFldrAttr(WPFolder *somSelf, 
		ULONG Attr, 
		ULONG ulView);
#pragma linkage(somTP_WPFolder_wpSetFldrAttr, system)
typedef somTP_WPFolder_wpSetFldrAttr *somTD_WPFolder_wpSetFldrAttr;
#define somMD_WPFolder_wpSetFldrAttr "::WPFolder::wpSetFldrAttr"
#define WPFolder_wpSetFldrAttr(somSelf,Attr,ulView) \
    (SOM_Resolve(somSelf, WPFolder, wpSetFldrAttr) \
	(somSelf,Attr,ulView))
#ifndef SOMGD_wpSetFldrAttr
    #if (defined(_wpSetFldrAttr) || defined(__wpSetFldrAttr))
        #undef _wpSetFldrAttr
        #undef __wpSetFldrAttr
        #define SOMGD_wpSetFldrAttr 1
    #else
        #define _wpSetFldrAttr WPFolder_wpSetFldrAttr
    #endif /* _wpSetFldrAttr */
#endif /* SOMGD_wpSetFldrAttr */

/*
 * New Method: wpQueryFldrAttr
 */
typedef ULONG   SOMLINK somTP_WPFolder_wpQueryFldrAttr(WPFolder *somSelf, 
		ULONG ulView);
#pragma linkage(somTP_WPFolder_wpQueryFldrAttr, system)
typedef somTP_WPFolder_wpQueryFldrAttr *somTD_WPFolder_wpQueryFldrAttr;
#define somMD_WPFolder_wpQueryFldrAttr "::WPFolder::wpQueryFldrAttr"
#define WPFolder_wpQueryFldrAttr(somSelf,ulView) \
    (SOM_Resolve(somSelf, WPFolder, wpQueryFldrAttr) \
	(somSelf,ulView))
#ifndef SOMGD_wpQueryFldrAttr
    #if (defined(_wpQueryFldrAttr) || defined(__wpQueryFldrAttr))
        #undef _wpQueryFldrAttr
        #undef __wpQueryFldrAttr
        #define SOMGD_wpQueryFldrAttr 1
    #else
        #define _wpQueryFldrAttr WPFolder_wpQueryFldrAttr
    #endif /* _wpQueryFldrAttr */
#endif /* SOMGD_wpQueryFldrAttr */

/*
 * New Method: wpSetNextIconPos
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpSetNextIconPos(WPFolder *somSelf, 
		PPOINTL pptl);
#pragma linkage(somTP_WPFolder_wpSetNextIconPos, system)
typedef somTP_WPFolder_wpSetNextIconPos *somTD_WPFolder_wpSetNextIconPos;
#define somMD_WPFolder_wpSetNextIconPos "::WPFolder::wpSetNextIconPos"
#define WPFolder_wpSetNextIconPos(somSelf,pptl) \
    (SOM_Resolve(somSelf, WPFolder, wpSetNextIconPos) \
	(somSelf,pptl))
#ifndef SOMGD_wpSetNextIconPos
    #if (defined(_wpSetNextIconPos) || defined(__wpSetNextIconPos))
        #undef _wpSetNextIconPos
        #undef __wpSetNextIconPos
        #define SOMGD_wpSetNextIconPos 1
    #else
        #define _wpSetNextIconPos WPFolder_wpSetNextIconPos
    #endif /* _wpSetNextIconPos */
#endif /* SOMGD_wpSetNextIconPos */

/*
 * New Method: wpQueryNextIconPos
 */
typedef PPOINTL   SOMLINK somTP_WPFolder_wpQueryNextIconPos(WPFolder *somSelf);
#pragma linkage(somTP_WPFolder_wpQueryNextIconPos, system)
typedef somTP_WPFolder_wpQueryNextIconPos *somTD_WPFolder_wpQueryNextIconPos;
#define somMD_WPFolder_wpQueryNextIconPos "::WPFolder::wpQueryNextIconPos"
#define WPFolder_wpQueryNextIconPos(somSelf) \
    (SOM_Resolve(somSelf, WPFolder, wpQueryNextIconPos) \
	(somSelf))
#ifndef SOMGD_wpQueryNextIconPos
    #if (defined(_wpQueryNextIconPos) || defined(__wpQueryNextIconPos))
        #undef _wpQueryNextIconPos
        #undef __wpQueryNextIconPos
        #define SOMGD_wpQueryNextIconPos 1
    #else
        #define _wpQueryNextIconPos WPFolder_wpQueryNextIconPos
    #endif /* _wpQueryNextIconPos */
#endif /* SOMGD_wpQueryNextIconPos */

/*
 * New Method: wpPopulate
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpPopulate(WPFolder *somSelf, 
		ULONG ulReserved, 
		PSZ pszPath, 
		BOOL fFoldersOnly);
#pragma linkage(somTP_WPFolder_wpPopulate, system)
typedef somTP_WPFolder_wpPopulate *somTD_WPFolder_wpPopulate;
#define somMD_WPFolder_wpPopulate "::WPFolder::wpPopulate"
#define WPFolder_wpPopulate(somSelf,ulReserved,pszPath,fFoldersOnly) \
    (SOM_Resolve(somSelf, WPFolder, wpPopulate) \
	(somSelf,ulReserved,pszPath,fFoldersOnly))
#ifndef SOMGD_wpPopulate
    #if (defined(_wpPopulate) || defined(__wpPopulate))
        #undef _wpPopulate
        #undef __wpPopulate
        #define SOMGD_wpPopulate 1
    #else
        #define _wpPopulate WPFolder_wpPopulate
    #endif /* _wpPopulate */
#endif /* SOMGD_wpPopulate */

/*
 * New Method: wpQueryContent
 */
typedef WPObject*   SOMLINK somTP_WPFolder_wpQueryContent(WPFolder *somSelf, 
		WPObject* Object, 
		ULONG ulOption);
#pragma linkage(somTP_WPFolder_wpQueryContent, system)
typedef somTP_WPFolder_wpQueryContent *somTD_WPFolder_wpQueryContent;
#define somMD_WPFolder_wpQueryContent "::WPFolder::wpQueryContent"
#define WPFolder_wpQueryContent(somSelf,Object,ulOption) \
    (SOM_Resolve(somSelf, WPFolder, wpQueryContent) \
	(somSelf,Object,ulOption))
#ifndef SOMGD_wpQueryContent
    #if (defined(_wpQueryContent) || defined(__wpQueryContent))
        #undef _wpQueryContent
        #undef __wpQueryContent
        #define SOMGD_wpQueryContent 1
    #else
        #define _wpQueryContent WPFolder_wpQueryContent
    #endif /* _wpQueryContent */
#endif /* SOMGD_wpQueryContent */

/*
 * New Method: wpAddFolderView1Page
 */
typedef ULONG   SOMLINK somTP_WPFolder_wpAddFolderView1Page(WPFolder *somSelf, 
		HWND hwndNotebook);
#pragma linkage(somTP_WPFolder_wpAddFolderView1Page, system)
typedef somTP_WPFolder_wpAddFolderView1Page *somTD_WPFolder_wpAddFolderView1Page;
#define somMD_WPFolder_wpAddFolderView1Page "::WPFolder::wpAddFolderView1Page"
#define WPFolder_wpAddFolderView1Page(somSelf,hwndNotebook) \
    (SOM_Resolve(somSelf, WPFolder, wpAddFolderView1Page) \
	(somSelf,hwndNotebook))
#ifndef SOMGD_wpAddFolderView1Page
    #if (defined(_wpAddFolderView1Page) || defined(__wpAddFolderView1Page))
        #undef _wpAddFolderView1Page
        #undef __wpAddFolderView1Page
        #define SOMGD_wpAddFolderView1Page 1
    #else
        #define _wpAddFolderView1Page WPFolder_wpAddFolderView1Page
    #endif /* _wpAddFolderView1Page */
#endif /* SOMGD_wpAddFolderView1Page */

/*
 * New Method: wpAddFolderView2Page
 */
typedef ULONG   SOMLINK somTP_WPFolder_wpAddFolderView2Page(WPFolder *somSelf, 
		HWND hwndNotebook);
#pragma linkage(somTP_WPFolder_wpAddFolderView2Page, system)
typedef somTP_WPFolder_wpAddFolderView2Page *somTD_WPFolder_wpAddFolderView2Page;
#define somMD_WPFolder_wpAddFolderView2Page "::WPFolder::wpAddFolderView2Page"
#define WPFolder_wpAddFolderView2Page(somSelf,hwndNotebook) \
    (SOM_Resolve(somSelf, WPFolder, wpAddFolderView2Page) \
	(somSelf,hwndNotebook))
#ifndef SOMGD_wpAddFolderView2Page
    #if (defined(_wpAddFolderView2Page) || defined(__wpAddFolderView2Page))
        #undef _wpAddFolderView2Page
        #undef __wpAddFolderView2Page
        #define SOMGD_wpAddFolderView2Page 1
    #else
        #define _wpAddFolderView2Page WPFolder_wpAddFolderView2Page
    #endif /* _wpAddFolderView2Page */
#endif /* SOMGD_wpAddFolderView2Page */

/*
 * New Method: wpAddFolderView3Page
 */
typedef ULONG   SOMLINK somTP_WPFolder_wpAddFolderView3Page(WPFolder *somSelf, 
		HWND hwndNotebook);
#pragma linkage(somTP_WPFolder_wpAddFolderView3Page, system)
typedef somTP_WPFolder_wpAddFolderView3Page *somTD_WPFolder_wpAddFolderView3Page;
#define somMD_WPFolder_wpAddFolderView3Page "::WPFolder::wpAddFolderView3Page"
#define WPFolder_wpAddFolderView3Page(somSelf,hwndNotebook) \
    (SOM_Resolve(somSelf, WPFolder, wpAddFolderView3Page) \
	(somSelf,hwndNotebook))
#ifndef SOMGD_wpAddFolderView3Page
    #if (defined(_wpAddFolderView3Page) || defined(__wpAddFolderView3Page))
        #undef _wpAddFolderView3Page
        #undef __wpAddFolderView3Page
        #define SOMGD_wpAddFolderView3Page 1
    #else
        #define _wpAddFolderView3Page WPFolder_wpAddFolderView3Page
    #endif /* _wpAddFolderView3Page */
#endif /* SOMGD_wpAddFolderView3Page */

/*
 * New Method: wpAddFolderIncludePage
 */
typedef ULONG   SOMLINK somTP_WPFolder_wpAddFolderIncludePage(WPFolder *somSelf, 
		HWND hwndNotebook);
#pragma linkage(somTP_WPFolder_wpAddFolderIncludePage, system)
typedef somTP_WPFolder_wpAddFolderIncludePage *somTD_WPFolder_wpAddFolderIncludePage;
#define somMD_WPFolder_wpAddFolderIncludePage "::WPFolder::wpAddFolderIncludePage"
#define WPFolder_wpAddFolderIncludePage(somSelf,hwndNotebook) \
    (SOM_Resolve(somSelf, WPFolder, wpAddFolderIncludePage) \
	(somSelf,hwndNotebook))
#ifndef SOMGD_wpAddFolderIncludePage
    #if (defined(_wpAddFolderIncludePage) || defined(__wpAddFolderIncludePage))
        #undef _wpAddFolderIncludePage
        #undef __wpAddFolderIncludePage
        #define SOMGD_wpAddFolderIncludePage 1
    #else
        #define _wpAddFolderIncludePage WPFolder_wpAddFolderIncludePage
    #endif /* _wpAddFolderIncludePage */
#endif /* SOMGD_wpAddFolderIncludePage */

/*
 * New Method: wpAddFolderSortPage
 */
typedef ULONG   SOMLINK somTP_WPFolder_wpAddFolderSortPage(WPFolder *somSelf, 
		HWND hwndNotebook);
#pragma linkage(somTP_WPFolder_wpAddFolderSortPage, system)
typedef somTP_WPFolder_wpAddFolderSortPage *somTD_WPFolder_wpAddFolderSortPage;
#define somMD_WPFolder_wpAddFolderSortPage "::WPFolder::wpAddFolderSortPage"
#define WPFolder_wpAddFolderSortPage(somSelf,hwndNotebook) \
    (SOM_Resolve(somSelf, WPFolder, wpAddFolderSortPage) \
	(somSelf,hwndNotebook))
#ifndef SOMGD_wpAddFolderSortPage
    #if (defined(_wpAddFolderSortPage) || defined(__wpAddFolderSortPage))
        #undef _wpAddFolderSortPage
        #undef __wpAddFolderSortPage
        #define SOMGD_wpAddFolderSortPage 1
    #else
        #define _wpAddFolderSortPage WPFolder_wpAddFolderSortPage
    #endif /* _wpAddFolderSortPage */
#endif /* SOMGD_wpAddFolderSortPage */

/*
 * New Method: wpAddFolderBackgroundPage
 */
typedef ULONG   SOMLINK somTP_WPFolder_wpAddFolderBackgroundPage(WPFolder *somSelf, 
		HWND hwndNotebook);
#pragma linkage(somTP_WPFolder_wpAddFolderBackgroundPage, system)
typedef somTP_WPFolder_wpAddFolderBackgroundPage *somTD_WPFolder_wpAddFolderBackgroundPage;
#define somMD_WPFolder_wpAddFolderBackgroundPage "::WPFolder::wpAddFolderBackgroundPage"
#define WPFolder_wpAddFolderBackgroundPage(somSelf,hwndNotebook) \
    (SOM_Resolve(somSelf, WPFolder, wpAddFolderBackgroundPage) \
	(somSelf,hwndNotebook))
#ifndef SOMGD_wpAddFolderBackgroundPage
    #if (defined(_wpAddFolderBackgroundPage) || defined(__wpAddFolderBackgroundPage))
        #undef _wpAddFolderBackgroundPage
        #undef __wpAddFolderBackgroundPage
        #define SOMGD_wpAddFolderBackgroundPage 1
    #else
        #define _wpAddFolderBackgroundPage WPFolder_wpAddFolderBackgroundPage
    #endif /* _wpAddFolderBackgroundPage */
#endif /* SOMGD_wpAddFolderBackgroundPage */

/*
 * New Method: wpAddFolderMenu2Page
 */
typedef ULONG   SOMLINK somTP_WPFolder_wpAddFolderMenu2Page(WPFolder *somSelf, 
		HWND hwndNotebook);
#pragma linkage(somTP_WPFolder_wpAddFolderMenu2Page, system)
typedef somTP_WPFolder_wpAddFolderMenu2Page *somTD_WPFolder_wpAddFolderMenu2Page;
#define somMD_WPFolder_wpAddFolderMenu2Page "::WPFolder::wpAddFolderMenu2Page"
#define WPFolder_wpAddFolderMenu2Page(somSelf,hwndNotebook) \
    (SOM_Resolve(somSelf, WPFolder, wpAddFolderMenu2Page) \
	(somSelf,hwndNotebook))
#ifndef SOMGD_wpAddFolderMenu2Page
    #if (defined(_wpAddFolderMenu2Page) || defined(__wpAddFolderMenu2Page))
        #undef _wpAddFolderMenu2Page
        #undef __wpAddFolderMenu2Page
        #define SOMGD_wpAddFolderMenu2Page 1
    #else
        #define _wpAddFolderMenu2Page WPFolder_wpAddFolderMenu2Page
    #endif /* _wpAddFolderMenu2Page */
#endif /* SOMGD_wpAddFolderMenu2Page */

/*
 * New Method: wpAddFolderSelfClosePage
 */
typedef ULONG   SOMLINK somTP_WPFolder_wpAddFolderSelfClosePage(WPFolder *somSelf, 
		HWND hwndNotebook);
#pragma linkage(somTP_WPFolder_wpAddFolderSelfClosePage, system)
typedef somTP_WPFolder_wpAddFolderSelfClosePage *somTD_WPFolder_wpAddFolderSelfClosePage;
#define somMD_WPFolder_wpAddFolderSelfClosePage "::WPFolder::wpAddFolderSelfClosePage"
#define WPFolder_wpAddFolderSelfClosePage(somSelf,hwndNotebook) \
    (SOM_Resolve(somSelf, WPFolder, wpAddFolderSelfClosePage) \
	(somSelf,hwndNotebook))
#ifndef SOMGD_wpAddFolderSelfClosePage
    #if (defined(_wpAddFolderSelfClosePage) || defined(__wpAddFolderSelfClosePage))
        #undef _wpAddFolderSelfClosePage
        #undef __wpAddFolderSelfClosePage
        #define SOMGD_wpAddFolderSelfClosePage 1
    #else
        #define _wpAddFolderSelfClosePage WPFolder_wpAddFolderSelfClosePage
    #endif /* _wpAddFolderSelfClosePage */
#endif /* SOMGD_wpAddFolderSelfClosePage */

/*
 * New Method: wpInitIconPosData
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpInitIconPosData(WPFolder *somSelf);
#pragma linkage(somTP_WPFolder_wpInitIconPosData, system)
typedef somTP_WPFolder_wpInitIconPosData *somTD_WPFolder_wpInitIconPosData;
#define somMD_WPFolder_wpInitIconPosData "::WPFolder::wpInitIconPosData"
#define WPFolder_wpInitIconPosData(somSelf) \
    (SOM_Resolve(somSelf, WPFolder, wpInitIconPosData) \
	(somSelf))
#ifndef SOMGD_wpInitIconPosData
    #if (defined(_wpInitIconPosData) || defined(__wpInitIconPosData))
        #undef _wpInitIconPosData
        #undef __wpInitIconPosData
        #define SOMGD_wpInitIconPosData 1
    #else
        #define _wpInitIconPosData WPFolder_wpInitIconPosData
    #endif /* _wpInitIconPosData */
#endif /* SOMGD_wpInitIconPosData */

/*
 * New Method: wpFreeIconPosData
 */
typedef void   SOMLINK somTP_WPFolder_wpFreeIconPosData(WPFolder *somSelf);
#pragma linkage(somTP_WPFolder_wpFreeIconPosData, system)
typedef somTP_WPFolder_wpFreeIconPosData *somTD_WPFolder_wpFreeIconPosData;
#define somMD_WPFolder_wpFreeIconPosData "::WPFolder::wpFreeIconPosData"
#define WPFolder_wpFreeIconPosData(somSelf) \
    (SOM_Resolve(somSelf, WPFolder, wpFreeIconPosData) \
	(somSelf))
#ifndef SOMGD_wpFreeIconPosData
    #if (defined(_wpFreeIconPosData) || defined(__wpFreeIconPosData))
        #undef _wpFreeIconPosData
        #undef __wpFreeIconPosData
        #define SOMGD_wpFreeIconPosData 1
    #else
        #define _wpFreeIconPosData WPFolder_wpFreeIconPosData
    #endif /* _wpFreeIconPosData */
#endif /* SOMGD_wpFreeIconPosData */

/*
 * New Method: wpStoreIconPosData
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpStoreIconPosData(WPFolder *somSelf, 
		PICONPOS pIconPos, 
		ULONG cbSize);
#pragma linkage(somTP_WPFolder_wpStoreIconPosData, system)
typedef somTP_WPFolder_wpStoreIconPosData *somTD_WPFolder_wpStoreIconPosData;
#define somMD_WPFolder_wpStoreIconPosData "::WPFolder::wpStoreIconPosData"
#define WPFolder_wpStoreIconPosData(somSelf,pIconPos,cbSize) \
    (SOM_Resolve(somSelf, WPFolder, wpStoreIconPosData) \
	(somSelf,pIconPos,cbSize))
#ifndef SOMGD_wpStoreIconPosData
    #if (defined(_wpStoreIconPosData) || defined(__wpStoreIconPosData))
        #undef _wpStoreIconPosData
        #undef __wpStoreIconPosData
        #define SOMGD_wpStoreIconPosData 1
    #else
        #define _wpStoreIconPosData WPFolder_wpStoreIconPosData
    #endif /* _wpStoreIconPosData */
#endif /* SOMGD_wpStoreIconPosData */

/*
 * New Method: wpQueryIconPosition
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpQueryIconPosition(WPFolder *somSelf, 
		PSZ pszIdentity, 
		PPOINTL pptl, 
		PULONG pIndex);
#pragma linkage(somTP_WPFolder_wpQueryIconPosition, system)
typedef somTP_WPFolder_wpQueryIconPosition *somTD_WPFolder_wpQueryIconPosition;
#define somMD_WPFolder_wpQueryIconPosition "::WPFolder::wpQueryIconPosition"
#define WPFolder_wpQueryIconPosition(somSelf,pszIdentity,pptl,pIndex) \
    (SOM_Resolve(somSelf, WPFolder, wpQueryIconPosition) \
	(somSelf,pszIdentity,pptl,pIndex))
#ifndef SOMGD_wpQueryIconPosition
    #if (defined(_wpQueryIconPosition) || defined(__wpQueryIconPosition))
        #undef _wpQueryIconPosition
        #undef __wpQueryIconPosition
        #define SOMGD_wpQueryIconPosition 1
    #else
        #define _wpQueryIconPosition WPFolder_wpQueryIconPosition
    #endif /* _wpQueryIconPosition */
#endif /* SOMGD_wpQueryIconPosition */

/*
 * New Method: wpSetFldrSort
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpSetFldrSort(WPFolder *somSelf, 
		PVOID pSortRecord, 
		ULONG ulView, 
		ULONG ulType);
#pragma linkage(somTP_WPFolder_wpSetFldrSort, system)
typedef somTP_WPFolder_wpSetFldrSort *somTD_WPFolder_wpSetFldrSort;
#define somMD_WPFolder_wpSetFldrSort "::WPFolder::wpSetFldrSort"
#define WPFolder_wpSetFldrSort(somSelf,pSortRecord,ulView,ulType) \
    (SOM_Resolve(somSelf, WPFolder, wpSetFldrSort) \
	(somSelf,pSortRecord,ulView,ulType))
#ifndef SOMGD_wpSetFldrSort
    #if (defined(_wpSetFldrSort) || defined(__wpSetFldrSort))
        #undef _wpSetFldrSort
        #undef __wpSetFldrSort
        #define SOMGD_wpSetFldrSort 1
    #else
        #define _wpSetFldrSort WPFolder_wpSetFldrSort
    #endif /* _wpSetFldrSort */
#endif /* SOMGD_wpSetFldrSort */

/*
 * New Method: wpQueryFldrSort
 */
typedef PVOID   SOMLINK somTP_WPFolder_wpQueryFldrSort(WPFolder *somSelf, 
		ULONG ulView, 
		ULONG ulType);
#pragma linkage(somTP_WPFolder_wpQueryFldrSort, system)
typedef somTP_WPFolder_wpQueryFldrSort *somTD_WPFolder_wpQueryFldrSort;
#define somMD_WPFolder_wpQueryFldrSort "::WPFolder::wpQueryFldrSort"
#define WPFolder_wpQueryFldrSort(somSelf,ulView,ulType) \
    (SOM_Resolve(somSelf, WPFolder, wpQueryFldrSort) \
	(somSelf,ulView,ulType))
#ifndef SOMGD_wpQueryFldrSort
    #if (defined(_wpQueryFldrSort) || defined(__wpQueryFldrSort))
        #undef _wpQueryFldrSort
        #undef __wpQueryFldrSort
        #define SOMGD_wpQueryFldrSort 1
    #else
        #define _wpQueryFldrSort WPFolder_wpQueryFldrSort
    #endif /* _wpQueryFldrSort */
#endif /* SOMGD_wpQueryFldrSort */

/*
 * New Method: wpRestoreFldrRunObjs
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpRestoreFldrRunObjs(WPFolder *somSelf);
#pragma linkage(somTP_WPFolder_wpRestoreFldrRunObjs, system)
typedef somTP_WPFolder_wpRestoreFldrRunObjs *somTD_WPFolder_wpRestoreFldrRunObjs;
#define somMD_WPFolder_wpRestoreFldrRunObjs "::WPFolder::wpRestoreFldrRunObjs"
#define WPFolder_wpRestoreFldrRunObjs(somSelf) \
    (SOM_Resolve(somSelf, WPFolder, wpRestoreFldrRunObjs) \
	(somSelf))
#ifndef SOMGD_wpRestoreFldrRunObjs
    #if (defined(_wpRestoreFldrRunObjs) || defined(__wpRestoreFldrRunObjs))
        #undef _wpRestoreFldrRunObjs
        #undef __wpRestoreFldrRunObjs
        #define SOMGD_wpRestoreFldrRunObjs 1
    #else
        #define _wpRestoreFldrRunObjs WPFolder_wpRestoreFldrRunObjs
    #endif /* _wpRestoreFldrRunObjs */
#endif /* SOMGD_wpRestoreFldrRunObjs */

/*
 * New Method: wpStoreFldrRunObjs
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpStoreFldrRunObjs(WPFolder *somSelf, 
		ULONG ulType);
#pragma linkage(somTP_WPFolder_wpStoreFldrRunObjs, system)
typedef somTP_WPFolder_wpStoreFldrRunObjs *somTD_WPFolder_wpStoreFldrRunObjs;
#define somMD_WPFolder_wpStoreFldrRunObjs "::WPFolder::wpStoreFldrRunObjs"
#define WPFolder_wpStoreFldrRunObjs(somSelf,ulType) \
    (SOM_Resolve(somSelf, WPFolder, wpStoreFldrRunObjs) \
	(somSelf,ulType))
#ifndef SOMGD_wpStoreFldrRunObjs
    #if (defined(_wpStoreFldrRunObjs) || defined(__wpStoreFldrRunObjs))
        #undef _wpStoreFldrRunObjs
        #undef __wpStoreFldrRunObjs
        #define SOMGD_wpStoreFldrRunObjs 1
    #else
        #define _wpStoreFldrRunObjs WPFolder_wpStoreFldrRunObjs
    #endif /* _wpStoreFldrRunObjs */
#endif /* SOMGD_wpStoreFldrRunObjs */

/*
 * New Method: wpHideFldrRunObjs
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpHideFldrRunObjs(WPFolder *somSelf, 
		BOOL fHide);
#pragma linkage(somTP_WPFolder_wpHideFldrRunObjs, system)
typedef somTP_WPFolder_wpHideFldrRunObjs *somTD_WPFolder_wpHideFldrRunObjs;
#define somMD_WPFolder_wpHideFldrRunObjs "::WPFolder::wpHideFldrRunObjs"
#define WPFolder_wpHideFldrRunObjs(somSelf,fHide) \
    (SOM_Resolve(somSelf, WPFolder, wpHideFldrRunObjs) \
	(somSelf,fHide))
#ifndef SOMGD_wpHideFldrRunObjs
    #if (defined(_wpHideFldrRunObjs) || defined(__wpHideFldrRunObjs))
        #undef _wpHideFldrRunObjs
        #undef __wpHideFldrRunObjs
        #define SOMGD_wpHideFldrRunObjs 1
    #else
        #define _wpHideFldrRunObjs WPFolder_wpHideFldrRunObjs
    #endif /* _wpHideFldrRunObjs */
#endif /* SOMGD_wpHideFldrRunObjs */

/*
 * New Method: wpDeleteContents
 */
typedef ULONG   SOMLINK somTP_WPFolder_wpDeleteContents(WPFolder *somSelf, 
		ULONG fConfirmations);
#pragma linkage(somTP_WPFolder_wpDeleteContents, system)
typedef somTP_WPFolder_wpDeleteContents *somTD_WPFolder_wpDeleteContents;
#define somMD_WPFolder_wpDeleteContents "::WPFolder::wpDeleteContents"
#define WPFolder_wpDeleteContents(somSelf,fConfirmations) \
    (SOM_Resolve(somSelf, WPFolder, wpDeleteContents) \
	(somSelf,fConfirmations))
#ifndef SOMGD_wpDeleteContents
    #if (defined(_wpDeleteContents) || defined(__wpDeleteContents))
        #undef _wpDeleteContents
        #undef __wpDeleteContents
        #define SOMGD_wpDeleteContents 1
    #else
        #define _wpDeleteContents WPFolder_wpDeleteContents
    #endif /* _wpDeleteContents */
#endif /* SOMGD_wpDeleteContents */

/*
 * New Method: wpSetFldrDetailsClass
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpSetFldrDetailsClass(WPFolder *somSelf, 
		M_WPObject* Class);
#pragma linkage(somTP_WPFolder_wpSetFldrDetailsClass, system)
typedef somTP_WPFolder_wpSetFldrDetailsClass *somTD_WPFolder_wpSetFldrDetailsClass;
#define somMD_WPFolder_wpSetFldrDetailsClass "::WPFolder::wpSetFldrDetailsClass"
#define WPFolder_wpSetFldrDetailsClass(somSelf,Class) \
    (SOM_Resolve(somSelf, WPFolder, wpSetFldrDetailsClass) \
	(somSelf,Class))
#ifndef SOMGD_wpSetFldrDetailsClass
    #if (defined(_wpSetFldrDetailsClass) || defined(__wpSetFldrDetailsClass))
        #undef _wpSetFldrDetailsClass
        #undef __wpSetFldrDetailsClass
        #define SOMGD_wpSetFldrDetailsClass 1
    #else
        #define _wpSetFldrDetailsClass WPFolder_wpSetFldrDetailsClass
    #endif /* _wpSetFldrDetailsClass */
#endif /* SOMGD_wpSetFldrDetailsClass */

/*
 * New Method: wpQueryFldrDetailsClass
 */
typedef M_WPObject*   SOMLINK somTP_WPFolder_wpQueryFldrDetailsClass(WPFolder *somSelf);
#pragma linkage(somTP_WPFolder_wpQueryFldrDetailsClass, system)
typedef somTP_WPFolder_wpQueryFldrDetailsClass *somTD_WPFolder_wpQueryFldrDetailsClass;
#define somMD_WPFolder_wpQueryFldrDetailsClass "::WPFolder::wpQueryFldrDetailsClass"
#define WPFolder_wpQueryFldrDetailsClass(somSelf) \
    (SOM_Resolve(somSelf, WPFolder, wpQueryFldrDetailsClass) \
	(somSelf))
#ifndef SOMGD_wpQueryFldrDetailsClass
    #if (defined(_wpQueryFldrDetailsClass) || defined(__wpQueryFldrDetailsClass))
        #undef _wpQueryFldrDetailsClass
        #undef __wpQueryFldrDetailsClass
        #define SOMGD_wpQueryFldrDetailsClass 1
    #else
        #define _wpQueryFldrDetailsClass WPFolder_wpQueryFldrDetailsClass
    #endif /* _wpQueryFldrDetailsClass */
#endif /* SOMGD_wpQueryFldrDetailsClass */

/*
 * New Method: wpSearchFolder
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpSearchFolder(WPFolder *somSelf, 
		PSZ pszName, 
		ULONG ulSearchType, 
		ULONG ulLen, 
		PSEARCH_INFO pInfo, 
		WPFolder* ResultFolder);
#pragma linkage(somTP_WPFolder_wpSearchFolder, system)
typedef somTP_WPFolder_wpSearchFolder *somTD_WPFolder_wpSearchFolder;
#define somMD_WPFolder_wpSearchFolder "::WPFolder::wpSearchFolder"
#define WPFolder_wpSearchFolder(somSelf,pszName,ulSearchType,ulLen,pInfo,ResultFolder) \
    (SOM_Resolve(somSelf, WPFolder, wpSearchFolder) \
	(somSelf,pszName,ulSearchType,ulLen,pInfo,ResultFolder))
#ifndef SOMGD_wpSearchFolder
    #if (defined(_wpSearchFolder) || defined(__wpSearchFolder))
        #undef _wpSearchFolder
        #undef __wpSearchFolder
        #define SOMGD_wpSearchFolder 1
    #else
        #define _wpSearchFolder WPFolder_wpSearchFolder
    #endif /* _wpSearchFolder */
#endif /* SOMGD_wpSearchFolder */

/*
 * New Method: wpContainsFolders
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpContainsFolders(WPFolder *somSelf, 
		BOOL* pfSubFolders);
#pragma linkage(somTP_WPFolder_wpContainsFolders, system)
typedef somTP_WPFolder_wpContainsFolders *somTD_WPFolder_wpContainsFolders;
#define somMD_WPFolder_wpContainsFolders "::WPFolder::wpContainsFolders"
#define WPFolder_wpContainsFolders(somSelf,pfSubFolders) \
    (SOM_Resolve(somSelf, WPFolder, wpContainsFolders) \
	(somSelf,pfSubFolders))
#ifndef SOMGD_wpContainsFolders
    #if (defined(_wpContainsFolders) || defined(__wpContainsFolders))
        #undef _wpContainsFolders
        #undef __wpContainsFolders
        #define SOMGD_wpContainsFolders 1
    #else
        #define _wpContainsFolders WPFolder_wpContainsFolders
    #endif /* _wpContainsFolders */
#endif /* SOMGD_wpContainsFolders */

/*
 * New Method: wpQueryOpenFolders
 */
typedef WPObject*   SOMLINK somTP_WPFolder_wpQueryOpenFolders(WPFolder *somSelf, 
		ULONG ulOption);
#pragma linkage(somTP_WPFolder_wpQueryOpenFolders, system)
typedef somTP_WPFolder_wpQueryOpenFolders *somTD_WPFolder_wpQueryOpenFolders;
#define somMD_WPFolder_wpQueryOpenFolders "::WPFolder::wpQueryOpenFolders"
#define WPFolder_wpQueryOpenFolders(somSelf,ulOption) \
    (SOM_Resolve(somSelf, WPFolder, wpQueryOpenFolders) \
	(somSelf,ulOption))
#ifndef SOMGD_wpQueryOpenFolders
    #if (defined(_wpQueryOpenFolders) || defined(__wpQueryOpenFolders))
        #undef _wpQueryOpenFolders
        #undef __wpQueryOpenFolders
        #define SOMGD_wpQueryOpenFolders 1
    #else
        #define _wpQueryOpenFolders WPFolder_wpQueryOpenFolders
    #endif /* _wpQueryOpenFolders */
#endif /* SOMGD_wpQueryOpenFolders */

/*
 * New Method: wpModifyFldrFlags
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpModifyFldrFlags(WPFolder *somSelf, 
		ULONG ulFlags, 
		ULONG ulFlagMask);
#pragma linkage(somTP_WPFolder_wpModifyFldrFlags, system)
typedef somTP_WPFolder_wpModifyFldrFlags *somTD_WPFolder_wpModifyFldrFlags;
#define somMD_WPFolder_wpModifyFldrFlags "::WPFolder::wpModifyFldrFlags"
#define WPFolder_wpModifyFldrFlags(somSelf,ulFlags,ulFlagMask) \
    (SOM_Resolve(somSelf, WPFolder, wpModifyFldrFlags) \
	(somSelf,ulFlags,ulFlagMask))
#ifndef SOMGD_wpModifyFldrFlags
    #if (defined(_wpModifyFldrFlags) || defined(__wpModifyFldrFlags))
        #undef _wpModifyFldrFlags
        #undef __wpModifyFldrFlags
        #define SOMGD_wpModifyFldrFlags 1
    #else
        #define _wpModifyFldrFlags WPFolder_wpModifyFldrFlags
    #endif /* _wpModifyFldrFlags */
#endif /* SOMGD_wpModifyFldrFlags */

/*
 * New Method: wpAddToContent
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpAddToContent(WPFolder *somSelf, 
		WPObject* Object);
#pragma linkage(somTP_WPFolder_wpAddToContent, system)
typedef somTP_WPFolder_wpAddToContent *somTD_WPFolder_wpAddToContent;
#define somMD_WPFolder_wpAddToContent "::WPFolder::wpAddToContent"
#define WPFolder_wpAddToContent(somSelf,Object) \
    (SOM_Resolve(somSelf, WPFolder, wpAddToContent) \
	(somSelf,Object))
#ifndef SOMGD_wpAddToContent
    #if (defined(_wpAddToContent) || defined(__wpAddToContent))
        #undef _wpAddToContent
        #undef __wpAddToContent
        #define SOMGD_wpAddToContent 1
    #else
        #define _wpAddToContent WPFolder_wpAddToContent
    #endif /* _wpAddToContent */
#endif /* SOMGD_wpAddToContent */

/*
 * New Method: wpDeleteFromContent
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpDeleteFromContent(WPFolder *somSelf, 
		WPObject* Object);
#pragma linkage(somTP_WPFolder_wpDeleteFromContent, system)
typedef somTP_WPFolder_wpDeleteFromContent *somTD_WPFolder_wpDeleteFromContent;
#define somMD_WPFolder_wpDeleteFromContent "::WPFolder::wpDeleteFromContent"
#define WPFolder_wpDeleteFromContent(somSelf,Object) \
    (SOM_Resolve(somSelf, WPFolder, wpDeleteFromContent) \
	(somSelf,Object))
#ifndef SOMGD_wpDeleteFromContent
    #if (defined(_wpDeleteFromContent) || defined(__wpDeleteFromContent))
        #undef _wpDeleteFromContent
        #undef __wpDeleteFromContent
        #define SOMGD_wpDeleteFromContent 1
    #else
        #define _wpDeleteFromContent WPFolder_wpDeleteFromContent
    #endif /* _wpDeleteFromContent */
#endif /* SOMGD_wpDeleteFromContent */

/*
 * New Method: wpSetDetailsColumnVisibility
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpSetDetailsColumnVisibility(WPFolder *somSelf, 
		ULONG index, 
		BOOL Visible);
#pragma linkage(somTP_WPFolder_wpSetDetailsColumnVisibility, system)
typedef somTP_WPFolder_wpSetDetailsColumnVisibility *somTD_WPFolder_wpSetDetailsColumnVisibility;
#define somMD_WPFolder_wpSetDetailsColumnVisibility "::WPFolder::wpSetDetailsColumnVisibility"
#define WPFolder_wpSetDetailsColumnVisibility(somSelf,index,Visible) \
    (SOM_Resolve(somSelf, WPFolder, wpSetDetailsColumnVisibility) \
	(somSelf,index,Visible))
#ifndef SOMGD_wpSetDetailsColumnVisibility
    #if (defined(_wpSetDetailsColumnVisibility) || defined(__wpSetDetailsColumnVisibility))
        #undef _wpSetDetailsColumnVisibility
        #undef __wpSetDetailsColumnVisibility
        #define SOMGD_wpSetDetailsColumnVisibility 1
    #else
        #define _wpSetDetailsColumnVisibility WPFolder_wpSetDetailsColumnVisibility
    #endif /* _wpSetDetailsColumnVisibility */
#endif /* SOMGD_wpSetDetailsColumnVisibility */

/*
 * New Method: wpIsDetailsColumnVisible
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpIsDetailsColumnVisible(WPFolder *somSelf, 
		ULONG index);
#pragma linkage(somTP_WPFolder_wpIsDetailsColumnVisible, system)
typedef somTP_WPFolder_wpIsDetailsColumnVisible *somTD_WPFolder_wpIsDetailsColumnVisible;
#define somMD_WPFolder_wpIsDetailsColumnVisible "::WPFolder::wpIsDetailsColumnVisible"
#define WPFolder_wpIsDetailsColumnVisible(somSelf,index) \
    (SOM_Resolve(somSelf, WPFolder, wpIsDetailsColumnVisible) \
	(somSelf,index))
#ifndef SOMGD_wpIsDetailsColumnVisible
    #if (defined(_wpIsDetailsColumnVisible) || defined(__wpIsDetailsColumnVisible))
        #undef _wpIsDetailsColumnVisible
        #undef __wpIsDetailsColumnVisible
        #define SOMGD_wpIsDetailsColumnVisible 1
    #else
        #define _wpIsDetailsColumnVisible WPFolder_wpIsDetailsColumnVisible
    #endif /* _wpIsDetailsColumnVisible */
#endif /* SOMGD_wpIsDetailsColumnVisible */

/*
 * New Method: wpSetFldrSortClass
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpSetFldrSortClass(WPFolder *somSelf, 
		M_WPObject* Class);
#pragma linkage(somTP_WPFolder_wpSetFldrSortClass, system)
typedef somTP_WPFolder_wpSetFldrSortClass *somTD_WPFolder_wpSetFldrSortClass;
#define somMD_WPFolder_wpSetFldrSortClass "::WPFolder::wpSetFldrSortClass"
#define WPFolder_wpSetFldrSortClass(somSelf,Class) \
    (SOM_Resolve(somSelf, WPFolder, wpSetFldrSortClass) \
	(somSelf,Class))
#ifndef SOMGD_wpSetFldrSortClass
    #if (defined(_wpSetFldrSortClass) || defined(__wpSetFldrSortClass))
        #undef _wpSetFldrSortClass
        #undef __wpSetFldrSortClass
        #define SOMGD_wpSetFldrSortClass 1
    #else
        #define _wpSetFldrSortClass WPFolder_wpSetFldrSortClass
    #endif /* _wpSetFldrSortClass */
#endif /* SOMGD_wpSetFldrSortClass */

/*
 * New Method: wpQueryFldrSortClass
 */
typedef M_WPObject*   SOMLINK somTP_WPFolder_wpQueryFldrSortClass(WPFolder *somSelf);
#pragma linkage(somTP_WPFolder_wpQueryFldrSortClass, system)
typedef somTP_WPFolder_wpQueryFldrSortClass *somTD_WPFolder_wpQueryFldrSortClass;
#define somMD_WPFolder_wpQueryFldrSortClass "::WPFolder::wpQueryFldrSortClass"
#define WPFolder_wpQueryFldrSortClass(somSelf) \
    (SOM_Resolve(somSelf, WPFolder, wpQueryFldrSortClass) \
	(somSelf))
#ifndef SOMGD_wpQueryFldrSortClass
    #if (defined(_wpQueryFldrSortClass) || defined(__wpQueryFldrSortClass))
        #undef _wpQueryFldrSortClass
        #undef __wpQueryFldrSortClass
        #define SOMGD_wpQueryFldrSortClass 1
    #else
        #define _wpQueryFldrSortClass WPFolder_wpQueryFldrSortClass
    #endif /* _wpQueryFldrSortClass */
#endif /* SOMGD_wpQueryFldrSortClass */

/*
 * New Method: wpSetSortAttribAvailable
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpSetSortAttribAvailable(WPFolder *somSelf, 
		ULONG index, 
		BOOL Available);
#pragma linkage(somTP_WPFolder_wpSetSortAttribAvailable, system)
typedef somTP_WPFolder_wpSetSortAttribAvailable *somTD_WPFolder_wpSetSortAttribAvailable;
#define somMD_WPFolder_wpSetSortAttribAvailable "::WPFolder::wpSetSortAttribAvailable"
#define WPFolder_wpSetSortAttribAvailable(somSelf,index,Available) \
    (SOM_Resolve(somSelf, WPFolder, wpSetSortAttribAvailable) \
	(somSelf,index,Available))
#ifndef SOMGD_wpSetSortAttribAvailable
    #if (defined(_wpSetSortAttribAvailable) || defined(__wpSetSortAttribAvailable))
        #undef _wpSetSortAttribAvailable
        #undef __wpSetSortAttribAvailable
        #define SOMGD_wpSetSortAttribAvailable 1
    #else
        #define _wpSetSortAttribAvailable WPFolder_wpSetSortAttribAvailable
    #endif /* _wpSetSortAttribAvailable */
#endif /* SOMGD_wpSetSortAttribAvailable */

/*
 * New Method: wpIsSortAttribAvailable
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpIsSortAttribAvailable(WPFolder *somSelf, 
		ULONG index);
#pragma linkage(somTP_WPFolder_wpIsSortAttribAvailable, system)
typedef somTP_WPFolder_wpIsSortAttribAvailable *somTD_WPFolder_wpIsSortAttribAvailable;
#define somMD_WPFolder_wpIsSortAttribAvailable "::WPFolder::wpIsSortAttribAvailable"
#define WPFolder_wpIsSortAttribAvailable(somSelf,index) \
    (SOM_Resolve(somSelf, WPFolder, wpIsSortAttribAvailable) \
	(somSelf,index))
#ifndef SOMGD_wpIsSortAttribAvailable
    #if (defined(_wpIsSortAttribAvailable) || defined(__wpIsSortAttribAvailable))
        #undef _wpIsSortAttribAvailable
        #undef __wpIsSortAttribAvailable
        #define SOMGD_wpIsSortAttribAvailable 1
    #else
        #define _wpIsSortAttribAvailable WPFolder_wpIsSortAttribAvailable
    #endif /* _wpIsSortAttribAvailable */
#endif /* SOMGD_wpIsSortAttribAvailable */

/*
 * New Method: wpQueryIconViewPos
 */
typedef char*   SOMLINK somTP_WPFolder_wpQueryIconViewPos(WPFolder *somSelf);
#pragma linkage(somTP_WPFolder_wpQueryIconViewPos, system)
typedef somTP_WPFolder_wpQueryIconViewPos *somTD_WPFolder_wpQueryIconViewPos;
#define somMD_WPFolder_wpQueryIconViewPos "::WPFolder::wpQueryIconViewPos"
#define WPFolder_wpQueryIconViewPos(somSelf) \
    (SOM_Resolve(somSelf, WPFolder, wpQueryIconViewPos) \
	(somSelf))
#ifndef SOMGD_wpQueryIconViewPos
    #if (defined(_wpQueryIconViewPos) || defined(__wpQueryIconViewPos))
        #undef _wpQueryIconViewPos
        #undef __wpQueryIconViewPos
        #define SOMGD_wpQueryIconViewPos 1
    #else
        #define _wpQueryIconViewPos WPFolder_wpQueryIconViewPos
    #endif /* _wpQueryIconViewPos */
#endif /* SOMGD_wpQueryIconViewPos */

/*
 * New Method: wpAddFirstChild
 */
typedef WPObject*   SOMLINK somTP_WPFolder_wpAddFirstChild(WPFolder *somSelf);
#pragma linkage(somTP_WPFolder_wpAddFirstChild, system)
typedef somTP_WPFolder_wpAddFirstChild *somTD_WPFolder_wpAddFirstChild;
#define somMD_WPFolder_wpAddFirstChild "::WPFolder::wpAddFirstChild"
#define WPFolder_wpAddFirstChild(somSelf) \
    (SOM_Resolve(somSelf, WPFolder, wpAddFirstChild) \
	(somSelf))
#ifndef SOMGD_wpAddFirstChild
    #if (defined(_wpAddFirstChild) || defined(__wpAddFirstChild))
        #undef _wpAddFirstChild
        #undef __wpAddFirstChild
        #define SOMGD_wpAddFirstChild 1
    #else
        #define _wpAddFirstChild WPFolder_wpAddFirstChild
    #endif /* _wpAddFirstChild */
#endif /* SOMGD_wpAddFirstChild */

/*
 * New Method: wpFlushNotifications
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpFlushNotifications(WPFolder *somSelf);
#pragma linkage(somTP_WPFolder_wpFlushNotifications, system)
typedef somTP_WPFolder_wpFlushNotifications *somTD_WPFolder_wpFlushNotifications;
#define somMD_WPFolder_wpFlushNotifications "::WPFolder::wpFlushNotifications"
#define WPFolder_wpFlushNotifications(somSelf) \
    (SOM_Resolve(somSelf, WPFolder, wpFlushNotifications) \
	(somSelf))
#ifndef SOMGD_wpFlushNotifications
    #if (defined(_wpFlushNotifications) || defined(__wpFlushNotifications))
        #undef _wpFlushNotifications
        #undef __wpFlushNotifications
        #define SOMGD_wpFlushNotifications 1
    #else
        #define _wpFlushNotifications WPFolder_wpFlushNotifications
    #endif /* _wpFlushNotifications */
#endif /* SOMGD_wpFlushNotifications */

/*
 * New Method: wpSetMenuBarVisibility
 */
typedef BOOL   SOMLINK somTP_WPFolder_wpSetMenuBarVisibility(WPFolder *somSelf, 
		ULONG ulVisibility);
#pragma linkage(somTP_WPFolder_wpSetMenuBarVisibility, system)
typedef somTP_WPFolder_wpSetMenuBarVisibility *somTD_WPFolder_wpSetMenuBarVisibility;
#define somMD_WPFolder_wpSetMenuBarVisibility "::WPFolder::wpSetMenuBarVisibility"
#define WPFolder_wpSetMenuBarVisibility(somSelf,ulVisibility) \
    (SOM_Resolve(somSelf, WPFolder, wpSetMenuBarVisibility) \
	(somSelf,ulVisibility))
#ifndef SOMGD_wpSetMenuBarVisibility
    #if (defined(_wpSetMenuBarVisibility) || defined(__wpSetMenuBarVisibility))
        #undef _wpSetMenuBarVisibility
        #undef __wpSetMenuBarVisibility
        #define SOMGD_wpSetMenuBarVisibility 1
    #else
        #define _wpSetMenuBarVisibility WPFolder_wpSetMenuBarVisibility
    #endif /* _wpSetMenuBarVisibility */
#endif /* SOMGD_wpSetMenuBarVisibility */

/*
 * New Method: wpQueryMenuBarVisibility
 */
typedef ULONG   SOMLINK somTP_WPFolder_wpQueryMenuBarVisibility(WPFolder *somSelf);
#pragma linkage(somTP_WPFolder_wpQueryMenuBarVisibility, system)
typedef somTP_WPFolder_wpQueryMenuBarVisibility *somTD_WPFolder_wpQueryMenuBarVisibility;
#define somMD_WPFolder_wpQueryMenuBarVisibility "::WPFolder::wpQueryMenuBarVisibility"
#define WPFolder_wpQueryMenuBarVisibility(somSelf) \
    (SOM_Resolve(somSelf, WPFolder, wpQueryMenuBarVisibility) \
	(somSelf))
#ifndef SOMGD_wpQueryMenuBarVisibility
    #if (defined(_wpQueryMenuBarVisibility) || defined(__wpQueryMenuBarVisibility))
        #undef _wpQueryMenuBarVisibility
        #undef __wpQueryMenuBarVisibility
        #define SOMGD_wpQueryMenuBarVisibility 1
    #else
        #define _wpQueryMenuBarVisibility WPFolder_wpQueryMenuBarVisibility
    #endif /* _wpQueryMenuBarVisibility */
#endif /* SOMGD_wpQueryMenuBarVisibility */

/*
 * New Method: wpQueryIconTextBackgroundColor
 */
typedef ULONG   SOMLINK somTP_WPFolder_wpQueryIconTextBackgroundColor(WPFolder *somSelf);
#pragma linkage(somTP_WPFolder_wpQueryIconTextBackgroundColor, system)
typedef somTP_WPFolder_wpQueryIconTextBackgroundColor *somTD_WPFolder_wpQueryIconTextBackgroundColor;
#define somMD_WPFolder_wpQueryIconTextBackgroundColor "::WPFolder::wpQueryIconTextBackgroundColor"
#define WPFolder_wpQueryIconTextBackgroundColor(somSelf) \
    (SOM_Resolve(somSelf, WPFolder, wpQueryIconTextBackgroundColor) \
	(somSelf))
#ifndef SOMGD_wpQueryIconTextBackgroundColor
    #if (defined(_wpQueryIconTextBackgroundColor) || defined(__wpQueryIconTextBackgroundColor))
        #undef _wpQueryIconTextBackgroundColor
        #undef __wpQueryIconTextBackgroundColor
        #define SOMGD_wpQueryIconTextBackgroundColor 1
    #else
        #define _wpQueryIconTextBackgroundColor WPFolder_wpQueryIconTextBackgroundColor
    #endif /* _wpQueryIconTextBackgroundColor */
#endif /* SOMGD_wpQueryIconTextBackgroundColor */

/*
 * New Method: wpSetIconTextBackgroundColor
 */
typedef void   SOMLINK somTP_WPFolder_wpSetIconTextBackgroundColor(WPFolder *somSelf, 
		ULONG ulColor, 
		BOOL fRefreshViews);
#pragma linkage(somTP_WPFolder_wpSetIconTextBackgroundColor, system)
typedef somTP_WPFolder_wpSetIconTextBackgroundColor *somTD_WPFolder_wpSetIconTextBackgroundColor;
#define somMD_WPFolder_wpSetIconTextBackgroundColor "::WPFolder::wpSetIconTextBackgroundColor"
#define WPFolder_wpSetIconTextBackgroundColor(somSelf,ulColor,fRefreshViews) \
    (SOM_Resolve(somSelf, WPFolder, wpSetIconTextBackgroundColor) \
	(somSelf,ulColor,fRefreshViews))
#ifndef SOMGD_wpSetIconTextBackgroundColor
    #if (defined(_wpSetIconTextBackgroundColor) || defined(__wpSetIconTextBackgroundColor))
        #undef _wpSetIconTextBackgroundColor
        #undef __wpSetIconTextBackgroundColor
        #define SOMGD_wpSetIconTextBackgroundColor 1
    #else
        #define _wpSetIconTextBackgroundColor WPFolder_wpSetIconTextBackgroundColor
    #endif /* _wpSetIconTextBackgroundColor */
#endif /* SOMGD_wpSetIconTextBackgroundColor */

/*
 * New Method: wpQueryIconTextColor
 */
typedef ULONG   SOMLINK somTP_WPFolder_wpQueryIconTextColor(WPFolder *somSelf, 
		ULONG ulView);
#pragma linkage(somTP_WPFolder_wpQueryIconTextColor, system)
typedef somTP_WPFolder_wpQueryIconTextColor *somTD_WPFolder_wpQueryIconTextColor;
#define somMD_WPFolder_wpQueryIconTextColor "::WPFolder::wpQueryIconTextColor"
#define WPFolder_wpQueryIconTextColor(somSelf,ulView) \
    (SOM_Resolve(somSelf, WPFolder, wpQueryIconTextColor) \
	(somSelf,ulView))
#ifndef SOMGD_wpQueryIconTextColor
    #if (defined(_wpQueryIconTextColor) || defined(__wpQueryIconTextColor))
        #undef _wpQueryIconTextColor
        #undef __wpQueryIconTextColor
        #define SOMGD_wpQueryIconTextColor 1
    #else
        #define _wpQueryIconTextColor WPFolder_wpQueryIconTextColor
    #endif /* _wpQueryIconTextColor */
#endif /* SOMGD_wpQueryIconTextColor */

/*
 * New Method: wpSetIconTextColor
 */
typedef void   SOMLINK somTP_WPFolder_wpSetIconTextColor(WPFolder *somSelf, 
		ULONG ulColor, 
		ULONG ulView, 
		BOOL fRefreshViews);
#pragma linkage(somTP_WPFolder_wpSetIconTextColor, system)
typedef somTP_WPFolder_wpSetIconTextColor *somTD_WPFolder_wpSetIconTextColor;
#define somMD_WPFolder_wpSetIconTextColor "::WPFolder::wpSetIconTextColor"
#define WPFolder_wpSetIconTextColor(somSelf,ulColor,ulView,fRefreshViews) \
    (SOM_Resolve(somSelf, WPFolder, wpSetIconTextColor) \
	(somSelf,ulColor,ulView,fRefreshViews))
#ifndef SOMGD_wpSetIconTextColor
    #if (defined(_wpSetIconTextColor) || defined(__wpSetIconTextColor))
        #undef _wpSetIconTextColor
        #undef __wpSetIconTextColor
        #define SOMGD_wpSetIconTextColor 1
    #else
        #define _wpSetIconTextColor WPFolder_wpSetIconTextColor
    #endif /* _wpSetIconTextColor */
#endif /* SOMGD_wpSetIconTextColor */

/*
 * New Method: wpQueryShadowTextColor
 */
typedef ULONG   SOMLINK somTP_WPFolder_wpQueryShadowTextColor(WPFolder *somSelf, 
		ULONG ulView);
#pragma linkage(somTP_WPFolder_wpQueryShadowTextColor, system)
typedef somTP_WPFolder_wpQueryShadowTextColor *somTD_WPFolder_wpQueryShadowTextColor;
#define somMD_WPFolder_wpQueryShadowTextColor "::WPFolder::wpQueryShadowTextColor"
#define WPFolder_wpQueryShadowTextColor(somSelf,ulView) \
    (SOM_Resolve(somSelf, WPFolder, wpQueryShadowTextColor) \
	(somSelf,ulView))
#ifndef SOMGD_wpQueryShadowTextColor
    #if (defined(_wpQueryShadowTextColor) || defined(__wpQueryShadowTextColor))
        #undef _wpQueryShadowTextColor
        #undef __wpQueryShadowTextColor
        #define SOMGD_wpQueryShadowTextColor 1
    #else
        #define _wpQueryShadowTextColor WPFolder_wpQueryShadowTextColor
    #endif /* _wpQueryShadowTextColor */
#endif /* SOMGD_wpQueryShadowTextColor */

/*
 * New Method: wpSetShadowTextColor
 */
typedef void   SOMLINK somTP_WPFolder_wpSetShadowTextColor(WPFolder *somSelf, 
		ULONG ulColor, 
		ULONG ulView, 
		BOOL fRefreshViews);
#pragma linkage(somTP_WPFolder_wpSetShadowTextColor, system)
typedef somTP_WPFolder_wpSetShadowTextColor *somTD_WPFolder_wpSetShadowTextColor;
#define somMD_WPFolder_wpSetShadowTextColor "::WPFolder::wpSetShadowTextColor"
#define WPFolder_wpSetShadowTextColor(somSelf,ulColor,ulView,fRefreshViews) \
    (SOM_Resolve(somSelf, WPFolder, wpSetShadowTextColor) \
	(somSelf,ulColor,ulView,fRefreshViews))
#ifndef SOMGD_wpSetShadowTextColor
    #if (defined(_wpSetShadowTextColor) || defined(__wpSetShadowTextColor))
        #undef _wpSetShadowTextColor
        #undef __wpSetShadowTextColor
        #define SOMGD_wpSetShadowTextColor 1
    #else
        #define _wpSetShadowTextColor WPFolder_wpSetShadowTextColor
    #endif /* _wpSetShadowTextColor */
#endif /* SOMGD_wpSetShadowTextColor */

/*
 * New Method: wpQueryIconTextVisibility
 */
typedef ULONG   SOMLINK somTP_WPFolder_wpQueryIconTextVisibility(WPFolder *somSelf, 
		ULONG ulView);
#pragma linkage(somTP_WPFolder_wpQueryIconTextVisibility, system)
typedef somTP_WPFolder_wpQueryIconTextVisibility *somTD_WPFolder_wpQueryIconTextVisibility;
#define somMD_WPFolder_wpQueryIconTextVisibility "::WPFolder::wpQueryIconTextVisibility"
#define WPFolder_wpQueryIconTextVisibility(somSelf,ulView) \
    (SOM_Resolve(somSelf, WPFolder, wpQueryIconTextVisibility) \
	(somSelf,ulView))
#ifndef SOMGD_wpQueryIconTextVisibility
    #if (defined(_wpQueryIconTextVisibility) || defined(__wpQueryIconTextVisibility))
        #undef _wpQueryIconTextVisibility
        #undef __wpQueryIconTextVisibility
        #define SOMGD_wpQueryIconTextVisibility 1
    #else
        #define _wpQueryIconTextVisibility WPFolder_wpQueryIconTextVisibility
    #endif /* _wpQueryIconTextVisibility */
#endif /* SOMGD_wpQueryIconTextVisibility */

/*
 * New Method: wpSetIconTextVisibility
 */
typedef void   SOMLINK somTP_WPFolder_wpSetIconTextVisibility(WPFolder *somSelf, 
		ULONG ulOption, 
		ULONG ulView, 
		BOOL fRefreshViews);
#pragma linkage(somTP_WPFolder_wpSetIconTextVisibility, system)
typedef somTP_WPFolder_wpSetIconTextVisibility *somTD_WPFolder_wpSetIconTextVisibility;
#define somMD_WPFolder_wpSetIconTextVisibility "::WPFolder::wpSetIconTextVisibility"
#define WPFolder_wpSetIconTextVisibility(somSelf,ulOption,ulView,fRefreshViews) \
    (SOM_Resolve(somSelf, WPFolder, wpSetIconTextVisibility) \
	(somSelf,ulOption,ulView,fRefreshViews))
#ifndef SOMGD_wpSetIconTextVisibility
    #if (defined(_wpSetIconTextVisibility) || defined(__wpSetIconTextVisibility))
        #undef _wpSetIconTextVisibility
        #undef __wpSetIconTextVisibility
        #define SOMGD_wpSetIconTextVisibility 1
    #else
        #define _wpSetIconTextVisibility WPFolder_wpSetIconTextVisibility
    #endif /* _wpSetIconTextVisibility */
#endif /* SOMGD_wpSetIconTextVisibility */

/*
 * New Method: wpQueryFldrBackground
 */
typedef void   SOMLINK somTP_WPFolder_wpQueryFldrBackground(WPFolder *somSelf, 
		PSZ* ppszImageFileName, 
		ULONG* pulImageMode, 
		ULONG* pulScaleFactor, 
		ULONG* pulBackgroundType, 
		long* plBackgroundColor);
#pragma linkage(somTP_WPFolder_wpQueryFldrBackground, system)
typedef somTP_WPFolder_wpQueryFldrBackground *somTD_WPFolder_wpQueryFldrBackground;
#define somMD_WPFolder_wpQueryFldrBackground "::WPFolder::wpQueryFldrBackground"
#define WPFolder_wpQueryFldrBackground(somSelf,ppszImageFileName,pulImageMode,pulScaleFactor,pulBackgroundType,plBackgroundColor) \
    (SOM_Resolve(somSelf, WPFolder, wpQueryFldrBackground) \
	(somSelf,ppszImageFileName,pulImageMode,pulScaleFactor,pulBackgroundType,plBackgroundColor))
#ifndef SOMGD_wpQueryFldrBackground
    #if (defined(_wpQueryFldrBackground) || defined(__wpQueryFldrBackground))
        #undef _wpQueryFldrBackground
        #undef __wpQueryFldrBackground
        #define SOMGD_wpQueryFldrBackground 1
    #else
        #define _wpQueryFldrBackground WPFolder_wpQueryFldrBackground
    #endif /* _wpQueryFldrBackground */
#endif /* SOMGD_wpQueryFldrBackground */

/*
 * New Method: wpSetFldrBackground
 */
typedef void   SOMLINK somTP_WPFolder_wpSetFldrBackground(WPFolder *somSelf, 
		PSZ pszImageFileName, 
		ULONG ulImageMode, 
		ULONG ulScaleFactor, 
		ULONG ulBackgroundType, 
		long lBackgroundColor);
#pragma linkage(somTP_WPFolder_wpSetFldrBackground, system)
typedef somTP_WPFolder_wpSetFldrBackground *somTD_WPFolder_wpSetFldrBackground;
#define somMD_WPFolder_wpSetFldrBackground "::WPFolder::wpSetFldrBackground"
#define WPFolder_wpSetFldrBackground(somSelf,pszImageFileName,ulImageMode,ulScaleFactor,ulBackgroundType,lBackgroundColor) \
    (SOM_Resolve(somSelf, WPFolder, wpSetFldrBackground) \
	(somSelf,pszImageFileName,ulImageMode,ulScaleFactor,ulBackgroundType,lBackgroundColor))
#ifndef SOMGD_wpSetFldrBackground
    #if (defined(_wpSetFldrBackground) || defined(__wpSetFldrBackground))
        #undef _wpSetFldrBackground
        #undef __wpSetFldrBackground
        #define SOMGD_wpSetFldrBackground 1
    #else
        #define _wpSetFldrBackground WPFolder_wpSetFldrBackground
    #endif /* _wpSetFldrBackground */
#endif /* SOMGD_wpSetFldrBackground */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define WPFolder_wpSetRealName WPFileSystem_wpSetRealName
#define WPFolder_wpSetType WPFileSystem_wpSetType
#define WPFolder_wpQueryType WPFileSystem_wpQueryType
#define WPFolder_wpSetAttr WPFileSystem_wpSetAttr
#define WPFolder_wpQueryAttr WPFileSystem_wpQueryAttr
#define WPFolder_wpAddFile1Page WPFileSystem_wpAddFile1Page
#define WPFolder_wpQueryCreation WPFileSystem_wpQueryCreation
#define WPFolder_wpQueryLastAccess WPFileSystem_wpQueryLastAccess
#define WPFolder_wpQueryLastWrite WPFileSystem_wpQueryLastWrite
#define WPFolder_wpQueryFileSize WPFileSystem_wpQueryFileSize
#define WPFolder_wpQueryEASize WPFileSystem_wpQueryEASize
#define WPFolder_wpSetDateInfo WPFileSystem_wpSetDateInfo
#define WPFolder_wpSetFileSizeInfo WPFileSystem_wpSetFileSizeInfo
#define WPFolder_wpQueryRefreshFlags WPFileSystem_wpQueryRefreshFlags
#define WPFolder_wpSetRefreshFlags WPFileSystem_wpSetRefreshFlags
#define WPFolder_wpPrintPlainTextFile WPFileSystem_wpPrintPlainTextFile
#define WPFolder_wpSetTitleAndRenameFile WPFileSystem_wpSetTitleAndRenameFile
#define WPFolder_wpConfirmRenameFileWithExt WPFileSystem_wpConfirmRenameFileWithExt
#define WPFolder_wpVerifyUpdateAccess WPFileSystem_wpVerifyUpdateAccess
#define WPFolder_wpQueryEASupport WPFileSystem_wpQueryEASupport
#define WPFolder_wpAddUserItemsToPopupMenu WPFileSystem_wpAddUserItemsToPopupMenu
#define WPFolder_wpIsDiskSwapped WPFileSystem_wpIsDiskSwapped
#define WPFolder_wpQueryRealName WPFileSystem_wpQueryRealName
#define WPFolder_wpQueryFilename WPFileSystem_wpQueryFilename
#define WPFolder_wpQueryDisk WPFileSystem_wpQueryDisk
#define WPFolder_wpQueryDateInfo WPFileSystem_wpQueryDateInfo
#define WPFolder_wpConfirmKeepAssoc WPFileSystem_wpConfirmKeepAssoc
#define WPFolder_wpQueryFileSizeL WPFileSystem_wpQueryFileSizeL
#define WPFolder_wpSetFileSizeL WPFileSystem_wpSetFileSizeL
#define WPFolder_wpQueryHandle WPObject_wpQueryHandle
#define WPFolder_wpSaveImmediate WPObject_wpSaveImmediate
#define WPFolder_wpSetTitle WPObject_wpSetTitle
#define WPFolder_wpViewObject WPObject_wpViewObject
#define WPFolder_wpSwitchTo WPObject_wpSwitchTo
#define WPFolder_wpCopyObject WPObject_wpCopyObject
#define WPFolder_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define WPFolder_wpQueryIcon WPObject_wpQueryIcon
#define WPFolder_wpQueryIconData WPObject_wpQueryIconData
#define WPFolder_wpQueryDetailsData WPObject_wpQueryDetailsData
#define WPFolder_wpDraggedOverObject WPObject_wpDraggedOverObject
#define WPFolder_wpDroppedOnObject WPObject_wpDroppedOnObject
#define WPFolder_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define WPFolder_wpAppendObject WPObject_wpAppendObject
#define WPFolder_wpReplaceObject WPObject_wpReplaceObject
#define WPFolder_wpQueryStyle WPObject_wpQueryStyle
#define WPFolder_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define WPFolder_wpIdentify WPObject_wpIdentify
#define WPFolder_wpIsDeleteable WPObject_wpIsDeleteable
#define WPFolder_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define WPFolder_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define WPFolder_wpAddToObjUseList WPObject_wpAddToObjUseList
#define WPFolder_wpAllocMem WPObject_wpAllocMem
#define WPFolder_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define WPFolder_wpClose WPObject_wpClose
#define WPFolder_wpCnrInsertObject WPObject_wpCnrInsertObject
#define WPFolder_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define WPFolder_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define WPFolder_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define WPFolder_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define WPFolder_wpCreateAnother WPObject_wpCreateAnother
#define WPFolder_wpCreateShadowObject WPObject_wpCreateShadowObject
#define WPFolder_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define WPFolder_wpDisplayHelp WPObject_wpDisplayHelp
#define WPFolder_wpEndConversation WPObject_wpEndConversation
#define WPFolder_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define WPFolder_wpFindUseItem WPObject_wpFindUseItem
#define WPFolder_wpFreeMem WPObject_wpFreeMem
#define WPFolder_wpHide WPObject_wpHide
#define WPFolder_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define WPFolder_wpInsertMenuItems WPObject_wpInsertMenuItems
#define WPFolder_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define WPFolder_wpModifyPopupMenu WPObject_wpModifyPopupMenu
#define WPFolder_wpPrintObject WPObject_wpPrintObject
#define WPFolder_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define WPFolder_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define WPFolder_wpQueryConfirmations WPObject_wpQueryConfirmations
#define WPFolder_wpQueryError WPObject_wpQueryError
#define WPFolder_wpSetFolder WPObject_wpSetFolder
#define WPFolder_wpQueryFolder WPObject_wpQueryFolder
#define WPFolder_wpQueryMinWindow WPObject_wpQueryMinWindow
#define WPFolder_wpSetTaskRec WPObject_wpSetTaskRec
#define WPFolder_wpFindTaskRec WPObject_wpFindTaskRec
#define WPFolder_wpQueryTitle WPObject_wpQueryTitle
#define WPFolder_wpRegisterView WPObject_wpRegisterView
#define WPFolder_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define WPFolder_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define WPFolder_wpRestore WPObject_wpRestore
#define WPFolder_wpRestoreData WPObject_wpRestoreData
#define WPFolder_wpRestoreLong WPObject_wpRestoreLong
#define WPFolder_wpRestoreString WPObject_wpRestoreString
#define WPFolder_wpSaveData WPObject_wpSaveData
#define WPFolder_wpSaveDeferred WPObject_wpSaveDeferred
#define WPFolder_wpSaveLong WPObject_wpSaveLong
#define WPFolder_wpSaveString WPObject_wpSaveString
#define WPFolder_wpScanSetupString WPObject_wpScanSetupString
#define WPFolder_wpSetConcurrentView WPObject_wpSetConcurrentView
#define WPFolder_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define WPFolder_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define WPFolder_wpSetDefaultView WPObject_wpSetDefaultView
#define WPFolder_wpSetError WPObject_wpSetError
#define WPFolder_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define WPFolder_wpSetupOnce WPObject_wpSetupOnce
#define WPFolder_wpSetIcon WPObject_wpSetIcon
#define WPFolder_wpSetMinWindow WPObject_wpSetMinWindow
#define WPFolder_wpModifyStyle WPObject_wpModifyStyle
#define WPFolder_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define WPFolder_wpUnlockObject WPObject_wpUnlockObject
#define WPFolder_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define WPFolder_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define WPFolder_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define WPFolder_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define WPFolder_wpSetObjectID WPObject_wpSetObjectID
#define WPFolder_wpQueryObjectID WPObject_wpQueryObjectID
#define WPFolder_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define WPFolder_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define WPFolder_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define WPFolder_wpFindViewItem WPObject_wpFindViewItem
#define WPFolder_wpLockObject WPObject_wpLockObject
#define WPFolder_wpIsLocked WPObject_wpIsLocked
#define WPFolder_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define WPFolder_wpWaitForClose WPObject_wpWaitForClose
#define WPFolder_wpSetMenuStyle WPObject_wpSetMenuStyle
#define WPFolder_wpQueryMenuStyle WPObject_wpQueryMenuStyle
#define WPFolder_wpSetStyle WPObject_wpSetStyle
#define WPFolder_somInit SOMObject_somInit
#define WPFolder_somUninit SOMObject_somUninit
#define WPFolder_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define WPFolder_somDefaultAssign SOMObject_somDefaultAssign
#define WPFolder_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define WPFolder_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define WPFolder_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define WPFolder_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define WPFolder_somDefaultVAssign SOMObject_somDefaultVAssign
#define WPFolder_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define WPFolder_somFree SOMObject_somFree
#define WPFolder_somGetClass SOMObject_somGetClass
#define WPFolder_somGetClassName SOMObject_somGetClassName
#define WPFolder_somGetSize SOMObject_somGetSize
#define WPFolder_somIsA SOMObject_somIsA
#define WPFolder_somIsInstanceOf SOMObject_somIsInstanceOf
#define WPFolder_somRespondsTo SOMObject_somRespondsTo
#define WPFolder_somDispatch SOMObject_somDispatch
#define WPFolder_somClassDispatch SOMObject_somClassDispatch
#define WPFolder_somCastObj SOMObject_somCastObj
#define WPFolder_somResetObj SOMObject_somResetObj
#define WPFolder_somDispatchV SOMObject_somDispatchV
#define WPFolder_somDispatchL SOMObject_somDispatchL
#define WPFolder_somDispatchA SOMObject_somDispatchA
#define WPFolder_somDispatchD SOMObject_somDispatchD
#define WPFolder_somPrintSelf SOMObject_somPrintSelf
#define WPFolder_somDumpSelf SOMObject_somDumpSelf
#define WPFolder_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_WPFolder_h */

#ifndef SOM_M_WPFolder_h
#define SOM_M_WPFolder_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_WPFolder
#define M_WPFolder SOMObject
#endif
#include <wpfsys.h>

/*
 * Start of bindings for IDL types
 */


/*
 * End of bindings for IDL types.
 */

#define M_WPFolder_MajorVersion 1
#define M_WPFolder_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_WPFolderNewClass wpfdrc
#pragma linkage(wpfdrc, system)
#define M_WPFolderClassData wpfdrd
#define M_WPFolderCClassData wpfdrx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_WPFolder_classObj M_WPFolderClassData.classObject
#define _M_WPFolder M_WPFolder_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_WPFolderNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_WPFolderNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_WPFolderClassDataStructure {
	SOMClass *classObject;
	somMToken wpclsFolderPrivate1;
	somMToken wpclsFolderPrivate2;
	somMToken wpclsQueryOpenFolders;
	somMToken wpclsFolderPrivate3;
	somMToken wpclsQueryIconDataN;
	somMToken wpclsQueryIconN;
} SOMDLINK M_WPFolderClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_WPFolderCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_WPFolderCClassData;

/*
 * New and Renew macros for M_WPFolder
 */
#define M_WPFolderNew() \
   ( _M_WPFolder ? \
	_somNew(_M_WPFolder) \
	: ( M_WPFolderNewClass(\
		M_WPFolder_MajorVersion, \
		M_WPFolder_MinorVersion),\
	   _somNew(_M_WPFolder)))
#define M_WPFolderRenew(buf) \
   ( _M_WPFolder ? \
	_somRenew(_M_WPFolder, buf) \
	: ( M_WPFolderNewClass(\
		M_WPFolder_MajorVersion, \
		M_WPFolder_MinorVersion),\
	   _somRenew(_M_WPFolder, buf)))

/*
 * Override method: wpclsInitData
 */
#define M_WPFolder_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsQueryDefaultView
 */
#define M_WPFolder_wpclsQueryDefaultView(somSelf) \
	M_WPObject_wpclsQueryDefaultView(somSelf)

/*
 * Override method: wpclsQueryTitle
 */
#define M_WPFolder_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)

/*
 * Override method: wpclsQueryIconData
 */
#define M_WPFolder_wpclsQueryIconData(somSelf,pIconInfo) \
	M_WPObject_wpclsQueryIconData(somSelf,pIconInfo)

/*
 * Override method: wpclsQueryStyle
 */
#define M_WPFolder_wpclsQueryStyle(somSelf) \
	M_WPObject_wpclsQueryStyle(somSelf)

/*
 * Override method: wpclsQueryDefaultHelp
 */
#define M_WPFolder_wpclsQueryDefaultHelp(somSelf,pHelpPanelId,pszHelpLibrary) \
	M_WPObject_wpclsQueryDefaultHelp(somSelf,pHelpPanelId,pszHelpLibrary)

/*
 * Override method: wpclsQuerySettingsPageSize
 */
#define M_WPFolder_wpclsQuerySettingsPageSize(somSelf,pSizl) \
	M_WPObject_wpclsQuerySettingsPageSize(somSelf,pSizl)

/*
 * New Method: wpclsQueryIconDataN
 */
typedef ULONG   SOMLINK somTP_M_WPFolder_wpclsQueryIconDataN(M_WPFolder *somSelf, 
		ICONINFO* pIconInfo, 
		ULONG ulIconIndex);
#pragma linkage(somTP_M_WPFolder_wpclsQueryIconDataN, system)
typedef somTP_M_WPFolder_wpclsQueryIconDataN *somTD_M_WPFolder_wpclsQueryIconDataN;
#define somMD_M_WPFolder_wpclsQueryIconDataN "::M_WPFolder::wpclsQueryIconDataN"
#define M_WPFolder_wpclsQueryIconDataN(somSelf,pIconInfo,ulIconIndex) \
    (SOM_Resolve(somSelf, M_WPFolder, wpclsQueryIconDataN) \
	(somSelf,pIconInfo,ulIconIndex))
#ifndef SOMGD_wpclsQueryIconDataN
    #if (defined(_wpclsQueryIconDataN) || defined(__wpclsQueryIconDataN))
        #undef _wpclsQueryIconDataN
        #undef __wpclsQueryIconDataN
        #define SOMGD_wpclsQueryIconDataN 1
    #else
        #define _wpclsQueryIconDataN M_WPFolder_wpclsQueryIconDataN
    #endif /* _wpclsQueryIconDataN */
#endif /* SOMGD_wpclsQueryIconDataN */

/*
 * New Method: wpclsQueryIconN
 */
typedef HPOINTER   SOMLINK somTP_M_WPFolder_wpclsQueryIconN(M_WPFolder *somSelf, 
		ULONG ulIconIndex);
#pragma linkage(somTP_M_WPFolder_wpclsQueryIconN, system)
typedef somTP_M_WPFolder_wpclsQueryIconN *somTD_M_WPFolder_wpclsQueryIconN;
#define somMD_M_WPFolder_wpclsQueryIconN "::M_WPFolder::wpclsQueryIconN"
#define M_WPFolder_wpclsQueryIconN(somSelf,ulIconIndex) \
    (SOM_Resolve(somSelf, M_WPFolder, wpclsQueryIconN) \
	(somSelf,ulIconIndex))
#ifndef SOMGD_wpclsQueryIconN
    #if (defined(_wpclsQueryIconN) || defined(__wpclsQueryIconN))
        #undef _wpclsQueryIconN
        #undef __wpclsQueryIconN
        #define SOMGD_wpclsQueryIconN 1
    #else
        #define _wpclsQueryIconN M_WPFolder_wpclsQueryIconN
    #endif /* _wpclsQueryIconN */
#endif /* SOMGD_wpclsQueryIconN */

/*
 * New Method: wpclsQueryOpenFolders
 */
typedef WPFolder*   SOMLINK somTP_M_WPFolder_wpclsQueryOpenFolders(M_WPFolder *somSelf, 
		WPFolder* Folder, 
		ULONG ulOption, 
		BOOL fLock);
#pragma linkage(somTP_M_WPFolder_wpclsQueryOpenFolders, system)
typedef somTP_M_WPFolder_wpclsQueryOpenFolders *somTD_M_WPFolder_wpclsQueryOpenFolders;
#define somMD_M_WPFolder_wpclsQueryOpenFolders "::M_WPFolder::wpclsQueryOpenFolders"
#define M_WPFolder_wpclsQueryOpenFolders(somSelf,Folder,ulOption,fLock) \
    (SOM_Resolve(somSelf, M_WPFolder, wpclsQueryOpenFolders) \
	(somSelf,Folder,ulOption,fLock))
#ifndef SOMGD_wpclsQueryOpenFolders
    #if (defined(_wpclsQueryOpenFolders) || defined(__wpclsQueryOpenFolders))
        #undef _wpclsQueryOpenFolders
        #undef __wpclsQueryOpenFolders
        #define SOMGD_wpclsQueryOpenFolders 1
    #else
        #define _wpclsQueryOpenFolders M_WPFolder_wpclsQueryOpenFolders
    #endif /* _wpclsQueryOpenFolders */
#endif /* SOMGD_wpclsQueryOpenFolders */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_WPFolder_wpclsQueryAwakeObject M_WPFileSystem_wpclsQueryAwakeObject
#define M_WPFolder_wpclsFileSysExists M_WPFileSystem_wpclsFileSysExists
#define M_WPFolder_wpclsQueryObjectFromPath M_WPFileSystem_wpclsQueryObjectFromPath
#define M_WPFolder_wpclsQueryInstanceType M_WPFileSystem_wpclsQueryInstanceType
#define M_WPFolder_wpclsQueryInstanceFilter M_WPFileSystem_wpclsQueryInstanceFilter
#define M_WPFolder_wpclsQueryInstanceClass M_WPFileSystem_wpclsQueryInstanceClass
#define M_WPFolder_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_WPFolder_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_WPFolder_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_WPFolder_wpclsNew M_WPObject_wpclsNew
#define M_WPFolder_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_WPFolder_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_WPFolder_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_WPFolder_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_WPFolder_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_WPFolder_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_WPFolder_wpclsUnInitData M_WPObject_wpclsUnInitData
#define M_WPFolder_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_WPFolder_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_WPFolder_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_WPFolder_wpclsSetError M_WPObject_wpclsSetError
#define M_WPFolder_wpclsQueryError M_WPObject_wpclsQueryError
#define M_WPFolder_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_WPFolder_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_WPFolder_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_WPFolder_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_WPFolder_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_WPFolder_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_WPFolder_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_WPFolder_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_WPFolder_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_WPFolder_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_WPFolder_somUninit SOMObject_somUninit
#define M_WPFolder_somClassReady SOMClass_somClassReady
#define M_WPFolder_somNew SOMClass_somNew
#define M_WPFolder_somRenew SOMClass_somRenew
#define M_WPFolder__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_WPFolder__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_WPFolder__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_WPFolder__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_WPFolder_somNewNoInit SOMClass_somNewNoInit
#define M_WPFolder_somRenewNoInit SOMClass_somRenewNoInit
#define M_WPFolder_somRenewNoZero SOMClass_somRenewNoZero
#define M_WPFolder_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_WPFolder_somAllocate SOMClass_somAllocate
#define M_WPFolder_somDeallocate SOMClass_somDeallocate
#define M_WPFolder__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_WPFolder__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_WPFolder_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_WPFolder_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_WPFolder_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_WPFolder_somInitClass SOMClass_somInitClass
#define M_WPFolder_somInitMIClass SOMClass_somInitMIClass
#define M_WPFolder_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_WPFolder_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_WPFolder_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_WPFolder_somGetApplyStub SOMClass_somGetApplyStub
#define M_WPFolder_somGetClassData SOMClass_somGetClassData
#define M_WPFolder_somSetClassData SOMClass_somSetClassData
#define M_WPFolder_somGetClassMtab SOMClass_somGetClassMtab
#define M_WPFolder_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_WPFolder_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_WPFolder_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_WPFolder_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_WPFolder_somGetMemberToken SOMClass_somGetMemberToken
#define M_WPFolder_somGetMethodData SOMClass_somGetMethodData
#define M_WPFolder_somGetRdStub SOMClass_somGetRdStub
#define M_WPFolder_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_WPFolder_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_WPFolder_somGetMethodToken SOMClass_somGetMethodToken
#define M_WPFolder_somGetName SOMClass_somGetName
#define M_WPFolder_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_WPFolder_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_WPFolder_somGetNumMethods SOMClass_somGetNumMethods
#define M_WPFolder_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_WPFolder_somGetParent SOMClass_somGetParent
#define M_WPFolder_somGetParents SOMClass_somGetParents
#define M_WPFolder_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_WPFolder_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_WPFolder_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_WPFolder_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_WPFolder_somFindMethod SOMClass_somFindMethod
#define M_WPFolder_somFindMethodOk SOMClass_somFindMethodOk
#define M_WPFolder_somFindSMethod SOMClass_somFindSMethod
#define M_WPFolder_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_WPFolder_somLookupMethod SOMClass_somLookupMethod
#define M_WPFolder_somCheckVersion SOMClass_somCheckVersion
#define M_WPFolder_somDescendedFrom SOMClass_somDescendedFrom
#define M_WPFolder_somSupportsMethod SOMClass_somSupportsMethod
#define M_WPFolder_somDefinedMethod SOMClass_somDefinedMethod
#define M_WPFolder_somOverrideMtab SOMClass_somOverrideMtab
#define M_WPFolder_somDefaultInit SOMObject_somDefaultInit
#define M_WPFolder_somDestruct SOMObject_somDestruct
#define M_WPFolder_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_WPFolder_somDefaultAssign SOMObject_somDefaultAssign
#define M_WPFolder_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_WPFolder_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_WPFolder_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_WPFolder_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_WPFolder_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_WPFolder_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_WPFolder_somInit SOMObject_somInit
#define M_WPFolder_somFree SOMObject_somFree
#define M_WPFolder_somGetClass SOMObject_somGetClass
#define M_WPFolder_somGetClassName SOMObject_somGetClassName
#define M_WPFolder_somGetSize SOMObject_somGetSize
#define M_WPFolder_somIsA SOMObject_somIsA
#define M_WPFolder_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_WPFolder_somRespondsTo SOMObject_somRespondsTo
#define M_WPFolder_somDispatch SOMObject_somDispatch
#define M_WPFolder_somClassDispatch SOMObject_somClassDispatch
#define M_WPFolder_somCastObj SOMObject_somCastObj
#define M_WPFolder_somResetObj SOMObject_somResetObj
#define M_WPFolder_somDispatchV SOMObject_somDispatchV
#define M_WPFolder_somDispatchL SOMObject_somDispatchL
#define M_WPFolder_somDispatchA SOMObject_somDispatchA
#define M_WPFolder_somDispatchD SOMObject_somDispatchD
#define M_WPFolder_somPrintSelf SOMObject_somPrintSelf
#define M_WPFolder_somDumpSelf SOMObject_somDumpSelf
#define M_WPFolder_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_WPFolder_h */
