
/*
 * This file was generated by the SOM Compiler.
 * FileName: G:\cwpsh\rel\os2c\include\base\os2\wppdr.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.14
 *     SOM Emitter emith: 2.43
 */

/*
 *   Module Header
 * 
 *   Module Name: WPPDR
 * 
 *   OS/2 Presentation Manager Workplace class definitions
 * 
 *   Copyright (c) International Business Machines Corporation 1991, 1992
 * 
 */


#ifndef SOM_WPPdr_h
#define SOM_WPPdr_h


#include <som.h>

/*
 * -- This emitter normally treats Method Tokens as Thunks,
 * -- but the sc modifier "nothunks" was used, so somResolve will be called.
 */
#undef somresolve_
#define somresolve_(obj,mToken) (somResolve(obj,mToken))

/*
 * Define the class name as an object type
 */
#ifndef WPPdr
#define WPPdr SOMObject
#endif
#include <wptrans.h>

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef WPImageFile
    #define WPImageFile SOMObject
#endif /* WPImageFile */
#ifndef M_WPTransient
    #define M_WPTransient SOMObject
#endif /* M_WPTransient */
#ifndef M_WPPdr
    #define M_WPPdr SOMObject
#endif /* M_WPPdr */

/*
 * End of bindings for IDL types.
 */

#define WPPdr_MajorVersion 1
#define WPPdr_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define WPPdrNewClass WPpdrc
#define WPPdrClassData WPpdrd
#define WPPdrCClassData WPpdrx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include <wppdr.h>
/*--------------Migration------------*/
#define WPPdr_classObj WPPdrClassData.classObject
#define _WPPdr WPPdr_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK WPPdrNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);

/*
 * Declare the class data structure
 */
SOMEXTERN struct WPPdrClassDataStructure {
	SOMClass *classObject;
	somMToken prtGetPDriverInfo;
	somMToken prtSetPDriverInfo;
	somMToken prtGetPDriverName;
	somMToken prtGetPDeviceName;
	somMToken prtSetPdrIcon;
	somMToken prtSetPDriverDiscardhwndDlg;
	somMToken prtSetPDriverInstallhwndDlg;
	somMToken prtGetDriverFilename;
	somMToken prtSetPdrState;
	somMToken prtGetPdrState;
} SOMDLINK WPPdrClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct WPPdrCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK WPPdrCClassData;

/*
 * New and Renew macros for WPPdr
 */
#define WPPdrNew() \
   ( _WPPdr ? \
	_somNew(_WPPdr) \
	: ( WPPdrNewClass(\
		WPPdr_MajorVersion, \
		WPPdr_MinorVersion),\
	   _somNew(_WPPdr)))
#define WPPdrRenew(buf) \
   ( _WPPdr ? \
	_somRenew(_WPPdr, buf) \
	: ( WPPdrNewClass(\
		WPPdr_MajorVersion, \
		WPPdr_MinorVersion),\
	   _somRenew(_WPPdr, buf)))

/*
 * Override method: wpInitData
 */
#define WPPdr_wpInitData(somSelf) \
	WPObject_wpInitData(somSelf)

/*
 * Override method: wpUnInitData
 */
#define WPPdr_wpUnInitData(somSelf) \
	WPObject_wpUnInitData(somSelf)

/*
 * Override method: somDumpSelfInt
 */
#define WPPdr_somDumpSelfInt(somSelf,level) \
	SOMObject_somDumpSelfInt(somSelf,level)

/*
 * Override method: wpSetup
 */
#define WPPdr_wpSetup(somSelf,pszSetupString) \
	WPObject_wpSetup(somSelf,pszSetupString)

/*
 * Override method: wpAddSettingsPages
 */
#define WPPdr_wpAddSettingsPages(somSelf,hwndNotebook) \
	WPObject_wpAddSettingsPages(somSelf,hwndNotebook)

/*
 * Override method: wpQueryTitle
 */
#define WPPdr_wpQueryTitle(somSelf) \
	WPObject_wpQueryTitle(somSelf)

/*
 * Override method: wpQueryIcon
 */
#define WPPdr_wpQueryIcon(somSelf) \
	WPObject_wpQueryIcon(somSelf)

/*
 * Override method: wpFilterPopupMenu
 */
#define WPPdr_wpFilterPopupMenu(somSelf,ulFlags,hwndCnr,fMultiSelect) \
	WPObject_wpFilterPopupMenu(somSelf,ulFlags,hwndCnr,fMultiSelect)

/*
 * Override method: wpFree
 */
#define WPPdr_wpFree(somSelf) \
	WPObject_wpFree(somSelf)

/*
 * Override method: wpConfirmDelete
 */
#define WPPdr_wpConfirmDelete(somSelf,fConfirmations) \
	WPObject_wpConfirmDelete(somSelf,fConfirmations)

/*
 * Override method: wpModifyPopupMenu
 */
#define WPPdr_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition) \
	WPObject_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition)

/*
 * Override method: wpMenuItemSelected
 */
#define WPPdr_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)

/*
 * Override method: wpMenuItemHelpSelected
 */
#define WPPdr_wpMenuItemHelpSelected(somSelf,MenuId) \
	WPObject_wpMenuItemHelpSelected(somSelf,MenuId)

/*
 * Override method: wpOpen
 */
#define WPPdr_wpOpen(somSelf,hwndCnr,ulView,param) \
	WPObject_wpOpen(somSelf,hwndCnr,ulView,param)

/*
 * Override method: wpDrop
 */
#define WPPdr_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem) \
	WPObject_wpDrop(somSelf,hwndCnr,pdrgInfo,pdrgItem)

/*
 * Override method: wpDragOver
 */
#define WPPdr_wpDragOver(somSelf,hwndCnr,pdrgInfo) \
	WPObject_wpDragOver(somSelf,hwndCnr,pdrgInfo)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define WPPdr_wpQueryHandle WPObject_wpQueryHandle
#define WPPdr_wpCopyObject WPObject_wpCopyObject
#define WPPdr_somDefaultInit SOMObject_somDefaultInit
#define WPPdr_somDestruct SOMObject_somDestruct
#define WPPdr_wpSaveImmediate WPObject_wpSaveImmediate
#define WPPdr_wpIdentify WPObject_wpIdentify
#define WPPdr_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define WPPdr_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define WPPdr_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define WPPdr_wpAddToObjUseList WPObject_wpAddToObjUseList
#define WPPdr_wpAllocMem WPObject_wpAllocMem
#define WPPdr_wpAppendObject WPObject_wpAppendObject
#define WPPdr_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define WPPdr_wpClose WPObject_wpClose
#define WPPdr_wpCnrInsertObject WPObject_wpCnrInsertObject
#define WPPdr_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define WPPdr_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define WPPdr_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define WPPdr_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define WPPdr_wpCreateAnother WPObject_wpCreateAnother
#define WPPdr_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define WPPdr_wpCreateShadowObject WPObject_wpCreateShadowObject
#define WPPdr_wpDelete WPObject_wpDelete
#define WPPdr_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define WPPdr_wpDisplayHelp WPObject_wpDisplayHelp
#define WPPdr_wpDisplayMenu WPObject_wpDisplayMenu
#define WPPdr_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define WPPdr_wpDraggedOverObject WPObject_wpDraggedOverObject
#define WPPdr_wpDroppedOnObject WPObject_wpDroppedOnObject
#define WPPdr_wpEndConversation WPObject_wpEndConversation
#define WPPdr_wpFilterMenu WPObject_wpFilterMenu
#define WPPdr_wpFindUseItem WPObject_wpFindUseItem
#define WPPdr_wpFormatDragItem WPObject_wpFormatDragItem
#define WPPdr_wpFreeMem WPObject_wpFreeMem
#define WPPdr_wpHide WPObject_wpHide
#define WPPdr_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define WPPdr_wpInsertMenuItems WPObject_wpInsertMenuItems
#define WPPdr_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define WPPdr_wpModifyMenu WPObject_wpModifyMenu
#define WPPdr_wpMoveObject WPObject_wpMoveObject
#define WPPdr_wpPrintObject WPObject_wpPrintObject
#define WPPdr_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define WPPdr_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define WPPdr_wpQueryConfirmations WPObject_wpQueryConfirmations
#define WPPdr_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define WPPdr_wpQueryDefaultView WPObject_wpQueryDefaultView
#define WPPdr_wpQueryDetailsData WPObject_wpQueryDetailsData
#define WPPdr_wpQueryError WPObject_wpQueryError
#define WPPdr_wpSetFolder WPObject_wpSetFolder
#define WPPdr_wpQueryFolder WPObject_wpQueryFolder
#define WPPdr_wpQueryIconData WPObject_wpQueryIconData
#define WPPdr_wpQueryMinWindow WPObject_wpQueryMinWindow
#define WPPdr_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define WPPdr_wpQueryStyle WPObject_wpQueryStyle
#define WPPdr_wpSetTaskRec WPObject_wpSetTaskRec
#define WPPdr_wpFindTaskRec WPObject_wpFindTaskRec
#define WPPdr_wpRegisterView WPObject_wpRegisterView
#define WPPdr_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define WPPdr_wpRender WPObject_wpRender
#define WPPdr_wpRenderComplete WPObject_wpRenderComplete
#define WPPdr_wpReplaceObject WPObject_wpReplaceObject
#define WPPdr_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define WPPdr_wpRestore WPObject_wpRestore
#define WPPdr_wpRestoreData WPObject_wpRestoreData
#define WPPdr_wpRestoreLong WPObject_wpRestoreLong
#define WPPdr_wpRestoreState WPObject_wpRestoreState
#define WPPdr_wpRestoreString WPObject_wpRestoreString
#define WPPdr_wpSaveData WPObject_wpSaveData
#define WPPdr_wpSaveDeferred WPObject_wpSaveDeferred
#define WPPdr_wpSaveLong WPObject_wpSaveLong
#define WPPdr_wpSaveState WPObject_wpSaveState
#define WPPdr_wpSaveString WPObject_wpSaveString
#define WPPdr_wpScanSetupString WPObject_wpScanSetupString
#define WPPdr_wpSetConcurrentView WPObject_wpSetConcurrentView
#define WPPdr_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define WPPdr_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define WPPdr_wpSetDefaultView WPObject_wpSetDefaultView
#define WPPdr_wpSetError WPObject_wpSetError
#define WPPdr_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define WPPdr_wpSetupOnce WPObject_wpSetupOnce
#define WPPdr_wpSetIcon WPObject_wpSetIcon
#define WPPdr_wpSetIconData WPObject_wpSetIconData
#define WPPdr_wpSetMinWindow WPObject_wpSetMinWindow
#define WPPdr_wpModifyStyle WPObject_wpModifyStyle
#define WPPdr_wpSetTitle WPObject_wpSetTitle
#define WPPdr_wpSwitchTo WPObject_wpSwitchTo
#define WPPdr_wpViewObject WPObject_wpViewObject
#define WPPdr_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define WPPdr_wpUnlockObject WPObject_wpUnlockObject
#define WPPdr_wpObjectReady WPObject_wpObjectReady
#define WPPdr_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define WPPdr_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define WPPdr_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define WPPdr_wpIsDeleteable WPObject_wpIsDeleteable
#define WPPdr_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define WPPdr_wpSetObjectID WPObject_wpSetObjectID
#define WPPdr_wpQueryObjectID WPObject_wpQueryObjectID
#define WPPdr_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define WPPdr_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define WPPdr_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define WPPdr_wpFindViewItem WPObject_wpFindViewItem
#define WPPdr_wpLockObject WPObject_wpLockObject
#define WPPdr_wpIsLocked WPObject_wpIsLocked
#define WPPdr_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define WPPdr_wpWaitForClose WPObject_wpWaitForClose
#define WPPdr_wpSetMenuStyle WPObject_wpSetMenuStyle
#define WPPdr_wpQueryMenuStyle WPObject_wpQueryMenuStyle
#define WPPdr_wpSetStyle WPObject_wpSetStyle
#define WPPdr_somInit SOMObject_somInit
#define WPPdr_somUninit SOMObject_somUninit
#define WPPdr_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define WPPdr_somDefaultAssign SOMObject_somDefaultAssign
#define WPPdr_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define WPPdr_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define WPPdr_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define WPPdr_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define WPPdr_somDefaultVAssign SOMObject_somDefaultVAssign
#define WPPdr_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define WPPdr_somFree SOMObject_somFree
#define WPPdr_somGetClass SOMObject_somGetClass
#define WPPdr_somGetClassName SOMObject_somGetClassName
#define WPPdr_somGetSize SOMObject_somGetSize
#define WPPdr_somIsA SOMObject_somIsA
#define WPPdr_somIsInstanceOf SOMObject_somIsInstanceOf
#define WPPdr_somRespondsTo SOMObject_somRespondsTo
#define WPPdr_somDispatch SOMObject_somDispatch
#define WPPdr_somClassDispatch SOMObject_somClassDispatch
#define WPPdr_somCastObj SOMObject_somCastObj
#define WPPdr_somResetObj SOMObject_somResetObj
#define WPPdr_somDispatchV SOMObject_somDispatchV
#define WPPdr_somDispatchL SOMObject_somDispatchL
#define WPPdr_somDispatchA SOMObject_somDispatchA
#define WPPdr_somDispatchD SOMObject_somDispatchD
#define WPPdr_somPrintSelf SOMObject_somPrintSelf
#define WPPdr_somDumpSelf SOMObject_somDumpSelf
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_WPPdr_h */

#ifndef SOM_M_WPPdr_h
#define SOM_M_WPPdr_h


#include <som.h>

/*
 * -- This emitter normally treats Method Tokens as Thunks,
 * -- but the sc modifier "nothunks" was used, so somResolve will be called.
 */
#undef somresolve_
#define somresolve_(obj,mToken) (somResolve(obj,mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_WPPdr
#define M_WPPdr SOMObject
#endif
#include <wptrans.h>

/*
 * Start of bindings for IDL types
 */


/*
 * End of bindings for IDL types.
 */

#define M_WPPdr_MajorVersion 1
#define M_WPPdr_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_WPPdrNewClass WPpdrc
#define M_WPPdrClassData WPpdrd
#define M_WPPdrCClassData WPpdrx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_WPPdr_classObj M_WPPdrClassData.classObject
#define _M_WPPdr M_WPPdr_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_WPPdrNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_WPPdrClassDataStructure {
	SOMClass *classObject;
} SOMDLINK M_WPPdrClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_WPPdrCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_WPPdrCClassData;

/*
 * New and Renew macros for M_WPPdr
 */
#define M_WPPdrNew() \
   ( _M_WPPdr ? \
	_somNew(_M_WPPdr) \
	: ( M_WPPdrNewClass(\
		M_WPPdr_MajorVersion, \
		M_WPPdr_MinorVersion),\
	   _somNew(_M_WPPdr)))
#define M_WPPdrRenew(buf) \
   ( _M_WPPdr ? \
	_somRenew(_M_WPPdr, buf) \
	: ( M_WPPdrNewClass(\
		M_WPPdr_MajorVersion, \
		M_WPPdr_MinorVersion),\
	   _somRenew(_M_WPPdr, buf)))

/*
 * Override method: wpclsQueryTitle
 */
#define M_WPPdr_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)

/*
 * Override method: wpclsQueryIcon
 */
#define M_WPPdr_wpclsQueryIcon(somSelf) \
	M_WPObject_wpclsQueryIcon(somSelf)

/*
 * Override method: wpclsQueryDefaultHelp
 */
#define M_WPPdr_wpclsQueryDefaultHelp(somSelf,pHelpPanelId,pszHelpLibrary) \
	M_WPObject_wpclsQueryDefaultHelp(somSelf,pHelpPanelId,pszHelpLibrary)

/*
 * Override method: wpclsQueryDefaultView
 */
#define M_WPPdr_wpclsQueryDefaultView(somSelf) \
	M_WPObject_wpclsQueryDefaultView(somSelf)

/*
 * Override method: wpclsQueryStyle
 */
#define M_WPPdr_wpclsQueryStyle(somSelf) \
	M_WPObject_wpclsQueryStyle(somSelf)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_WPPdr_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_WPPdr_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_WPPdr_wpclsInitData M_WPObject_wpclsInitData
#define M_WPPdr_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_WPPdr_wpclsNew M_WPObject_wpclsNew
#define M_WPPdr_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_WPPdr_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_WPPdr_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_WPPdr_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_WPPdr_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_WPPdr_wpclsUnInitData M_WPObject_wpclsUnInitData
#define M_WPPdr_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_WPPdr_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_WPPdr_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_WPPdr_wpclsSetError M_WPObject_wpclsSetError
#define M_WPPdr_wpclsQueryError M_WPObject_wpclsQueryError
#define M_WPPdr_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_WPPdr_wpclsQueryIconData M_WPObject_wpclsQueryIconData
#define M_WPPdr_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_WPPdr_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_WPPdr_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_WPPdr_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_WPPdr_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_WPPdr_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_WPPdr_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_WPPdr_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_WPPdr_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_WPPdr_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_WPPdr_somUninit SOMObject_somUninit
#define M_WPPdr_somClassReady SOMClass_somClassReady
#define M_WPPdr_somNew SOMClass_somNew
#define M_WPPdr_somRenew SOMClass_somRenew
#define M_WPPdr__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_WPPdr__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_WPPdr__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_WPPdr__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_WPPdr_somNewNoInit SOMClass_somNewNoInit
#define M_WPPdr_somRenewNoInit SOMClass_somRenewNoInit
#define M_WPPdr_somRenewNoZero SOMClass_somRenewNoZero
#define M_WPPdr_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_WPPdr_somAllocate SOMClass_somAllocate
#define M_WPPdr_somDeallocate SOMClass_somDeallocate
#define M_WPPdr__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_WPPdr__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_WPPdr_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_WPPdr_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_WPPdr_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_WPPdr_somInitClass SOMClass_somInitClass
#define M_WPPdr_somInitMIClass SOMClass_somInitMIClass
#define M_WPPdr_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_WPPdr_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_WPPdr_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_WPPdr_somGetApplyStub SOMClass_somGetApplyStub
#define M_WPPdr_somGetClassData SOMClass_somGetClassData
#define M_WPPdr_somSetClassData SOMClass_somSetClassData
#define M_WPPdr_somGetClassMtab SOMClass_somGetClassMtab
#define M_WPPdr_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_WPPdr_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_WPPdr_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_WPPdr_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_WPPdr_somGetMemberToken SOMClass_somGetMemberToken
#define M_WPPdr_somGetMethodData SOMClass_somGetMethodData
#define M_WPPdr_somGetRdStub SOMClass_somGetRdStub
#define M_WPPdr_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_WPPdr_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_WPPdr_somGetMethodToken SOMClass_somGetMethodToken
#define M_WPPdr_somGetName SOMClass_somGetName
#define M_WPPdr_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_WPPdr_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_WPPdr_somGetNumMethods SOMClass_somGetNumMethods
#define M_WPPdr_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_WPPdr_somGetParent SOMClass_somGetParent
#define M_WPPdr_somGetParents SOMClass_somGetParents
#define M_WPPdr_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_WPPdr_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_WPPdr_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_WPPdr_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_WPPdr_somFindMethod SOMClass_somFindMethod
#define M_WPPdr_somFindMethodOk SOMClass_somFindMethodOk
#define M_WPPdr_somFindSMethod SOMClass_somFindSMethod
#define M_WPPdr_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_WPPdr_somLookupMethod SOMClass_somLookupMethod
#define M_WPPdr_somCheckVersion SOMClass_somCheckVersion
#define M_WPPdr_somDescendedFrom SOMClass_somDescendedFrom
#define M_WPPdr_somSupportsMethod SOMClass_somSupportsMethod
#define M_WPPdr_somDefinedMethod SOMClass_somDefinedMethod
#define M_WPPdr_somOverrideMtab SOMClass_somOverrideMtab
#define M_WPPdr_somDefaultInit SOMObject_somDefaultInit
#define M_WPPdr_somDestruct SOMObject_somDestruct
#define M_WPPdr_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_WPPdr_somDefaultAssign SOMObject_somDefaultAssign
#define M_WPPdr_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_WPPdr_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_WPPdr_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_WPPdr_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_WPPdr_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_WPPdr_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_WPPdr_somInit SOMObject_somInit
#define M_WPPdr_somFree SOMObject_somFree
#define M_WPPdr_somGetClass SOMObject_somGetClass
#define M_WPPdr_somGetClassName SOMObject_somGetClassName
#define M_WPPdr_somGetSize SOMObject_somGetSize
#define M_WPPdr_somIsA SOMObject_somIsA
#define M_WPPdr_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_WPPdr_somRespondsTo SOMObject_somRespondsTo
#define M_WPPdr_somDispatch SOMObject_somDispatch
#define M_WPPdr_somClassDispatch SOMObject_somClassDispatch
#define M_WPPdr_somCastObj SOMObject_somCastObj
#define M_WPPdr_somResetObj SOMObject_somResetObj
#define M_WPPdr_somDispatchV SOMObject_somDispatchV
#define M_WPPdr_somDispatchL SOMObject_somDispatchL
#define M_WPPdr_somDispatchA SOMObject_somDispatchA
#define M_WPPdr_somDispatchD SOMObject_somDispatchD
#define M_WPPdr_somPrintSelf SOMObject_somPrintSelf
#define M_WPPdr_somDumpSelf SOMObject_somDumpSelf
#define M_WPPdr_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_WPPdr_h */
