
/*
 * This file was generated by the SOM Compiler.
 * FileName: G:\cwpsh\rel\os2c\include\base\os2\wptrans.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.14
 *     SOM Emitter emith: 2.43
 */

/*
 *   Module Header
 * 
 *   Module Name: WPTRANS
 * 
 *   OS/2 Presentation Manager Workplace class definitions
 * 
 *   Copyright (c) International Business Machines Corporation 1991, 1992
 * 
 */


#ifndef SOM_WPTransient_h
#define SOM_WPTransient_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef WPTransient
#define WPTransient SOMObject
#endif
#include <wpobject.h>

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef WPImageFile
    #define WPImageFile SOMObject
#endif /* WPImageFile */
#ifndef M_WPTransient
    #define M_WPTransient SOMObject
#endif /* M_WPTransient */

/*
 * End of bindings for IDL types.
 */

#define WPTransient_MajorVersion 1
#define WPTransient_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define WPTransientNewClass wptrnc
#pragma linkage(wptrnc, system)
#define WPTransientClassData wptrnd
#define WPTransientCClassData wptrnx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */

/*
 * Include the meta class file
 */
#include <wptrans.h>
/*--------------Migration------------*/
#define WPTransient_classObj WPTransientClassData.classObject
#define _WPTransient WPTransient_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK WPTransientNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(WPTransientNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct WPTransientClassDataStructure {
	SOMClass *classObject;
} SOMDLINK WPTransientClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct WPTransientCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK WPTransientCClassData;

/*
 * New and Renew macros for WPTransient
 */
#define WPTransientNew() \
   ( _WPTransient ? \
	_somNew(_WPTransient) \
	: ( WPTransientNewClass(\
		WPTransient_MajorVersion, \
		WPTransient_MinorVersion),\
	   _somNew(_WPTransient)))
#define WPTransientRenew(buf) \
   ( _WPTransient ? \
	_somRenew(_WPTransient, buf) \
	: ( WPTransientNewClass(\
		WPTransient_MajorVersion, \
		WPTransient_MinorVersion),\
	   _somRenew(_WPTransient, buf)))

/*
 * Override method: wpQueryHandle
 */
#define WPTransient_wpQueryHandle(somSelf) \
	WPObject_wpQueryHandle(somSelf)

/*
 * Override method: wpCopyObject
 */
#define WPTransient_wpCopyObject(somSelf,Folder,fLock) \
	WPObject_wpCopyObject(somSelf,Folder,fLock)

/*
 * Override method: somDefaultInit
 */
#define WPTransient_somDefaultInit(somSelf,ctrl) \
	SOMObject_somDefaultInit(somSelf,ctrl)

/*
 * Override method: somDestruct
 */
#define WPTransient_somDestruct(somSelf,doFree,ctrl) \
	SOMObject_somDestruct(somSelf,doFree,ctrl)

/*
 * Override method: wpQueryIcon
 */
#define WPTransient_wpQueryIcon(somSelf) \
	WPObject_wpQueryIcon(somSelf)

/*
 * Override method: wpSaveImmediate
 */
#define WPTransient_wpSaveImmediate(somSelf) \
	WPObject_wpSaveImmediate(somSelf)

/*
 * Override method: wpIdentify
 */
#define WPTransient_wpIdentify(somSelf,pszIdentity) \
	WPObject_wpIdentify(somSelf,pszIdentity)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define WPTransient_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define WPTransient_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define WPTransient_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define WPTransient_wpAddSettingsPages WPObject_wpAddSettingsPages
#define WPTransient_wpAddToObjUseList WPObject_wpAddToObjUseList
#define WPTransient_wpAllocMem WPObject_wpAllocMem
#define WPTransient_wpAppendObject WPObject_wpAppendObject
#define WPTransient_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define WPTransient_wpClose WPObject_wpClose
#define WPTransient_wpCnrInsertObject WPObject_wpCnrInsertObject
#define WPTransient_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define WPTransient_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define WPTransient_wpConfirmDelete WPObject_wpConfirmDelete
#define WPTransient_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define WPTransient_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define WPTransient_wpCreateAnother WPObject_wpCreateAnother
#define WPTransient_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define WPTransient_wpCreateShadowObject WPObject_wpCreateShadowObject
#define WPTransient_wpDelete WPObject_wpDelete
#define WPTransient_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define WPTransient_wpDisplayHelp WPObject_wpDisplayHelp
#define WPTransient_wpDisplayMenu WPObject_wpDisplayMenu
#define WPTransient_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define WPTransient_wpDraggedOverObject WPObject_wpDraggedOverObject
#define WPTransient_wpDragOver WPObject_wpDragOver
#define WPTransient_wpDrop WPObject_wpDrop
#define WPTransient_wpDroppedOnObject WPObject_wpDroppedOnObject
#define WPTransient_wpEndConversation WPObject_wpEndConversation
#define WPTransient_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define WPTransient_wpFilterMenu WPObject_wpFilterMenu
#define WPTransient_wpFindUseItem WPObject_wpFindUseItem
#define WPTransient_wpFormatDragItem WPObject_wpFormatDragItem
#define WPTransient_wpFree WPObject_wpFree
#define WPTransient_wpFreeMem WPObject_wpFreeMem
#define WPTransient_wpHide WPObject_wpHide
#define WPTransient_wpInitData WPObject_wpInitData
#define WPTransient_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define WPTransient_wpInsertMenuItems WPObject_wpInsertMenuItems
#define WPTransient_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define WPTransient_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define WPTransient_wpMenuItemSelected WPObject_wpMenuItemSelected
#define WPTransient_wpModifyPopupMenu WPObject_wpModifyPopupMenu
#define WPTransient_wpModifyMenu WPObject_wpModifyMenu
#define WPTransient_wpMoveObject WPObject_wpMoveObject
#define WPTransient_wpOpen WPObject_wpOpen
#define WPTransient_wpPrintObject WPObject_wpPrintObject
#define WPTransient_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define WPTransient_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define WPTransient_wpQueryConfirmations WPObject_wpQueryConfirmations
#define WPTransient_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define WPTransient_wpQueryDefaultView WPObject_wpQueryDefaultView
#define WPTransient_wpQueryDetailsData WPObject_wpQueryDetailsData
#define WPTransient_wpQueryError WPObject_wpQueryError
#define WPTransient_wpSetFolder WPObject_wpSetFolder
#define WPTransient_wpQueryFolder WPObject_wpQueryFolder
#define WPTransient_wpQueryIconData WPObject_wpQueryIconData
#define WPTransient_wpQueryMinWindow WPObject_wpQueryMinWindow
#define WPTransient_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define WPTransient_wpQueryStyle WPObject_wpQueryStyle
#define WPTransient_wpSetTaskRec WPObject_wpSetTaskRec
#define WPTransient_wpFindTaskRec WPObject_wpFindTaskRec
#define WPTransient_wpQueryTitle WPObject_wpQueryTitle
#define WPTransient_wpRegisterView WPObject_wpRegisterView
#define WPTransient_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define WPTransient_wpRender WPObject_wpRender
#define WPTransient_wpRenderComplete WPObject_wpRenderComplete
#define WPTransient_wpReplaceObject WPObject_wpReplaceObject
#define WPTransient_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define WPTransient_wpRestore WPObject_wpRestore
#define WPTransient_wpRestoreData WPObject_wpRestoreData
#define WPTransient_wpRestoreLong WPObject_wpRestoreLong
#define WPTransient_wpRestoreState WPObject_wpRestoreState
#define WPTransient_wpRestoreString WPObject_wpRestoreString
#define WPTransient_wpSaveData WPObject_wpSaveData
#define WPTransient_wpSaveDeferred WPObject_wpSaveDeferred
#define WPTransient_wpSaveLong WPObject_wpSaveLong
#define WPTransient_wpSaveState WPObject_wpSaveState
#define WPTransient_wpSaveString WPObject_wpSaveString
#define WPTransient_wpScanSetupString WPObject_wpScanSetupString
#define WPTransient_wpSetConcurrentView WPObject_wpSetConcurrentView
#define WPTransient_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define WPTransient_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define WPTransient_wpSetDefaultView WPObject_wpSetDefaultView
#define WPTransient_wpSetError WPObject_wpSetError
#define WPTransient_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define WPTransient_wpSetupOnce WPObject_wpSetupOnce
#define WPTransient_wpSetIcon WPObject_wpSetIcon
#define WPTransient_wpSetIconData WPObject_wpSetIconData
#define WPTransient_wpSetMinWindow WPObject_wpSetMinWindow
#define WPTransient_wpModifyStyle WPObject_wpModifyStyle
#define WPTransient_wpSetTitle WPObject_wpSetTitle
#define WPTransient_wpSetup WPObject_wpSetup
#define WPTransient_wpSwitchTo WPObject_wpSwitchTo
#define WPTransient_wpUnInitData WPObject_wpUnInitData
#define WPTransient_wpViewObject WPObject_wpViewObject
#define WPTransient_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define WPTransient_wpUnlockObject WPObject_wpUnlockObject
#define WPTransient_wpObjectReady WPObject_wpObjectReady
#define WPTransient_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define WPTransient_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define WPTransient_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define WPTransient_wpIsDeleteable WPObject_wpIsDeleteable
#define WPTransient_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define WPTransient_wpSetObjectID WPObject_wpSetObjectID
#define WPTransient_wpQueryObjectID WPObject_wpQueryObjectID
#define WPTransient_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define WPTransient_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define WPTransient_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define WPTransient_wpFindViewItem WPObject_wpFindViewItem
#define WPTransient_wpLockObject WPObject_wpLockObject
#define WPTransient_wpIsLocked WPObject_wpIsLocked
#define WPTransient_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define WPTransient_wpWaitForClose WPObject_wpWaitForClose
#define WPTransient_wpSetMenuStyle WPObject_wpSetMenuStyle
#define WPTransient_wpQueryMenuStyle WPObject_wpQueryMenuStyle
#define WPTransient_wpSetStyle WPObject_wpSetStyle
#define WPTransient_somInit SOMObject_somInit
#define WPTransient_somUninit SOMObject_somUninit
#define WPTransient_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define WPTransient_somDefaultAssign SOMObject_somDefaultAssign
#define WPTransient_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define WPTransient_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define WPTransient_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define WPTransient_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define WPTransient_somDefaultVAssign SOMObject_somDefaultVAssign
#define WPTransient_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define WPTransient_somFree SOMObject_somFree
#define WPTransient_somGetClass SOMObject_somGetClass
#define WPTransient_somGetClassName SOMObject_somGetClassName
#define WPTransient_somGetSize SOMObject_somGetSize
#define WPTransient_somIsA SOMObject_somIsA
#define WPTransient_somIsInstanceOf SOMObject_somIsInstanceOf
#define WPTransient_somRespondsTo SOMObject_somRespondsTo
#define WPTransient_somDispatch SOMObject_somDispatch
#define WPTransient_somClassDispatch SOMObject_somClassDispatch
#define WPTransient_somCastObj SOMObject_somCastObj
#define WPTransient_somResetObj SOMObject_somResetObj
#define WPTransient_somDispatchV SOMObject_somDispatchV
#define WPTransient_somDispatchL SOMObject_somDispatchL
#define WPTransient_somDispatchA SOMObject_somDispatchA
#define WPTransient_somDispatchD SOMObject_somDispatchD
#define WPTransient_somPrintSelf SOMObject_somPrintSelf
#define WPTransient_somDumpSelf SOMObject_somDumpSelf
#define WPTransient_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_WPTransient_h */

#ifndef SOM_M_WPTransient_h
#define SOM_M_WPTransient_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_WPTransient
#define M_WPTransient SOMObject
#endif
#include <wpobject.h>

/*
 * Start of bindings for IDL types
 */


/*
 * End of bindings for IDL types.
 */

#define M_WPTransient_MajorVersion 1
#define M_WPTransient_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_WPTransientNewClass wptrnc
#pragma linkage(wptrnc, system)
#define M_WPTransientClassData wptrnd
#define M_WPTransientCClassData wptrnx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_WPTransient_classObj M_WPTransientClassData.classObject
#define _M_WPTransient M_WPTransient_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_WPTransientNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_WPTransientNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_WPTransientClassDataStructure {
	SOMClass *classObject;
	somMToken wpclsTransientPrivate1;
	somMToken wpclsTransientPrivate2;
} SOMDLINK M_WPTransientClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_WPTransientCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_WPTransientCClassData;

/*
 * New and Renew macros for M_WPTransient
 */
#define M_WPTransientNew() \
   ( _M_WPTransient ? \
	_somNew(_M_WPTransient) \
	: ( M_WPTransientNewClass(\
		M_WPTransient_MajorVersion, \
		M_WPTransient_MinorVersion),\
	   _somNew(_M_WPTransient)))
#define M_WPTransientRenew(buf) \
   ( _M_WPTransient ? \
	_somRenew(_M_WPTransient, buf) \
	: ( M_WPTransientNewClass(\
		M_WPTransient_MajorVersion, \
		M_WPTransient_MinorVersion),\
	   _somRenew(_M_WPTransient, buf)))

/*
 * Override method: wpclsQueryTitle
 */
#define M_WPTransient_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)

/*
 * Override method: wpclsQueryStyle
 */
#define M_WPTransient_wpclsQueryStyle(somSelf) \
	M_WPObject_wpclsQueryStyle(somSelf)

/*
 * Override method: wpclsObjectFromHandle
 */
#define M_WPTransient_wpclsObjectFromHandle(somSelf,hObject) \
	M_WPObject_wpclsObjectFromHandle(somSelf,hObject)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_WPTransient_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_WPTransient_wpclsInitData M_WPObject_wpclsInitData
#define M_WPTransient_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_WPTransient_wpclsNew M_WPObject_wpclsNew
#define M_WPTransient_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_WPTransient_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_WPTransient_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_WPTransient_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_WPTransient_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_WPTransient_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_WPTransient_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_WPTransient_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_WPTransient_wpclsUnInitData M_WPObject_wpclsUnInitData
#define M_WPTransient_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_WPTransient_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_WPTransient_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_WPTransient_wpclsSetError M_WPObject_wpclsSetError
#define M_WPTransient_wpclsQueryError M_WPObject_wpclsQueryError
#define M_WPTransient_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_WPTransient_wpclsQueryIconData M_WPObject_wpclsQueryIconData
#define M_WPTransient_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_WPTransient_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_WPTransient_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_WPTransient_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_WPTransient_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_WPTransient_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_WPTransient_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_WPTransient_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_WPTransient_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_WPTransient_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_WPTransient_somUninit SOMObject_somUninit
#define M_WPTransient_somClassReady SOMClass_somClassReady
#define M_WPTransient_somNew SOMClass_somNew
#define M_WPTransient_somRenew SOMClass_somRenew
#define M_WPTransient__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_WPTransient__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_WPTransient__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_WPTransient__set_somDirectInitClasses SOMClass__set_somDirectInitClasses
#define M_WPTransient_somNewNoInit SOMClass_somNewNoInit
#define M_WPTransient_somRenewNoInit SOMClass_somRenewNoInit
#define M_WPTransient_somRenewNoZero SOMClass_somRenewNoZero
#define M_WPTransient_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_WPTransient_somAllocate SOMClass_somAllocate
#define M_WPTransient_somDeallocate SOMClass_somDeallocate
#define M_WPTransient__get_somClassAllocate SOMClass__get_somClassAllocate
#define M_WPTransient__get_somClassDeallocate SOMClass__get_somClassDeallocate
#define M_WPTransient_somGetInstanceInitMask SOMClass_somGetInstanceInitMask
#define M_WPTransient_somGetInstanceDestructionMask SOMClass_somGetInstanceDestructionMask
#define M_WPTransient_somGetInstanceAssignmentMask SOMClass_somGetInstanceAssignmentMask
#define M_WPTransient_somInitClass SOMClass_somInitClass
#define M_WPTransient_somInitMIClass SOMClass_somInitMIClass
#define M_WPTransient_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_WPTransient_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_WPTransient_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_WPTransient_somGetApplyStub SOMClass_somGetApplyStub
#define M_WPTransient_somGetClassData SOMClass_somGetClassData
#define M_WPTransient_somSetClassData SOMClass_somSetClassData
#define M_WPTransient_somGetClassMtab SOMClass_somGetClassMtab
#define M_WPTransient_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_WPTransient_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_WPTransient_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_WPTransient_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_WPTransient_somGetMemberToken SOMClass_somGetMemberToken
#define M_WPTransient_somGetMethodData SOMClass_somGetMethodData
#define M_WPTransient_somGetRdStub SOMClass_somGetRdStub
#define M_WPTransient_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_WPTransient_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_WPTransient_somGetMethodToken SOMClass_somGetMethodToken
#define M_WPTransient_somGetName SOMClass_somGetName
#define M_WPTransient_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_WPTransient_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_WPTransient_somGetNumMethods SOMClass_somGetNumMethods
#define M_WPTransient_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_WPTransient_somGetParent SOMClass_somGetParent
#define M_WPTransient_somGetParents SOMClass_somGetParents
#define M_WPTransient_somGetPClsMtab SOMClass_somGetPClsMtab
#define M_WPTransient_somGetPClsMtabs SOMClass_somGetPClsMtabs
#define M_WPTransient_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_WPTransient_somSetMethodDescriptor SOMClass_somSetMethodDescriptor
#define M_WPTransient_somFindMethod SOMClass_somFindMethod
#define M_WPTransient_somFindMethodOk SOMClass_somFindMethodOk
#define M_WPTransient_somFindSMethod SOMClass_somFindSMethod
#define M_WPTransient_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_WPTransient_somLookupMethod SOMClass_somLookupMethod
#define M_WPTransient_somCheckVersion SOMClass_somCheckVersion
#define M_WPTransient_somDescendedFrom SOMClass_somDescendedFrom
#define M_WPTransient_somSupportsMethod SOMClass_somSupportsMethod
#define M_WPTransient_somDefinedMethod SOMClass_somDefinedMethod
#define M_WPTransient_somOverrideMtab SOMClass_somOverrideMtab
#define M_WPTransient_somDefaultInit SOMObject_somDefaultInit
#define M_WPTransient_somDestruct SOMObject_somDestruct
#define M_WPTransient_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_WPTransient_somDefaultAssign SOMObject_somDefaultAssign
#define M_WPTransient_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_WPTransient_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_WPTransient_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_WPTransient_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_WPTransient_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_WPTransient_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_WPTransient_somInit SOMObject_somInit
#define M_WPTransient_somFree SOMObject_somFree
#define M_WPTransient_somGetClass SOMObject_somGetClass
#define M_WPTransient_somGetClassName SOMObject_somGetClassName
#define M_WPTransient_somGetSize SOMObject_somGetSize
#define M_WPTransient_somIsA SOMObject_somIsA
#define M_WPTransient_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_WPTransient_somRespondsTo SOMObject_somRespondsTo
#define M_WPTransient_somDispatch SOMObject_somDispatch
#define M_WPTransient_somClassDispatch SOMObject_somClassDispatch
#define M_WPTransient_somCastObj SOMObject_somCastObj
#define M_WPTransient_somResetObj SOMObject_somResetObj
#define M_WPTransient_somDispatchV SOMObject_somDispatchV
#define M_WPTransient_somDispatchL SOMObject_somDispatchL
#define M_WPTransient_somDispatchA SOMObject_somDispatchA
#define M_WPTransient_somDispatchD SOMObject_somDispatchD
#define M_WPTransient_somPrintSelf SOMObject_somPrintSelf
#define M_WPTransient_somDumpSelf SOMObject_somDumpSelf
#define M_WPTransient_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_WPTransient_h */
