//
//   COMPONENT_NAME: somp
//
//   ORIGINS: 27
//
//
//    25H7912  (C)  COPYRIGHT International Business Machines Corp. 1992,1994,1996 
//   All Rights Reserved
//   Licensed Materials - Property of IBM
//   US Government Users Restricted Rights - Use, duplication or
//   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
//
//#  @(#) 2.9 src/somp/mia.idl, somp, som2.1 12/26/95 16:58:00 [7/30/96 14:46:55]



#ifndef mia_idl
#define mia_idl

#include <somobj.idl>
#include <somp.idl>
#include <somperrd.idl>

interface SOMPMediaInterfaceAbstract : SOMObject

// This is the abstract class definition for an interface to
// some media.

{
   void sompOpen() raises (SOMPError::sompException);
// Open the media interface.

   void sompClose() raises (SOMPError::sompException);
// Close the media interface.

#ifdef __SOMIDL__

implementation
{
    callstyle=idl;
    dllname="somp.dll";

    majorversion = 2;
    minorversion = 1;

    releaseorder: sompOpen, sompClose;

// Class Modifiers
   filestem = mia;

// Method Modifiers

};
#endif /* __SOMIDL__ */
};

#endif  /* mia_idl */
