
/*
 * This file was generated by the SOM Compiler.
 * FileName: scbase.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.17
 *     SOM Emitter emith: 2.47
 */

/*
 *   COMPONENT_NAME: some
 * 
 *   ORIGINS: 27
 * 
 * 
 *    25H7912  (C)  COPYRIGHT International Business Machines Corp. 1992,1994,1996
 *   All Rights Reserved
 *   Licensed Materials - Property of IBM
 *   US Government Users Restricted Rights - Use, duplication or
 *   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 *  @(#) somc/sctypes.h 2.7 12/26/95 16:26:17 [7/30/96 14:46:04]
 * 
 */


#ifndef SOM_SOMTBaseClassEntryC_h
#define SOM_SOMTBaseClassEntryC_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef SOMTBaseClassEntryC
#define SOMTBaseClassEntryC SOMObject
#endif
#include <scentry.h>

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef SOMTEntryC
    #define SOMTEntryC SOMObject
#endif /* SOMTEntryC */
#ifndef SOMTEmitC
    #define SOMTEmitC SOMObject
#endif /* SOMTEmitC */
#ifndef SOMTMetaClassEntryC
    #define SOMTMetaClassEntryC SOMObject
#endif /* SOMTMetaClassEntryC */
#ifndef SOMTAttributeEntryC
    #define SOMTAttributeEntryC SOMObject
#endif /* SOMTAttributeEntryC */
#ifndef SOMTTypedefEntryC
    #define SOMTTypedefEntryC SOMObject
#endif /* SOMTTypedefEntryC */
#ifndef SOMTBaseClassEntryC
    #define SOMTBaseClassEntryC SOMObject
#endif /* SOMTBaseClassEntryC */
#ifndef SOMTPassthruEntryC
    #define SOMTPassthruEntryC SOMObject
#endif /* SOMTPassthruEntryC */
#ifndef SOMTDataEntryC
    #define SOMTDataEntryC SOMObject
#endif /* SOMTDataEntryC */
#ifndef SOMTMethodEntryC
    #define SOMTMethodEntryC SOMObject
#endif /* SOMTMethodEntryC */
#ifndef SOMTClassEntryC
    #define SOMTClassEntryC SOMObject
#endif /* SOMTClassEntryC */
#ifndef SOMTModuleEntryC
    #define SOMTModuleEntryC SOMObject
#endif /* SOMTModuleEntryC */
#ifndef SOMTParameterEntryC
    #define SOMTParameterEntryC SOMObject
#endif /* SOMTParameterEntryC */
#ifndef SOMTStructEntryC
    #define SOMTStructEntryC SOMObject
#endif /* SOMTStructEntryC */
#ifndef SOMTUnionEntryC
    #define SOMTUnionEntryC SOMObject
#endif /* SOMTUnionEntryC */
#ifndef SOMTEnumEntryC
    #define SOMTEnumEntryC SOMObject
#endif /* SOMTEnumEntryC */
#ifndef SOMTConstEntryC
    #define SOMTConstEntryC SOMObject
#endif /* SOMTConstEntryC */
#ifndef SOMTSequenceEntryC
    #define SOMTSequenceEntryC SOMObject
#endif /* SOMTSequenceEntryC */
#ifndef SOMTStringEntryC
    #define SOMTStringEntryC SOMObject
#endif /* SOMTStringEntryC */
#ifndef SOMTEnumNameEntryC
    #define SOMTEnumNameEntryC SOMObject
#endif /* SOMTEnumNameEntryC */
#ifndef SOMTCommonEntryC
    #define SOMTCommonEntryC SOMObject
#endif /* SOMTCommonEntryC */
#ifndef SOMTUserDefinedTypeEntryC
    #define SOMTUserDefinedTypeEntryC SOMObject
#endif /* SOMTUserDefinedTypeEntryC */

/*
 * End of bindings for IDL types.
 */

#define SOMTBaseClassEntryC_MajorVersion 2
#define SOMTBaseClassEntryC_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define SOMTBaseClassEntryCNewClass c
#pragma linkage(c, system)
#define SOMTBaseClassEntryCClassData d
#define SOMTBaseClassEntryCCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define SOMTBaseClassEntryC_classObj SOMTBaseClassEntryCClassData.classObject
#define _SOMTBaseClassEntryC SOMTBaseClassEntryC_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK SOMTBaseClassEntryCNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(SOMTBaseClassEntryCNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct SOMTBaseClassEntryCClassDataStructure {
	SOMClass *classObject;
	somMToken _get_somtBaseClassDef;
} SOMDLINK SOMTBaseClassEntryCClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct SOMTBaseClassEntryCCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK SOMTBaseClassEntryCCClassData;

/*
 * New and Renew macros for SOMTBaseClassEntryC
 */
#define SOMTBaseClassEntryCNew() \
   ( _SOMTBaseClassEntryC ? \
	_somNew(_SOMTBaseClassEntryC) \
	: ( SOMTBaseClassEntryCNewClass(\
		SOMTBaseClassEntryC_MajorVersion, \
		SOMTBaseClassEntryC_MinorVersion),\
	   _somNew(_SOMTBaseClassEntryC)))
#define SOMTBaseClassEntryCRenew(buf) \
   ( _SOMTBaseClassEntryC ? \
	_somRenew(_SOMTBaseClassEntryC, buf) \
	: ( SOMTBaseClassEntryCNewClass(\
		SOMTBaseClassEntryC_MajorVersion, \
		SOMTBaseClassEntryC_MinorVersion),\
	   _somRenew(_SOMTBaseClassEntryC, buf)))

/*
 * Override method: somDumpSelfInt
 */
#define SOMTBaseClassEntryC_somDumpSelfInt(somSelf,level) \
	SOMObject_somDumpSelfInt(somSelf,level)

/*
 * Override method: somtSetSymbolsOnEntry
 */
#define SOMTBaseClassEntryC_somtSetSymbolsOnEntry(somSelf,emitter,prefix) \
	SOMTEntryC_somtSetSymbolsOnEntry(somSelf,emitter,prefix)

/*
 * New Method: _get_somtBaseClassDef
 */
typedef SOMTClassEntryC*   SOMLINK somTP_SOMTBaseClassEntryC__get_somtBaseClassDef(SOMTBaseClassEntryC *somSelf);
#pragma linkage(somTP_SOMTBaseClassEntryC__get_somtBaseClassDef, system)
typedef somTP_SOMTBaseClassEntryC__get_somtBaseClassDef *somTD_SOMTBaseClassEntryC__get_somtBaseClassDef;
/*
 *  Returns the class definition entry for the Base class named in
 *  this entry.
 */
#define somMD_SOMTBaseClassEntryC__get_somtBaseClassDef "::SOMTBaseClassEntryC::_get_somtBaseClassDef"
#define SOMTBaseClassEntryC__get_somtBaseClassDef(somSelf) \
    (SOM_Resolve(somSelf, SOMTBaseClassEntryC, _get_somtBaseClassDef) \
	(somSelf))
#ifndef SOMGD_get_somtBaseClassDef
    #if (defined(_get_somtBaseClassDef) || defined(__get_somtBaseClassDef))
        #undef _get_somtBaseClassDef
        #undef __get_somtBaseClassDef
        #define SOMGD_get_somtBaseClassDef 1
    #else
        #define __get_somtBaseClassDef SOMTBaseClassEntryC__get_somtBaseClassDef
    #endif /* __get_somtBaseClassDef */
#endif /* SOMGD_get_somtBaseClassDef */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define SOMTBaseClassEntryC__get_somtEntryName SOMTEntryC__get_somtEntryName
#define SOMTBaseClassEntryC__set_somtEntryName SOMTEntryC__set_somtEntryName
#define SOMTBaseClassEntryC__get_somtElementType SOMTEntryC__get_somtElementType
#define SOMTBaseClassEntryC__set_somtElementType SOMTEntryC__set_somtElementType
#define SOMTBaseClassEntryC__get_somtElementTypeName SOMTEntryC__get_somtElementTypeName
#define SOMTBaseClassEntryC__get_somtEntryComment SOMTEntryC__get_somtEntryComment
#define SOMTBaseClassEntryC__get_somtSourceLineNumber SOMTEntryC__get_somtSourceLineNumber
#define SOMTBaseClassEntryC__get_somtTypeCode SOMTEntryC__get_somtTypeCode
#define SOMTBaseClassEntryC__get_somtIsReference SOMTEntryC__get_somtIsReference
#define SOMTBaseClassEntryC__get_somtIDLScopedName SOMTEntryC__get_somtIDLScopedName
#define SOMTBaseClassEntryC__get_somtCScopedName SOMTEntryC__get_somtCScopedName
#define SOMTBaseClassEntryC_somtGetModifierValue SOMTEntryC_somtGetModifierValue
#define SOMTBaseClassEntryC_somtGetFirstModifier SOMTEntryC_somtGetFirstModifier
#define SOMTBaseClassEntryC_somtGetNextModifier SOMTEntryC_somtGetNextModifier
#define SOMTBaseClassEntryC_somtFormatModifier SOMTEntryC_somtFormatModifier
#define SOMTBaseClassEntryC_somtGetModifierList SOMTEntryC_somtGetModifierList
#define SOMTBaseClassEntryC_somtSetEntryStruct SOMTEntryC_somtSetEntryStruct
#define SOMTBaseClassEntryC_somInit SOMObject_somInit
#define SOMTBaseClassEntryC_somUninit SOMObject_somUninit
#define SOMTBaseClassEntryC_somPrintSelf SOMObject_somPrintSelf
#define SOMTBaseClassEntryC_somDumpSelf SOMObject_somDumpSelf
#define SOMTBaseClassEntryC_somDefaultInit SOMObject_somDefaultInit
#define SOMTBaseClassEntryC_somDestruct SOMObject_somDestruct
#define SOMTBaseClassEntryC_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define SOMTBaseClassEntryC_somDefaultAssign SOMObject_somDefaultAssign
#define SOMTBaseClassEntryC_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define SOMTBaseClassEntryC_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define SOMTBaseClassEntryC_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define SOMTBaseClassEntryC_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define SOMTBaseClassEntryC_somDefaultVAssign SOMObject_somDefaultVAssign
#define SOMTBaseClassEntryC_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define SOMTBaseClassEntryC_somFree SOMObject_somFree
#define SOMTBaseClassEntryC_somGetClass SOMObject_somGetClass
#define SOMTBaseClassEntryC_somGetClassName SOMObject_somGetClassName
#define SOMTBaseClassEntryC_somGetSize SOMObject_somGetSize
#define SOMTBaseClassEntryC_somIsA SOMObject_somIsA
#define SOMTBaseClassEntryC_somIsInstanceOf SOMObject_somIsInstanceOf
#define SOMTBaseClassEntryC_somRespondsTo SOMObject_somRespondsTo
#define SOMTBaseClassEntryC_somDispatch SOMObject_somDispatch
#define SOMTBaseClassEntryC_somClassDispatch SOMObject_somClassDispatch
#define SOMTBaseClassEntryC_somCastObj SOMObject_somCastObj
#define SOMTBaseClassEntryC_somResetObj SOMObject_somResetObj
#define SOMTBaseClassEntryC_somDispatchV SOMObject_somDispatchV
#define SOMTBaseClassEntryC_somDispatchL SOMObject_somDispatchL
#define SOMTBaseClassEntryC_somDispatchA SOMObject_somDispatchA
#define SOMTBaseClassEntryC_somDispatchD SOMObject_somDispatchD
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_SOMTBaseClassEntryC_h */
