
/*
 * This file was generated by the SOM Compiler.
 * FileName: scstruct.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.17
 *     SOM Emitter emith: 2.47
 */

/*
 *   COMPONENT_NAME: some
 * 
 *   ORIGINS: 27
 * 
 * 
 *    25H7912  (C)  COPYRIGHT International Business Machines Corp. 1992,1994,1996
 *   All Rights Reserved
 *   Licensed Materials - Property of IBM
 *   US Government Users Restricted Rights - Use, duplication or
 *   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 *  @(#) somc/sctypes.h 2.7 12/26/95 16:26:17 [7/30/96 14:46:04]
 * 
 */


#ifndef SOM_SOMTStructEntryC_h
#define SOM_SOMTStructEntryC_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef SOMTStructEntryC
#define SOMTStructEntryC SOMObject
#endif
#include <scentry.h>

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef SOMTEntryC
    #define SOMTEntryC SOMObject
#endif /* SOMTEntryC */
#ifndef SOMTEmitC
    #define SOMTEmitC SOMObject
#endif /* SOMTEmitC */
#ifndef SOMTMetaClassEntryC
    #define SOMTMetaClassEntryC SOMObject
#endif /* SOMTMetaClassEntryC */
#ifndef SOMTAttributeEntryC
    #define SOMTAttributeEntryC SOMObject
#endif /* SOMTAttributeEntryC */
#ifndef SOMTTypedefEntryC
    #define SOMTTypedefEntryC SOMObject
#endif /* SOMTTypedefEntryC */
#ifndef SOMTBaseClassEntryC
    #define SOMTBaseClassEntryC SOMObject
#endif /* SOMTBaseClassEntryC */
#ifndef SOMTPassthruEntryC
    #define SOMTPassthruEntryC SOMObject
#endif /* SOMTPassthruEntryC */
#ifndef SOMTDataEntryC
    #define SOMTDataEntryC SOMObject
#endif /* SOMTDataEntryC */
#ifndef SOMTMethodEntryC
    #define SOMTMethodEntryC SOMObject
#endif /* SOMTMethodEntryC */
#ifndef SOMTClassEntryC
    #define SOMTClassEntryC SOMObject
#endif /* SOMTClassEntryC */
#ifndef SOMTModuleEntryC
    #define SOMTModuleEntryC SOMObject
#endif /* SOMTModuleEntryC */
#ifndef SOMTParameterEntryC
    #define SOMTParameterEntryC SOMObject
#endif /* SOMTParameterEntryC */
#ifndef SOMTStructEntryC
    #define SOMTStructEntryC SOMObject
#endif /* SOMTStructEntryC */
#ifndef SOMTUnionEntryC
    #define SOMTUnionEntryC SOMObject
#endif /* SOMTUnionEntryC */
#ifndef SOMTEnumEntryC
    #define SOMTEnumEntryC SOMObject
#endif /* SOMTEnumEntryC */
#ifndef SOMTConstEntryC
    #define SOMTConstEntryC SOMObject
#endif /* SOMTConstEntryC */
#ifndef SOMTSequenceEntryC
    #define SOMTSequenceEntryC SOMObject
#endif /* SOMTSequenceEntryC */
#ifndef SOMTStringEntryC
    #define SOMTStringEntryC SOMObject
#endif /* SOMTStringEntryC */
#ifndef SOMTEnumNameEntryC
    #define SOMTEnumNameEntryC SOMObject
#endif /* SOMTEnumNameEntryC */
#ifndef SOMTCommonEntryC
    #define SOMTCommonEntryC SOMObject
#endif /* SOMTCommonEntryC */
#ifndef SOMTUserDefinedTypeEntryC
    #define SOMTUserDefinedTypeEntryC SOMObject
#endif /* SOMTUserDefinedTypeEntryC */

/*
 * End of bindings for IDL types.
 */

#define SOMTStructEntryC_MajorVersion 2
#define SOMTStructEntryC_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define SOMTStructEntryCNewClass c
#pragma linkage(c, system)
#define SOMTStructEntryCClassData d
#define SOMTStructEntryCCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define SOMTStructEntryC_classObj SOMTStructEntryCClassData.classObject
#define _SOMTStructEntryC SOMTStructEntryC_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK SOMTStructEntryCNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(SOMTStructEntryCNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct SOMTStructEntryCClassDataStructure {
	SOMClass *classObject;
	somMToken _get_somtStructClass;
	somMToken _get_somtIsException;
	somMToken somtGetFirstMember;
	somMToken somtGetNextMember;
} SOMDLINK SOMTStructEntryCClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct SOMTStructEntryCCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK SOMTStructEntryCCClassData;

/*
 * New and Renew macros for SOMTStructEntryC
 */
#define SOMTStructEntryCNew() \
   ( _SOMTStructEntryC ? \
	_somNew(_SOMTStructEntryC) \
	: ( SOMTStructEntryCNewClass(\
		SOMTStructEntryC_MajorVersion, \
		SOMTStructEntryC_MinorVersion),\
	   _somNew(_SOMTStructEntryC)))
#define SOMTStructEntryCRenew(buf) \
   ( _SOMTStructEntryC ? \
	_somRenew(_SOMTStructEntryC, buf) \
	: ( SOMTStructEntryCNewClass(\
		SOMTStructEntryC_MajorVersion, \
		SOMTStructEntryC_MinorVersion),\
	   _somRenew(_SOMTStructEntryC, buf)))

/*
 * Override method: somDumpSelfInt
 */
#define SOMTStructEntryC_somDumpSelfInt(somSelf,level) \
	SOMObject_somDumpSelfInt(somSelf,level)

/*
 * Override method: somtSetSymbolsOnEntry
 */
#define SOMTStructEntryC_somtSetSymbolsOnEntry(somSelf,emitter,prefix) \
	SOMTEntryC_somtSetSymbolsOnEntry(somSelf,emitter,prefix)

/*
 * New Method: somtGetFirstMember
 */
typedef SOMTTypedefEntryC*   SOMLINK somTP_SOMTStructEntryC_somtGetFirstMember(SOMTStructEntryC *somSelf);
#pragma linkage(somTP_SOMTStructEntryC_somtGetFirstMember, system)
typedef somTP_SOMTStructEntryC_somtGetFirstMember *somTD_SOMTStructEntryC_somtGetFirstMember;
/*
 *  The first member of the struct.
 */
#define somMD_SOMTStructEntryC_somtGetFirstMember "::SOMTStructEntryC::somtGetFirstMember"
#define SOMTStructEntryC_somtGetFirstMember(somSelf) \
    (SOM_Resolve(somSelf, SOMTStructEntryC, somtGetFirstMember) \
	(somSelf))
#ifndef SOMGD_somtGetFirstMember
    #if (defined(_somtGetFirstMember) || defined(__somtGetFirstMember))
        #undef _somtGetFirstMember
        #undef __somtGetFirstMember
        #define SOMGD_somtGetFirstMember 1
    #else
        #define _somtGetFirstMember SOMTStructEntryC_somtGetFirstMember
    #endif /* _somtGetFirstMember */
#endif /* SOMGD_somtGetFirstMember */

/*
 * New Method: somtGetNextMember
 */
typedef SOMTTypedefEntryC*   SOMLINK somTP_SOMTStructEntryC_somtGetNextMember(SOMTStructEntryC *somSelf);
#pragma linkage(somTP_SOMTStructEntryC_somtGetNextMember, system)
typedef somTP_SOMTStructEntryC_somtGetNextMember *somTD_SOMTStructEntryC_somtGetNextMember;
/*
 *  The next member of the struct, relative to the previous call
 *  to this method or somtGetFirstMember.
 */
#define somMD_SOMTStructEntryC_somtGetNextMember "::SOMTStructEntryC::somtGetNextMember"
#define SOMTStructEntryC_somtGetNextMember(somSelf) \
    (SOM_Resolve(somSelf, SOMTStructEntryC, somtGetNextMember) \
	(somSelf))
#ifndef SOMGD_somtGetNextMember
    #if (defined(_somtGetNextMember) || defined(__somtGetNextMember))
        #undef _somtGetNextMember
        #undef __somtGetNextMember
        #define SOMGD_somtGetNextMember 1
    #else
        #define _somtGetNextMember SOMTStructEntryC_somtGetNextMember
    #endif /* _somtGetNextMember */
#endif /* SOMGD_somtGetNextMember */

/*
 * New Method: _get_somtStructClass
 */
typedef SOMTClassEntryC*   SOMLINK somTP_SOMTStructEntryC__get_somtStructClass(SOMTStructEntryC *somSelf);
#pragma linkage(somTP_SOMTStructEntryC__get_somtStructClass, system)
typedef somTP_SOMTStructEntryC__get_somtStructClass *somTD_SOMTStructEntryC__get_somtStructClass;
/*
 *  The class in which the structure was defined.
 */
#define somMD_SOMTStructEntryC__get_somtStructClass "::SOMTStructEntryC::_get_somtStructClass"
#define SOMTStructEntryC__get_somtStructClass(somSelf) \
    (SOM_Resolve(somSelf, SOMTStructEntryC, _get_somtStructClass) \
	(somSelf))
#ifndef SOMGD_get_somtStructClass
    #if (defined(_get_somtStructClass) || defined(__get_somtStructClass))
        #undef _get_somtStructClass
        #undef __get_somtStructClass
        #define SOMGD_get_somtStructClass 1
    #else
        #define __get_somtStructClass SOMTStructEntryC__get_somtStructClass
    #endif /* __get_somtStructClass */
#endif /* SOMGD_get_somtStructClass */

/*
 * New Method: _get_somtIsException
 */
typedef boolean   SOMLINK somTP_SOMTStructEntryC__get_somtIsException(SOMTStructEntryC *somSelf);
#pragma linkage(somTP_SOMTStructEntryC__get_somtIsException, system)
typedef somTP_SOMTStructEntryC__get_somtIsException *somTD_SOMTStructEntryC__get_somtIsException;
/*
 *  Whether the structure is really an exception.
 */
#define somMD_SOMTStructEntryC__get_somtIsException "::SOMTStructEntryC::_get_somtIsException"
#define SOMTStructEntryC__get_somtIsException(somSelf) \
    (SOM_Resolve(somSelf, SOMTStructEntryC, _get_somtIsException) \
	(somSelf))
#ifndef SOMGD_get_somtIsException
    #if (defined(_get_somtIsException) || defined(__get_somtIsException))
        #undef _get_somtIsException
        #undef __get_somtIsException
        #define SOMGD_get_somtIsException 1
    #else
        #define __get_somtIsException SOMTStructEntryC__get_somtIsException
    #endif /* __get_somtIsException */
#endif /* SOMGD_get_somtIsException */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define SOMTStructEntryC__get_somtEntryName SOMTEntryC__get_somtEntryName
#define SOMTStructEntryC__set_somtEntryName SOMTEntryC__set_somtEntryName
#define SOMTStructEntryC__get_somtElementType SOMTEntryC__get_somtElementType
#define SOMTStructEntryC__set_somtElementType SOMTEntryC__set_somtElementType
#define SOMTStructEntryC__get_somtElementTypeName SOMTEntryC__get_somtElementTypeName
#define SOMTStructEntryC__get_somtEntryComment SOMTEntryC__get_somtEntryComment
#define SOMTStructEntryC__get_somtSourceLineNumber SOMTEntryC__get_somtSourceLineNumber
#define SOMTStructEntryC__get_somtTypeCode SOMTEntryC__get_somtTypeCode
#define SOMTStructEntryC__get_somtIsReference SOMTEntryC__get_somtIsReference
#define SOMTStructEntryC__get_somtIDLScopedName SOMTEntryC__get_somtIDLScopedName
#define SOMTStructEntryC__get_somtCScopedName SOMTEntryC__get_somtCScopedName
#define SOMTStructEntryC_somtGetModifierValue SOMTEntryC_somtGetModifierValue
#define SOMTStructEntryC_somtGetFirstModifier SOMTEntryC_somtGetFirstModifier
#define SOMTStructEntryC_somtGetNextModifier SOMTEntryC_somtGetNextModifier
#define SOMTStructEntryC_somtFormatModifier SOMTEntryC_somtFormatModifier
#define SOMTStructEntryC_somtGetModifierList SOMTEntryC_somtGetModifierList
#define SOMTStructEntryC_somtSetEntryStruct SOMTEntryC_somtSetEntryStruct
#define SOMTStructEntryC_somInit SOMObject_somInit
#define SOMTStructEntryC_somUninit SOMObject_somUninit
#define SOMTStructEntryC_somPrintSelf SOMObject_somPrintSelf
#define SOMTStructEntryC_somDumpSelf SOMObject_somDumpSelf
#define SOMTStructEntryC_somDefaultInit SOMObject_somDefaultInit
#define SOMTStructEntryC_somDestruct SOMObject_somDestruct
#define SOMTStructEntryC_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define SOMTStructEntryC_somDefaultAssign SOMObject_somDefaultAssign
#define SOMTStructEntryC_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define SOMTStructEntryC_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define SOMTStructEntryC_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define SOMTStructEntryC_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define SOMTStructEntryC_somDefaultVAssign SOMObject_somDefaultVAssign
#define SOMTStructEntryC_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define SOMTStructEntryC_somFree SOMObject_somFree
#define SOMTStructEntryC_somGetClass SOMObject_somGetClass
#define SOMTStructEntryC_somGetClassName SOMObject_somGetClassName
#define SOMTStructEntryC_somGetSize SOMObject_somGetSize
#define SOMTStructEntryC_somIsA SOMObject_somIsA
#define SOMTStructEntryC_somIsInstanceOf SOMObject_somIsInstanceOf
#define SOMTStructEntryC_somRespondsTo SOMObject_somRespondsTo
#define SOMTStructEntryC_somDispatch SOMObject_somDispatch
#define SOMTStructEntryC_somClassDispatch SOMObject_somClassDispatch
#define SOMTStructEntryC_somCastObj SOMObject_somCastObj
#define SOMTStructEntryC_somResetObj SOMObject_somResetObj
#define SOMTStructEntryC_somDispatchV SOMObject_somDispatchV
#define SOMTStructEntryC_somDispatchL SOMObject_somDispatchL
#define SOMTStructEntryC_somDispatchA SOMObject_somDispatchA
#define SOMTStructEntryC_somDispatchD SOMObject_somDispatchD
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_SOMTStructEntryC_h */
