
/*
 * This file was generated by the SOM Compiler.
 * FileName: scusrtyp.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.17
 *     SOM Emitter emith: 2.47
 */

/*
 *   COMPONENT_NAME: some
 * 
 *   ORIGINS: 27
 * 
 * 
 *    25H7912  (C)  COPYRIGHT International Business Machines Corp. 1992,1994,1996
 *   All Rights Reserved
 *   Licensed Materials - Property of IBM
 *   US Government Users Restricted Rights - Use, duplication or
 *   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 *  @(#) somc/sctypes.h 2.7 12/26/95 16:26:17 [7/30/96 14:46:04]
 * 
 */


#ifndef SOM_SOMTUserDefinedTypeEntryC_h
#define SOM_SOMTUserDefinedTypeEntryC_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef SOMTUserDefinedTypeEntryC
#define SOMTUserDefinedTypeEntryC SOMObject
#endif
#include <sccommon.h>

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef SOMTEntryC
    #define SOMTEntryC SOMObject
#endif /* SOMTEntryC */
#ifndef SOMTEmitC
    #define SOMTEmitC SOMObject
#endif /* SOMTEmitC */
#ifndef SOMTMetaClassEntryC
    #define SOMTMetaClassEntryC SOMObject
#endif /* SOMTMetaClassEntryC */
#ifndef SOMTAttributeEntryC
    #define SOMTAttributeEntryC SOMObject
#endif /* SOMTAttributeEntryC */
#ifndef SOMTTypedefEntryC
    #define SOMTTypedefEntryC SOMObject
#endif /* SOMTTypedefEntryC */
#ifndef SOMTBaseClassEntryC
    #define SOMTBaseClassEntryC SOMObject
#endif /* SOMTBaseClassEntryC */
#ifndef SOMTPassthruEntryC
    #define SOMTPassthruEntryC SOMObject
#endif /* SOMTPassthruEntryC */
#ifndef SOMTDataEntryC
    #define SOMTDataEntryC SOMObject
#endif /* SOMTDataEntryC */
#ifndef SOMTMethodEntryC
    #define SOMTMethodEntryC SOMObject
#endif /* SOMTMethodEntryC */
#ifndef SOMTClassEntryC
    #define SOMTClassEntryC SOMObject
#endif /* SOMTClassEntryC */
#ifndef SOMTModuleEntryC
    #define SOMTModuleEntryC SOMObject
#endif /* SOMTModuleEntryC */
#ifndef SOMTParameterEntryC
    #define SOMTParameterEntryC SOMObject
#endif /* SOMTParameterEntryC */
#ifndef SOMTStructEntryC
    #define SOMTStructEntryC SOMObject
#endif /* SOMTStructEntryC */
#ifndef SOMTUnionEntryC
    #define SOMTUnionEntryC SOMObject
#endif /* SOMTUnionEntryC */
#ifndef SOMTEnumEntryC
    #define SOMTEnumEntryC SOMObject
#endif /* SOMTEnumEntryC */
#ifndef SOMTConstEntryC
    #define SOMTConstEntryC SOMObject
#endif /* SOMTConstEntryC */
#ifndef SOMTSequenceEntryC
    #define SOMTSequenceEntryC SOMObject
#endif /* SOMTSequenceEntryC */
#ifndef SOMTStringEntryC
    #define SOMTStringEntryC SOMObject
#endif /* SOMTStringEntryC */
#ifndef SOMTEnumNameEntryC
    #define SOMTEnumNameEntryC SOMObject
#endif /* SOMTEnumNameEntryC */
#ifndef SOMTCommonEntryC
    #define SOMTCommonEntryC SOMObject
#endif /* SOMTCommonEntryC */
#ifndef SOMTUserDefinedTypeEntryC
    #define SOMTUserDefinedTypeEntryC SOMObject
#endif /* SOMTUserDefinedTypeEntryC */

/*
 * End of bindings for IDL types.
 */

#define SOMTUserDefinedTypeEntryC_MajorVersion 2
#define SOMTUserDefinedTypeEntryC_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define SOMTUserDefinedTypeEntryCNewClass c
#pragma linkage(c, system)
#define SOMTUserDefinedTypeEntryCClassData d
#define SOMTUserDefinedTypeEntryCCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define SOMTUserDefinedTypeEntryC_classObj SOMTUserDefinedTypeEntryCClassData.classObject
#define _SOMTUserDefinedTypeEntryC SOMTUserDefinedTypeEntryC_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK SOMTUserDefinedTypeEntryCNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(SOMTUserDefinedTypeEntryCNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct SOMTUserDefinedTypeEntryCClassDataStructure {
	SOMClass *classObject;
	somMToken _get_somtOriginalTypedef;
	somMToken _get_somtBaseTypeObj;
} SOMDLINK SOMTUserDefinedTypeEntryCClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct SOMTUserDefinedTypeEntryCCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK SOMTUserDefinedTypeEntryCCClassData;

/*
 * New and Renew macros for SOMTUserDefinedTypeEntryC
 */
#define SOMTUserDefinedTypeEntryCNew() \
   ( _SOMTUserDefinedTypeEntryC ? \
	_somNew(_SOMTUserDefinedTypeEntryC) \
	: ( SOMTUserDefinedTypeEntryCNewClass(\
		SOMTUserDefinedTypeEntryC_MajorVersion, \
		SOMTUserDefinedTypeEntryC_MinorVersion),\
	   _somNew(_SOMTUserDefinedTypeEntryC)))
#define SOMTUserDefinedTypeEntryCRenew(buf) \
   ( _SOMTUserDefinedTypeEntryC ? \
	_somRenew(_SOMTUserDefinedTypeEntryC, buf) \
	: ( SOMTUserDefinedTypeEntryCNewClass(\
		SOMTUserDefinedTypeEntryC_MajorVersion, \
		SOMTUserDefinedTypeEntryC_MinorVersion),\
	   _somRenew(_SOMTUserDefinedTypeEntryC, buf)))

/*
 * Override method: somtSetSymbolsOnEntry
 */
#define SOMTUserDefinedTypeEntryC_somtSetSymbolsOnEntry(somSelf,emitter,prefix) \
	SOMTEntryC_somtSetSymbolsOnEntry(somSelf,emitter,prefix)

/*
 * Override method: somDumpSelfInt
 */
#define SOMTUserDefinedTypeEntryC_somDumpSelfInt(somSelf,level) \
	SOMObject_somDumpSelfInt(somSelf,level)

/*
 * Override method: _get_somtTypeObj
 */
#define SOMTUserDefinedTypeEntryC__get_somtTypeObj(somSelf) \
	SOMTCommonEntryC__get_somtTypeObj(somSelf)

/*
 * New Method: _get_somtOriginalTypedef
 */
typedef SOMTTypedefEntryC*   SOMLINK somTP_SOMTUserDefinedTypeEntryC__get_somtOriginalTypedef(SOMTUserDefinedTypeEntryC *somSelf);
#pragma linkage(somTP_SOMTUserDefinedTypeEntryC__get_somtOriginalTypedef, system)
typedef somTP_SOMTUserDefinedTypeEntryC__get_somtOriginalTypedef *somTD_SOMTUserDefinedTypeEntryC__get_somtOriginalTypedef;
/*
 *  The typedef that defined the user-defined type.
 */
#define somMD_SOMTUserDefinedTypeEntryC__get_somtOriginalTypedef "::SOMTUserDefinedTypeEntryC::_get_somtOriginalTypedef"
#define SOMTUserDefinedTypeEntryC__get_somtOriginalTypedef(somSelf) \
    (SOM_Resolve(somSelf, SOMTUserDefinedTypeEntryC, _get_somtOriginalTypedef) \
	(somSelf))
#ifndef SOMGD_get_somtOriginalTypedef
    #if (defined(_get_somtOriginalTypedef) || defined(__get_somtOriginalTypedef))
        #undef _get_somtOriginalTypedef
        #undef __get_somtOriginalTypedef
        #define SOMGD_get_somtOriginalTypedef 1
    #else
        #define __get_somtOriginalTypedef SOMTUserDefinedTypeEntryC__get_somtOriginalTypedef
    #endif /* __get_somtOriginalTypedef */
#endif /* SOMGD_get_somtOriginalTypedef */

/*
 * New Method: _get_somtBaseTypeObj
 */
typedef SOMTEntryC*   SOMLINK somTP_SOMTUserDefinedTypeEntryC__get_somtBaseTypeObj(SOMTUserDefinedTypeEntryC *somSelf);
#pragma linkage(somTP_SOMTUserDefinedTypeEntryC__get_somtBaseTypeObj, system)
typedef somTP_SOMTUserDefinedTypeEntryC__get_somtBaseTypeObj *somTD_SOMTUserDefinedTypeEntryC__get_somtBaseTypeObj;
/*
 *  The object representing the base type
 *  (eg. short, float, unsigned long) of a user-defined type,
 *  skipping over any intermediate user-defined types.
 */
#define somMD_SOMTUserDefinedTypeEntryC__get_somtBaseTypeObj "::SOMTUserDefinedTypeEntryC::_get_somtBaseTypeObj"
#define SOMTUserDefinedTypeEntryC__get_somtBaseTypeObj(somSelf) \
    (SOM_Resolve(somSelf, SOMTUserDefinedTypeEntryC, _get_somtBaseTypeObj) \
	(somSelf))
#ifndef SOMGD_get_somtBaseTypeObj
    #if (defined(_get_somtBaseTypeObj) || defined(__get_somtBaseTypeObj))
        #undef _get_somtBaseTypeObj
        #undef __get_somtBaseTypeObj
        #define SOMGD_get_somtBaseTypeObj 1
    #else
        #define __get_somtBaseTypeObj SOMTUserDefinedTypeEntryC__get_somtBaseTypeObj
    #endif /* __get_somtBaseTypeObj */
#endif /* SOMGD_get_somtBaseTypeObj */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define SOMTUserDefinedTypeEntryC__get_somtPtrs SOMTCommonEntryC__get_somtPtrs
#define SOMTUserDefinedTypeEntryC__get_somtArrayDimsString SOMTCommonEntryC__get_somtArrayDimsString
#define SOMTUserDefinedTypeEntryC_somtGetFirstArrayDimension SOMTCommonEntryC_somtGetFirstArrayDimension
#define SOMTUserDefinedTypeEntryC_somtGetNextArrayDimension SOMTCommonEntryC_somtGetNextArrayDimension
#define SOMTUserDefinedTypeEntryC__get_somtSourceText SOMTCommonEntryC__get_somtSourceText
#define SOMTUserDefinedTypeEntryC__get_somtType SOMTCommonEntryC__get_somtType
#define SOMTUserDefinedTypeEntryC__get_somtVisibility SOMTCommonEntryC__get_somtVisibility
#define SOMTUserDefinedTypeEntryC_somtIsArray SOMTCommonEntryC_somtIsArray
#define SOMTUserDefinedTypeEntryC_somtIsPointer SOMTCommonEntryC_somtIsPointer
#define SOMTUserDefinedTypeEntryC__get_somtEntryName SOMTEntryC__get_somtEntryName
#define SOMTUserDefinedTypeEntryC__set_somtEntryName SOMTEntryC__set_somtEntryName
#define SOMTUserDefinedTypeEntryC__get_somtElementType SOMTEntryC__get_somtElementType
#define SOMTUserDefinedTypeEntryC__set_somtElementType SOMTEntryC__set_somtElementType
#define SOMTUserDefinedTypeEntryC__get_somtElementTypeName SOMTEntryC__get_somtElementTypeName
#define SOMTUserDefinedTypeEntryC__get_somtEntryComment SOMTEntryC__get_somtEntryComment
#define SOMTUserDefinedTypeEntryC__get_somtSourceLineNumber SOMTEntryC__get_somtSourceLineNumber
#define SOMTUserDefinedTypeEntryC__get_somtTypeCode SOMTEntryC__get_somtTypeCode
#define SOMTUserDefinedTypeEntryC__get_somtIsReference SOMTEntryC__get_somtIsReference
#define SOMTUserDefinedTypeEntryC__get_somtIDLScopedName SOMTEntryC__get_somtIDLScopedName
#define SOMTUserDefinedTypeEntryC__get_somtCScopedName SOMTEntryC__get_somtCScopedName
#define SOMTUserDefinedTypeEntryC_somtGetModifierValue SOMTEntryC_somtGetModifierValue
#define SOMTUserDefinedTypeEntryC_somtGetFirstModifier SOMTEntryC_somtGetFirstModifier
#define SOMTUserDefinedTypeEntryC_somtGetNextModifier SOMTEntryC_somtGetNextModifier
#define SOMTUserDefinedTypeEntryC_somtFormatModifier SOMTEntryC_somtFormatModifier
#define SOMTUserDefinedTypeEntryC_somtGetModifierList SOMTEntryC_somtGetModifierList
#define SOMTUserDefinedTypeEntryC_somtSetEntryStruct SOMTEntryC_somtSetEntryStruct
#define SOMTUserDefinedTypeEntryC_somInit SOMObject_somInit
#define SOMTUserDefinedTypeEntryC_somUninit SOMObject_somUninit
#define SOMTUserDefinedTypeEntryC_somPrintSelf SOMObject_somPrintSelf
#define SOMTUserDefinedTypeEntryC_somDumpSelf SOMObject_somDumpSelf
#define SOMTUserDefinedTypeEntryC_somDefaultInit SOMObject_somDefaultInit
#define SOMTUserDefinedTypeEntryC_somDestruct SOMObject_somDestruct
#define SOMTUserDefinedTypeEntryC_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define SOMTUserDefinedTypeEntryC_somDefaultAssign SOMObject_somDefaultAssign
#define SOMTUserDefinedTypeEntryC_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define SOMTUserDefinedTypeEntryC_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define SOMTUserDefinedTypeEntryC_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define SOMTUserDefinedTypeEntryC_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define SOMTUserDefinedTypeEntryC_somDefaultVAssign SOMObject_somDefaultVAssign
#define SOMTUserDefinedTypeEntryC_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define SOMTUserDefinedTypeEntryC_somFree SOMObject_somFree
#define SOMTUserDefinedTypeEntryC_somGetClass SOMObject_somGetClass
#define SOMTUserDefinedTypeEntryC_somGetClassName SOMObject_somGetClassName
#define SOMTUserDefinedTypeEntryC_somGetSize SOMObject_somGetSize
#define SOMTUserDefinedTypeEntryC_somIsA SOMObject_somIsA
#define SOMTUserDefinedTypeEntryC_somIsInstanceOf SOMObject_somIsInstanceOf
#define SOMTUserDefinedTypeEntryC_somRespondsTo SOMObject_somRespondsTo
#define SOMTUserDefinedTypeEntryC_somDispatch SOMObject_somDispatch
#define SOMTUserDefinedTypeEntryC_somClassDispatch SOMObject_somClassDispatch
#define SOMTUserDefinedTypeEntryC_somCastObj SOMObject_somCastObj
#define SOMTUserDefinedTypeEntryC_somResetObj SOMObject_somResetObj
#define SOMTUserDefinedTypeEntryC_somDispatchV SOMObject_somDispatchV
#define SOMTUserDefinedTypeEntryC_somDispatchL SOMObject_somDispatchL
#define SOMTUserDefinedTypeEntryC_somDispatchA SOMObject_somDispatchA
#define SOMTUserDefinedTypeEntryC_somDispatchD SOMObject_somDispatchD
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_SOMTUserDefinedTypeEntryC_h */
