//
//   COMPONENT_NAME: somr
//
//   ORIGINS: 27
//
//
//   10H9767, 10H9769  (C) COPYRIGHT International Business Machines Corp. 1992,1994
//   All Rights Reserved
//   Licensed Materials - Property of IBM
//   US Government Users Restricted Rights - Use, duplication or
//   disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
//
//# @(#) 1.7 src/somr/somrcls.idl, somr, som2.1 9/1/94 15:55:49 [7/30/96 15:24:44]


#ifndef somrcls_idl
#define somrcls_idl

#include <replicbl.idl>
#include <somrmcls.idl>
interface SOMRReplicableObject : SOMRReplicbl
{

    char somrLoggingType( );

    boolean somrReplicableExemptMethod( in somId methodId );

#ifdef __SOMIDL__

implementation {
    releaseorder: somrLoggingType, somrReplicableExemptMethod;

    //# Class Modifiers
    majorversion = 2;
    minorversion = 1;
    filestem = somrcls;
    metaclass = SOMRReplicable;



    //# Method Modifiers
    logging: noset;
    somrRepInit: override;
    somrApplyUpdates: override;
    
    //# Behavioral Expression

    
    //# Instance Data

    char  logging;


    //# Invariant

    };
#endif /* __SOMIDL__ */
};
#endif  /* somrcls_idl */
