
/*
 * This file was generated by the SOM Compiler.
 * FileName: tdeqlink.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.17
 *     SOM Emitter emith: 2.47
 */

/*
 *    COMPONENT_NAME: somuc
 * 
 *    ORIGINS: 82, 81, 27
 * 
 * 
 *     25H7912  (C)  COPYRIGHT International Business Machines Corp. 1992,1996,1996
 *    All Rights Reserved
 *    Licensed Materials - Property of IBM
 *    US Government Users Restricted Rights - Use, duplication or
 *    disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 * 
 *    Copyright © 1988, 1989 Apple Computer, Inc. All rights reserved.
 * 
 * CLASS_NAME: somf_TDequeLinkable
 * 
 * DESCRIPTION: This class provides the user with a generic MLinkable
 *              containing a long value.
 * 
 */


#ifndef SOM_somf_TDequeLinkable_h
#define SOM_somf_TDequeLinkable_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef somf_TDequeLinkable
#define somf_TDequeLinkable SOMObject
#endif
#include <mlink.h>

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef somf_MCollectible
    #define somf_MCollectible SOMObject
#endif /* somf_MCollectible */

/*
 * End of bindings for IDL types.
 */

#define somf_TDequeLinkable_MajorVersion 2
#define somf_TDequeLinkable_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define somf_TDequeLinkableNewClass c
#pragma linkage(c, system)
#define somf_TDequeLinkableClassData d
#define somf_TDequeLinkableCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define somf_TDequeLinkable_classObj somf_TDequeLinkableClassData.classObject
#define _somf_TDequeLinkable somf_TDequeLinkable_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK somf_TDequeLinkableNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(somf_TDequeLinkableNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct somf_TDequeLinkableClassDataStructure {
	SOMClass *classObject;
	somMToken somfGetValue;
	somMToken somfSetValue;
	somMToken somfTDequeLinkableInitDDM;
	somMToken somfTDequeLinkableInitDD;
} SOMDLINK somf_TDequeLinkableClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct somf_TDequeLinkableCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK somf_TDequeLinkableCClassData;

/*
 * New and Renew macros for somf_TDequeLinkable
 */
#define somf_TDequeLinkableNew() \
   ( _somf_TDequeLinkable ? \
	_somNew(_somf_TDequeLinkable) \
	: ( somf_TDequeLinkableNewClass(\
		somf_TDequeLinkable_MajorVersion, \
		somf_TDequeLinkable_MinorVersion),\
	   _somNew(_somf_TDequeLinkable)))
#define somf_TDequeLinkableRenew(buf) \
   ( _somf_TDequeLinkable ? \
	_somRenew(_somf_TDequeLinkable, buf) \
	: ( somf_TDequeLinkableNewClass(\
		somf_TDequeLinkable_MajorVersion, \
		somf_TDequeLinkable_MinorVersion),\
	   _somRenew(_somf_TDequeLinkable, buf)))

/*
 * Override method: somInit
 */
#define somf_TDequeLinkable_somInit(somSelf) \
	SOMObject_somInit(somSelf)

/*
 * New Method: somfTDequeLinkableInitDDM
 */
typedef somf_TDequeLinkable*   SOMLINK somTP_somf_TDequeLinkable_somfTDequeLinkableInitDDM(somf_TDequeLinkable *somSelf, Environment *ev, 
		somf_TDequeLinkable* previous, 
		somf_TDequeLinkable* next, 
		somf_MCollectible* v);
#pragma linkage(somTP_somf_TDequeLinkable_somfTDequeLinkableInitDDM, system)
typedef somTP_somf_TDequeLinkable_somfTDequeLinkableInitDDM *somTD_somf_TDequeLinkable_somfTDequeLinkableInitDDM;
/*
 *  This method initializes the somf_TDequeLinkable object.
 */
#define somMD_somf_TDequeLinkable_somfTDequeLinkableInitDDM "::somf_TDequeLinkable::somfTDequeLinkableInitDDM"
#define somf_TDequeLinkable_somfTDequeLinkableInitDDM(somSelf,ev,previous,next,v) \
    (SOM_Resolve(somSelf, somf_TDequeLinkable, somfTDequeLinkableInitDDM) \
	(somSelf,ev,previous,next,v))
#ifndef SOMGD_somfTDequeLinkableInitDDM
    #if (defined(_somfTDequeLinkableInitDDM) || defined(__somfTDequeLinkableInitDDM))
        #undef _somfTDequeLinkableInitDDM
        #undef __somfTDequeLinkableInitDDM
        #define SOMGD_somfTDequeLinkableInitDDM 1
    #else
        #define _somfTDequeLinkableInitDDM somf_TDequeLinkable_somfTDequeLinkableInitDDM
    #endif /* _somfTDequeLinkableInitDDM */
#endif /* SOMGD_somfTDequeLinkableInitDDM */

/*
 * New Method: somfTDequeLinkableInitDD
 */
typedef somf_TDequeLinkable*   SOMLINK somTP_somf_TDequeLinkable_somfTDequeLinkableInitDD(somf_TDequeLinkable *somSelf, Environment *ev, 
		somf_TDequeLinkable* previous, 
		somf_TDequeLinkable* next);
#pragma linkage(somTP_somf_TDequeLinkable_somfTDequeLinkableInitDD, system)
typedef somTP_somf_TDequeLinkable_somfTDequeLinkableInitDD *somTD_somf_TDequeLinkable_somfTDequeLinkableInitDD;
/*
 *  This method initializes the somf_TDequeLinkable object.
 */
#define somMD_somf_TDequeLinkable_somfTDequeLinkableInitDD "::somf_TDequeLinkable::somfTDequeLinkableInitDD"
#define somf_TDequeLinkable_somfTDequeLinkableInitDD(somSelf,ev,previous,next) \
    (SOM_Resolve(somSelf, somf_TDequeLinkable, somfTDequeLinkableInitDD) \
	(somSelf,ev,previous,next))
#ifndef SOMGD_somfTDequeLinkableInitDD
    #if (defined(_somfTDequeLinkableInitDD) || defined(__somfTDequeLinkableInitDD))
        #undef _somfTDequeLinkableInitDD
        #undef __somfTDequeLinkableInitDD
        #define SOMGD_somfTDequeLinkableInitDD 1
    #else
        #define _somfTDequeLinkableInitDD somf_TDequeLinkable_somfTDequeLinkableInitDD
    #endif /* _somfTDequeLinkableInitDD */
#endif /* SOMGD_somfTDequeLinkableInitDD */

/*
 * New Method: somfGetValue
 */
typedef somf_MCollectible*   SOMLINK somTP_somf_TDequeLinkable_somfGetValue(somf_TDequeLinkable *somSelf, Environment *ev);
#pragma linkage(somTP_somf_TDequeLinkable_somfGetValue, system)
typedef somTP_somf_TDequeLinkable_somfGetValue *somTD_somf_TDequeLinkable_somfGetValue;
/*
 *  This method gets the value of the somf_TDequeLinkable.
 */
#define somMD_somf_TDequeLinkable_somfGetValue "::somf_TDequeLinkable::somfGetValue"
#define somf_TDequeLinkable_somfGetValue(somSelf,ev) \
    (SOM_Resolve(somSelf, somf_TDequeLinkable, somfGetValue) \
	(somSelf,ev))
#ifndef SOMGD_somfGetValue
    #if (defined(_somfGetValue) || defined(__somfGetValue))
        #undef _somfGetValue
        #undef __somfGetValue
        #define SOMGD_somfGetValue 1
    #else
        #define _somfGetValue somf_TDequeLinkable_somfGetValue
    #endif /* _somfGetValue */
#endif /* SOMGD_somfGetValue */

/*
 * New Method: somfSetValue
 */
typedef void   SOMLINK somTP_somf_TDequeLinkable_somfSetValue(somf_TDequeLinkable *somSelf, Environment *ev, 
		somf_MCollectible* v);
#pragma linkage(somTP_somf_TDequeLinkable_somfSetValue, system)
typedef somTP_somf_TDequeLinkable_somfSetValue *somTD_somf_TDequeLinkable_somfSetValue;
/*
 *  This method sets the value of the somf_TDequeLinkable.
 */
#define somMD_somf_TDequeLinkable_somfSetValue "::somf_TDequeLinkable::somfSetValue"
#define somf_TDequeLinkable_somfSetValue(somSelf,ev,v) \
    (SOM_Resolve(somSelf, somf_TDequeLinkable, somfSetValue) \
	(somSelf,ev,v))
#ifndef SOMGD_somfSetValue
    #if (defined(_somfSetValue) || defined(__somfSetValue))
        #undef _somfSetValue
        #undef __somfSetValue
        #define SOMGD_somfSetValue 1
    #else
        #define _somfSetValue somf_TDequeLinkable_somfSetValue
    #endif /* _somfSetValue */
#endif /* SOMGD_somfSetValue */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define somf_TDequeLinkable_somfMLinkableInit somf_MLinkable_somfMLinkableInit
#define somf_TDequeLinkable_somfGetNext somf_MLinkable_somfGetNext
#define somf_TDequeLinkable_somfSetNext somf_MLinkable_somfSetNext
#define somf_TDequeLinkable_somfGetPrevious somf_MLinkable_somfGetPrevious
#define somf_TDequeLinkable_somfSetPrevious somf_MLinkable_somfSetPrevious
#define somf_TDequeLinkable_somDefaultInit SOMObject_somDefaultInit
#define somf_TDequeLinkable_somDestruct SOMObject_somDestruct
#define somf_TDequeLinkable_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define somf_TDequeLinkable_somDefaultAssign SOMObject_somDefaultAssign
#define somf_TDequeLinkable_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define somf_TDequeLinkable_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define somf_TDequeLinkable_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define somf_TDequeLinkable_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define somf_TDequeLinkable_somDefaultVAssign SOMObject_somDefaultVAssign
#define somf_TDequeLinkable_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define somf_TDequeLinkable_somFree SOMObject_somFree
#define somf_TDequeLinkable_somUninit SOMObject_somUninit
#define somf_TDequeLinkable_somGetClass SOMObject_somGetClass
#define somf_TDequeLinkable_somGetClassName SOMObject_somGetClassName
#define somf_TDequeLinkable_somGetSize SOMObject_somGetSize
#define somf_TDequeLinkable_somIsA SOMObject_somIsA
#define somf_TDequeLinkable_somIsInstanceOf SOMObject_somIsInstanceOf
#define somf_TDequeLinkable_somRespondsTo SOMObject_somRespondsTo
#define somf_TDequeLinkable_somDispatch SOMObject_somDispatch
#define somf_TDequeLinkable_somClassDispatch SOMObject_somClassDispatch
#define somf_TDequeLinkable_somCastObj SOMObject_somCastObj
#define somf_TDequeLinkable_somResetObj SOMObject_somResetObj
#define somf_TDequeLinkable_somDispatchV SOMObject_somDispatchV
#define somf_TDequeLinkable_somDispatchL SOMObject_somDispatchL
#define somf_TDequeLinkable_somDispatchA SOMObject_somDispatchA
#define somf_TDequeLinkable_somDispatchD SOMObject_somDispatchD
#define somf_TDequeLinkable_somPrintSelf SOMObject_somPrintSelf
#define somf_TDequeLinkable_somDumpSelf SOMObject_somDumpSelf
#define somf_TDequeLinkable_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_somf_TDequeLinkable_h */
